import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  ru: {
    staking: {
      connectWalletTitle: "Подключите кошелек для стейкинга",
      closingInterval: "закрывающий интервал",
      newStake: "Новый стейк",
      amount: "Сумма (USDT)",
      amountPlaceholder: "Введите сумму...",
      balanceHelper: "Баланс: {balance} USDT | Мин: 10 USDT | Без макс. лимита",
      autoCompoundEvery: "Автокомпаундинг каждые {interval}",
      approveAndStake: "Одобрить и стейкнуть ${amount}",
      stakeBtn: "Стейкнуть ${amount}",
      yourStakes: "Ваши стейки",
      active: "активен",
      noActiveStakesDesc: "Нет активных стейков. Создайте первый стейк, чтобы начать зарабатывать!",
      stakeCount: "{count} стейк{count, plural, one {} few {а} many {ов} other {ов}}",
      totalStaked: "Всего стейкнуто",
      tierHeader: "Лимит 3X",
      pendingCompoundProfit: "Ожидаемая прибыль компаундинга",
      autoCompoundBtn: "Автокомпаундинг ({count})",
      accruing: "Накапливается",
      harvestBtn: "Собрать ${amount}",
      minHarvestStake: "Мин $10/стейк",
      minHarvestAmount: "Мин $10",
      total: "итого",
      tierCol: "Уровень",
      stakedCol: "Стейкнуто",
      earnedCol: "Заработано",
      harvestedCol: "Собрано",
      capCol: "Лимит 3X",
      startedCol: "Начат",
      statusCol: "Статус",
      actionCol: "Действие",
      statusActive: "Активен",
      statusCapped: "Достиг лимита",
      statusClosed: "Закрыт",
      unstake: "Вывести",
      unstakeConfirm: "Вывести стейк #{index}?\n\nВы стейкнули ${original} USDT.\nВы получите ~${preview} в KAIRO\n(80% от основной суммы, минус любой собранный доход).\n\nЭто действие необратимо. Продолжить?",
      calcTitle: "Калькулятор компаундинга",
      calcSubtitle: "Прогноз накопления прибыли с течением времени",
      calcStakeAmount: "Сумма стейка (USDT)",
      calcEnterAmount: "Введите сумму стейка...",
      calcDuration: "Срок: {count} {count, plural, one {месяц} few {месяца} many {месяцев} other {месяцев}}",
      calcProjectedProfit: "Прогноз прибыли",
      calcTier: "Уровень",
      calcFrequency: "Частота",
      calcCompounds: "Компаундинги",
      calcNote: "0,15% за компаундинг · Уровень и частота определяются автоматически по сумме",
      levelUnlockTitle: "Разблокировка уровня командных дивидендов",
      levelUnlockDesc: "Разблокируйте больше уровней командных дивидендов, добавляя прямых рефералов. У вас сейчас {count} прямых рефералов и {unlocked} / 15 разблокированных уровней.",
      directs: "прямых",
      intervals: "интервалы"
    },
    p2p: {
      subtitle: "Атомарная одноранговая торговля KAIRO",
      connectWalletTitle: "Подключите кошелек для торговли",
      connectWalletDesc: "Доступ к одноранговой торговле KAIRO",
      dexPrice: "Цена DEX",
      vol: "объём",
      noActiveBuyOrders: "Нет активных ордеров на покупку",
      noActiveSellOrders: "Нет активных ордеров на продажу",
      fill: "Исполнить",
      enterAmount: "Введите сумму...",
      usdtAmount: "Сумма USDT",
      kairoAmount: "Сумма KAIRO",
      max: "МАКС: {amount}",
      balanceLabel: "Баланс: {amount} {token}",
      dexReferencePrice: "Справочная цена DEX",
      tradingFee: "Комиссия за сделку",
      estimated: "Ожидается {token}",
      approveAndCreateBuy: "Одобрить и создать ордер на покупку",
      createBuyOrder: "Создать ордер на покупку",
      approveAndCreateSell: "Одобрить и создать ордер на продажу",
      createSellOrder: "Создать ордер на продажу",
      noActiveOrders: "У вас нет активных ордеров.",
      noActiveOrdersDesc: "Создайте ордер на покупку или продажу, чтобы начать.",
      myBuyOrders: "Мои ордера на покупку",
      mySellOrders: "Мои ордера на продажу",
      cancel: "Отмена",
      remaining: "${amount} осталось",
      filledOfTotal: "${filled} исполнено из ${total} всего",
      kairoRemaining: "{amount} KAIRO осталось"
    },
    swap: {
      title: "Свап",
      subtitle: "Односторонний свап с комиссией {fee}% и дефляционным сжиганием",
      connectWalletTitle: "Подключите кошелек для свапа",
      connectWalletDesc: "Односторонний свап KAIRO в USDT с дефляционным сжиганием",
      poolUsdt: "USDT в пуле",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Свап включает дефляционное сжигание",
      youPay: "Вы платите",
      youReceive: "Вы получаете (оценочно)",
      rate: "Курс",
      fee: "Комиссия ({percent}%)",
      minOutput: "Мин. вывод ({slippage}% проскальзывание)",
      slippage: "Проскальзывание:",
      priceImpact: "Влияние на цену",
      approveAndSwap: "Одобрить и свапнуть",
      swapBtn: "Свап KAIRO → USDT",
      max: "МАКС: {amount}"
    },
    referralNetwork: {
      title: "Реферальная сеть",
      rank: "Ранг",
      directReferrals: "Прямые рефералы",
      directActive: "{count} активны",
      directBusiness: "Прямой объём",
      referralStakes: "реферальные стейки",
      teamBusiness: "Командный объём",
      totalDownlineVolume: "общий объём даунлайна",
      shareLink: "Поделитесь ссылкой, чтобы приглашать новых участников и зарабатывать многоуровневые комиссии.",
      earnDirect: "Зарабатывайте 5% прямой комиссии + 15-уровневые командные дивиденды с каждого реферального стейка."
    },
    rankDividend: {
      title: "Дивиденд ранга",
      subtitle: "Достигайте рангов через командный объём и зарабатывайте периодические зарплатные вознаграждения",
      connectWalletTitle: "Подключите кошелек",
      rankChangeDetected: "Обнаружено изменение ранга: {from} → {to}",
      rankChangeDesc: "Ваш таймер зарплаты сбросится при подтверждении. Нажмите ниже, чтобы обновить ранг.",
      updateRank: "Обновить ранг",
      currentRank: "Текущий ранг",
      rankLevel: "Уровень {level} / 10",
      rankSalary: "Зарплата ранга",
      perPeriod: "за период",
      harvestable: "Доступно к сбору",
      crystallized: "кристаллизовано",
      harvested: "Собрано",
      totalClaimed: "всего получено",
      rankProgress: "Прогресс ранга",
      earningPerPeriod: "Заработка ${amount} / период",
      pending: "Ожидание: ${amount} · нажмите Синхронизировать для кристаллизации",
      syncRankChange: "Синхронизировать изменение ранга",
      syncRankSalary: "Синхронизировать зарплату ранга (+${amount})",
      nothingToSync: "Нечего синхронизировать",
      harvestBtn: "Собрать ${amount}",
      nothingToHarvest: "Нечего собирать",
      teamVolumeTitle: "Командный объём",
      totalTeamVolume: "Общий командный объём",
      next: "Далее: {rank}",
      targetMet: "Цель достигнута!",
      needMoreVolume: "Нужно ещё ${amount} квалифицирующего объёма",
      progressAchieved: "{percent}% достигнуто",
      directReferrals: "Прямые рефералы",
      activeDirects: "Активные прямые",
      unlockedLevels: "Разблокированные уровни",
      harvestIncomeTitle: "Доход от сбора",
      direct: "Прямой",
      team: "Команда",
      rank: "Ранг",
      harvest: "Сбор",
      fiftyPctCapRule: "Правило 50% лимита на ветвь",
      fiftyPctDesc: "Для каждой цели ранга максимум 50% порога этого конкретного ранга может быть зачтено из любой одной ветви. Ваш личный объём не учитывается для квалификации ранга. Даже если одна ветвь имеет огромный объём, только 50% цели ранга будет зачтено.",
      totalTeamVolumeLabel: "Общий командный объём",
      largestLeg: "Крупнейшая ветвь",
      numberOfLegs: "Количество ветвей",
      qualifyingVolume: "Квалифицирующий объём",
      legVolumeBreakdown: "Разбивка объёма по ветвям",
      leg: "Ветвь {index}",
      maxCredited: "(макс ${amount})",
      rankTargetsTitle: "Цели и зарплаты рангов",
      rankCol: "Ранг",
      teamVolumeTargetCol: "Цель командного объёма",
      salaryCol: "Зарплата / Период",
      progressCol: "Прогресс",
      statusCol: "Статус",
      achieved: "Достигнут",
      nextTarget: "Следующая цель",
      locked: "Заблокирован",
      salaryHistoryTitle: "История зарплат",
      records: "{count} записей",
      loadingHistory: "Загрузка истории...",
      noSalaryHistory: "Истории зарплат пока нет. Достигните ранга, чтобы начать зарабатывать!",
      typeCol: "Тип",
      dateCol: "Дата",
      amountCol: "Сумма",
      txCol: "Тх",
      salaryCredited: "Зарплата начислена",
      harvestedLabel: "Собрано"
    },
    teamDividend: {
      title: "Командный дивиденд",
      subtitle: "Зарабатывайте с 15 уровней командной прибыли от компаундинга в зависимости от количества прямых рефералов. Неактивные пользователи в цепочке пропускаются — только активные стейкхолдеры учитываются как уровни.",
      connectWalletTitle: "Подключите кошелек",
      connectWalletDesc: "Просмотр доходов от командных дивидендов",
      unlockedLevels: "Разблокированные уровни",
      directReferrals: "Прямые рефералы",
      moreForNext: "{count} ещё до следующего уровня",
      maxLevelsUnlocked: "Все уровни разблокированы",
      directBusiness: "Прямой объём",
      referralStakes: "Реферальные стейки",
      teamVolume: "Командный объём",
      totalDownlineVolume: "Общий объём даунлайна",
      teamDividend: "Командный дивиденд",
      harvest: "Собрать",
      activeLabel: "активен",
      levelBreakdownTitle: "Разбивка по уровням — Полные детали",
      levelBreakdownDesc: "Каждый уровень зарабатывает процент от прибыли компаундинга, генерируемой активными пользователями на этой сжатой глубине. Неактивные пользователи пропускаются — они не учитываются как уровень. L1: 10%, L2-L10: 5% каждый, L11-L15: 2% каждый. Разблокируйте уровни, добавляя прямых рефералов: 1-5 прямых = 1-5 уровней, затем каждый дополнительный прямой = ещё 2 уровня (макс 15 при 10 прямых).",
      levelCol: "Уровень",
      rateCol: "Ставка",
      membersCol: "Участники",
      businessCol: "Объём",
      earnedCol: "Заработано",
      statusCol: "Статус",
      statusActive: "Активен",
      statusNext: "Далее",
      statusLocked: "Заблокирован",
      total: "Итого",
      levelLabel: "Уровень {level}",
      directsNeeded: "{count} прям{count, plural, one {ой} few {ых} many {ых} other {ых}}",
      levelActivationTracker: "Трекер активации уровней",
      levelActivationDesc: "У вас {directs} прямых рефералов, разблокировано {unlocked} / 15 уровней командных дивидендов.",
      ppl: "чел.",
      legs: "{count} ветвей",
      legVolumeBreakdown: "Разбивка объёма по ветвям",
      legVolumeDesc: "Каждый прямой реферал образует «ветвь». Их общий нисходящий объём вкладывается в ваш командный объём и квалификацию ранга.",
      refCol: "Реферал",
      selfStakeCol: "Собственный стейк",
      legVolumeCol: "Объём ветви",
      shareCol: "Доля",
      howItWorks: "Как работают командные дивиденды",
      how1: "Когда любой пользователь в вашей команде делает компаундинг своего стейка, генерируется прибыль (0,15% за интервал).",
      how2: "Вы зарабатываете процент от этой прибыли в зависимости от уровня: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Требуется активный стейк и место в лимите FIFO. Доходы ограничены 3X от вашего общего стейка."
    },
    cms: {
      subtitle: "Покупайте подписки CMS и зарабатывайте вознаграждения KAIRO",
      connectWalletTitle: "Базовое членство",
      notAvailable: "CMS недоступен",
      notAvailableDesc: "Контракт базового членства (CMS) ещё не развёрнут.",
      yourSubscriptions: "Ваши подписки",
      remainingSlots: "Осталось слотов",
      subscriptionStatus: "Статус подписки",
      active: "Активна",
      ended: "Завершена",
      purchaseSubscription: "Купить подписку",
      subscriptionEnded: "Период подписки завершён",
      numberOfSubscriptions: "Количество подписок",
      enterAmount: "Введите количество...",
      subscriptionDetails: "Детали подписки",
      pricePerSub: "Цена за подписку:",
      loyaltyRewardPerSub: "Награда за лояльность за подписку:",
      totalCost: "Итоговая стоимость:",
      youllEarn: "Вы заработаете:",
      approveUsdt: "Одобрить USDT",
      subscribeBtn: "Подписаться ({cost} USDT)",
      completeRegistrationFirst: "Пожалуйста, сначала завершите регистрацию",
      claimRewards: "Получить вознаграждения",
      alreadyClaimed: "Вы уже получили свои вознаграждения",
      loyaltyRewards: "Награды за лояльность",
      leadershipRewards: "Лидерские вознаграждения",
      totalClaimable: "Итого к получению",
      claimRules: "Правила получения",
      claimRule1: "Однократное получение (используй или потеряй)",
      claimRule2: "Требуется активный стейк в StakingManager",
      claimRule3: "Ограничено стоимостью активного стейка (излишек удаляется)",
      claimRule4: "90% минтится вам, 10% дефляционно (не минтится)",
      excessWarning: "Внимание: {amount} KAIRO будут безвозвратно удалены (превышает лимит стейка)",
      maxClaimable: "Макс. к получению (на основе стейка):",
      claimRewardsBtn: "Получить вознаграждения",
      leadershipRewardsTitle: "Лидерские вознаграждения (5 уровней)",
      levelCol: "Уровень",
      requiredDirectsCol: "Нужно прямых",
      rewardPerSubCol: "Награда/Подписка",
      subscriptionsCol: "Подписки",
      earnedCol: "Заработано (KAIRO)",
      levelLabel: "Уровень {level}",
      howCmsWorks: "Как работает CMS",
      subscriptionBenefits: "Преимущества подписки",
      benefit1: "10 USDT за подписку (макс 10 000 всего)",
      benefit2: "Зарабатывайте 5 KAIRO награды за лояльность за подписку",
      benefit3: "Зарабатывайте лидерские вознаграждения с 5 уровней рефералов",
      benefit4: "Получите один раз с активным стейком (используй или потеряй)",
      referralRewards: "Реферальные вознаграждения",
      level1Desc: "1 KAIRO за подписку (0 прямых требуется)",
      level2Desc: "0,5 KAIRO за подписку (2 прямых требуется)",
      level3Desc: "0,5 KAIRO за подписку (3 прямых требуется)",
      level4Desc: "0,25 KAIRO за подписку (4 прямых требуется)",
      level5Desc: "0,25 KAIRO за подписку (5 прямых требуется)",
      level1: "Уровень 1:",
      level2: "Уровень 2:",
      level3: "Уровень 3:",
      level4: "Уровень 4:",
      level5: "Уровень 5:"
    },
    analytics: {
      title: "Аналитика протокола",
      subtitle: "Статистика экосистемы KAIRO в реальном времени",
      kairoPrice: "Цена KAIRO",
      marketCap: "Рыночная капитализация",
      poolLiquidityUsdt: "Ликвидность пула (USDT)",
      totalBurned: "Всего сожжено",
      tokenSupply: "Эмиссия токенов",
      deflationaryNote: "Дефляционные механизмы через сжигание",
      circulating: "В обращении",
      burned: "Сожжено",
      effectiveSupply: "Эффективная эмиссия",
      socialLock: "Социальная блокировка",
      burnRate: "Ставка сжигания",
      liquidityPool: "Пул ликвидности",
      dexPoolComposition: "Состав пула DEX",
      kairoInPool: "KAIRO в пуле",
      usdtInPool: "USDT в пуле",
      pricePerSupply: "Цена (USDT / Общая эмиссия)"
    },
    portfolio: {
      totalPortfolioValue: "Общая стоимость портфеля",
      activeStakes: "Активные стейки",
      totalStaked: "Всего стейкнуто",
      totalEarned: "Всего заработано",
      remainingCapping: "Остаток лимита",
      kairoPrice: "Цена KAIRO",
      poolLiquidity: "Ликвидность пула",
      totalCirculation: "Общее обращение",
      harvestableAffiliate: "Доступно к сбору (Аффилиат)",
      activeDirects: "Активные прямые"
    },
    activeStakesTable: {
      title: "Активные стейки",
      loading: "Загрузка стейков...",
      empty: "Нет активных стейков. Начните стейкать, чтобы получать вознаграждения!",
      tierCount: "{count} {count, plural, one {уровень} few {уровня} many {уровней} other {уровней}}",
      stakeCount: "{count} стейк{count, plural, one {} few {а} many {ов} other {ов}}",
      stakedAmount: "Стейкнутая сумма",
      capProgress: "Прогресс лимита 3X",
      harvestable: "Доступно к сбору",
      harvested: "Собрано",
      totalEarned: "Всего заработано",
      pendingCompoundProfit: "Ожидаемая прибыль компаундинга",
      autoCompound: "Автокомпаундинг",
      autoCompoundBtn: "Автокомпаундинг ({count})",
      accruing: "Накапливается",
      harvest: "Собрать ${amount}",
      minHarvestStake: "Мин $10/стейк",
      minHarvestAmount: "Мин $10",
      intervals: "интервалы"
    },
    income: {
      title: "Сводка доходов",
      typesCount: "{count} типов",
      direct: "Прямая комиссия",
      team: "Командные дивиденды",
      rank: "Зарплата ранга",
      harvest: "Сбор",
      pendingHarvest: "Ожидаемый сбор",
      affiliateHarvested: "Аффилиат собран",
      directLabel: "Прямой",
      teamLabel: "Команда",
      rankLabel: "Ранг",
      stakingEarnings: "Доход от стейкинга",
      harvestedLabel: "Собрано",
      harvestableLabel: "Доступно к сбору"
    },
    faucet: {
      testnetFaucet: "Testnet-кран · Тестовые USDT",
      mintDesc: "Создайте тестовые USDT для разработки. Текущий баланс:",
      mint10000: "Создать 10 000 USDT",
      mint: "Создать",
      customPlaceholder: "своя сумма",
      mintingPending: "Создание тестовых USDT…",
      mintingDesc: "Отправка {amount} USDT на ваш кошелёк",
      mintedSuccess: "Создано {amount} тестовых USDT",
      mintFailed: "Ошибка создания",
      invalidAmount: "Недопустимая сумма"
    },
    common: {
      connectWalletTitle: "Подключите ваш кошелёк",
      connectWalletDesc: "Подключите кошелёк, чтобы просмотреть портфель, управлять стейками и отслеживать доходы."
    }
  },

  hi: {
    staking: {
      connectWalletTitle: "स्टेकिंग के लिए अपना वॉलेट कनेक्ट करें",
      closingInterval: "समापन अंतराल",
      newStake: "नया स्टेक",
      amount: "राशि (USDT)",
      amountPlaceholder: "राशि दर्ज करें...",
      balanceHelper: "बैलेंस: {balance} USDT | न्यूनतम: 10 USDT | अधिकतम सीमा नहीं",
      autoCompoundEvery: "हर {interval} पर ऑटो-कंपाउंड",
      approveAndStake: "अनुमोदन और स्टेक ${amount}",
      stakeBtn: "स्टेक ${amount}",
      yourStakes: "आपके स्टेक्स",
      active: "सक्रिय",
      noActiveStakesDesc: "अभी कोई सक्रिय स्टेक नहीं है। कमाई शुरू करने के लिए अपना पहला स्टेक बनाएं!",
      stakeCount: "{count} स्टेक",
      totalStaked: "कुल स्टेक्ड",
      tierHeader: "3X कैप",
      pendingCompoundProfit: "लंबित कंपाउंड लाभ",
      autoCompoundBtn: "ऑटो-कंपाउंड ({count})",
      accruing: "संचयी",
      harvestBtn: "हार्वेस्ट ${amount}",
      minHarvestStake: "न्यूनतम $10/स्टेक",
      minHarvestAmount: "न्यूनतम $10",
      total: "कुल",
      tierCol: "स्तर",
      stakedCol: "स्टेक्ड",
      earnedCol: "अर्जित",
      harvestedCol: "हार्वेस्टेड",
      capCol: "3X कैप",
      startedCol: "शुरू",
      statusCol: "स्थिति",
      actionCol: "क्रिया",
      statusActive: "सक्रिय",
      statusCapped: "सीमित",
      statusClosed: "बंद",
      unstake: "अनस्टेक",
      unstakeConfirm: "स्टेक #{index} हटाएं?\n\nआपने ${original} USDT स्टेक किए।\nआपको ~${preview} KAIRO मिलेंगे\n(80% मूलधन, घटाकर कोई लंबित हार्वेस्टेड आय)।\n\nयह क्रिया अपरिवर्तनीय है। जारी रखें?",
      calcTitle: "कंपाउंडिंग कैलकुलेटर",
      calcSubtitle: "समय के साथ संभावित लाभ संचय का अनुमान लगाएं",
      calcStakeAmount: "स्टेक राशि (USDT)",
      calcEnterAmount: "स्टेक राशि दर्ज करें...",
      calcDuration: "अवधि: {count} माह",
      calcProjectedProfit: "प्रक्षिप्त लाभ",
      calcTier: "स्तर",
      calcFrequency: "आवृत्ति",
      calcCompounds: "कंपाउंड्स",
      calcNote: "प्रति कंपाउंड 0.15% · स्तर और आवृत्ति राशि से स्वतः निर्धारित",
      levelUnlockTitle: "टीम डिविडेंड स्तर अनलॉक",
      levelUnlockDesc: "अधिक टीम डिविडेंड स्तर अनलॉक करने के लिए सीधे रेफरल जोड़ें। आपके पास वर्तमान में {count} सीधे रेफरल और {unlocked} / 15 स्तर अनलॉक हैं।",
      directs: "सीधे",
      intervals: "अंतराल"
    },
    p2p: {
      subtitle: "परमाणु पीयर-टू-पीयर KAIRO ट्रेडिंग",
      connectWalletTitle: "ट्रेडिंग के लिए अपना वॉलेट कनेक्ट करें",
      connectWalletDesc: "पीयर-टू-पीयर KAIRO ट्रेडिंग तक पहुंच",
      dexPrice: "DEX मूल्य",
      vol: "वॉल",
      noActiveBuyOrders: "कोई सक्रिय खरीद आदेश नहीं",
      noActiveSellOrders: "कोई सक्रिय बिक्री आदेश नहीं",
      fill: "भरें",
      enterAmount: "राशि दर्ज करें...",
      usdtAmount: "USDT राशि",
      kairoAmount: "KAIRO राशि",
      max: "अधिकतम: {amount}",
      balanceLabel: "बैलेंस: {amount} {token}",
      dexReferencePrice: "DEX संदर्भ मूल्य",
      tradingFee: "ट्रेडिंग शुल्क",
      estimated: "अनुमानित {token}",
      approveAndCreateBuy: "अनुमोदन और खरीद आदेश बनाएं",
      createBuyOrder: "खरीद आदेश बनाएं",
      approveAndCreateSell: "अनुमोदन और बिक्री आदेश बनाएं",
      createSellOrder: "बिक्री आदेश बनाएं",
      noActiveOrders: "आपके पास कोई सक्रिय आदेश नहीं है।",
      noActiveOrdersDesc: "शुरू करने के लिए एक खरीद या बिक्री आदेश बनाएं।",
      myBuyOrders: "मेरे खरीद आदेश",
      mySellOrders: "मेरे बिक्री आदेश",
      cancel: "रद्द करें",
      remaining: "${amount} शेष",
      filledOfTotal: "${total} में से ${filled} भरा",
      kairoRemaining: "{amount} KAIRO शेष"
    },
    swap: {
      title: "स्वैप",
      subtitle: "{fee}% शुल्क और डिफ्लेशनरी बर्न के साथ एकतरफा स्वैप",
      connectWalletTitle: "स्वैप के लिए अपना वॉलेट कनेक्ट करें",
      connectWalletDesc: "डिफ्लेशनरी बर्न के साथ एकतरफा KAIRO से USDT स्वैप",
      poolUsdt: "पूल USDT",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "स्वैप में डिफ्लेशनरी बर्न शामिल है",
      youPay: "आप भुगतान करते हैं",
      youReceive: "आप प्राप्त करते हैं (अनुमानित)",
      rate: "दर",
      fee: "शुल्क ({percent}%)",
      minOutput: "न्यूनतम आउटपुट ({slippage}% स्लिपेज)",
      slippage: "स्लिपेज:",
      priceImpact: "मूल्य प्रभाव",
      approveAndSwap: "अनुमोदन और स्वैप",
      swapBtn: "KAIRO → USDT स्वैप",
      max: "अधिकतम: {amount}"
    },
    referralNetwork: {
      title: "रेफरल नेटवर्क",
      rank: "रैंक",
      directReferrals: "सीधे रेफरल",
      directActive: "{count} सक्रिय",
      directBusiness: "सीधा व्यवसाय",
      referralStakes: "रेफरल स्टेक्स",
      teamBusiness: "टीम व्यवसाय",
      totalDownlineVolume: "कुल डाउनलाइन वॉल्यूम",
      shareLink: "नए सदस्य आमंत्रित करने और मल्टी-लेवल कमीशन कमाने के लिए अपना लिंक साझा करें।",
      earnDirect: "हर रेफरल स्टेक पर 5% सीधा कमीशन + 15-स्तरीय टीम डिविडेंड कमाएं।"
    },
    rankDividend: {
      title: "रैंक डिविडेंड",
      subtitle: "टीम वॉल्यूम के माध्यम से रैंक प्राप्त करें और आवधिक वेतन पुरस्कार अर्जित करें",
      connectWalletTitle: "अपना वॉलेट कनेक्ट करें",
      rankChangeDetected: "रैंक परिवर्तन का पता चला: {from} → {to}",
      rankChangeDesc: "पुष्टि करने पर आपका वेतन टाइमर रीसेट हो जाएगा। अपना रैंक अपडेट करने के लिए नीचे क्लिक करें।",
      updateRank: "रैंक अपडेट करें",
      currentRank: "वर्तमान रैंक",
      rankLevel: "स्तर {level} / 10",
      rankSalary: "रैंक वेतन",
      perPeriod: "प्रति अवधि",
      harvestable: "हार्वेस्टेबल",
      crystallized: "क्रिस्टलाइज्ड",
      harvested: "हार्वेस्टेड",
      totalClaimed: "कुल क्लेम्ड",
      rankProgress: "रैंक प्रगति",
      earningPerPeriod: "${amount} / अवधि कमा रहे हैं",
      pending: "लंबित: ${amount} · क्रिस्टलाइज करने के लिए सिंक क्लिक करें",
      syncRankChange: "रैंक परिवर्तन सिंक करें",
      syncRankSalary: "रैंक वेतन सिंक करें (+${amount})",
      nothingToSync: "सिंक करने के लिए कुछ नहीं",
      harvestBtn: "हार्वेस्ट ${amount}",
      nothingToHarvest: "हार्वेस्ट करने के लिए कुछ नहीं",
      teamVolumeTitle: "टीम वॉल्यूम",
      totalTeamVolume: "कुल टीम वॉल्यूम",
      next: "अगला: {rank}",
      targetMet: "लक्ष्य पूरा!",
      needMoreVolume: "${amount} और योग्य वॉल्यूम चाहिए",
      progressAchieved: "{percent}% पूरा",
      directReferrals: "सीधे रेफरल",
      activeDirects: "सक्रिय सीधे",
      unlockedLevels: "अनलॉक स्तर",
      harvestIncomeTitle: "हार्वेस्ट आय",
      direct: "सीधा",
      team: "टीम",
      rank: "रैंक",
      harvest: "हार्वेस्ट",
      fiftyPctCapRule: "50% प्रति-लेग कैप नियम",
      fiftyPctDesc: "प्रत्येक रैंक लक्ष्य के लिए, उस विशिष्ट रैंक की सीमा का अधिकतम 50% किसी एक लेग से जमा किया जा सकता है। आपका व्यक्तिगत वॉल्यूम रैंक योग्यता में नहीं गिना जाता। भले ही एक लेग का बड़ा वॉल्यूम हो, केवल 50% रैंक लक्ष्य जमा होगा।",
      totalTeamVolumeLabel: "कुल टीम वॉल्यूम",
      largestLeg: "सबसे बड़ा लेग",
      numberOfLegs: "लेग की संख्या",
      qualifyingVolume: "योग्य वॉल्यूम",
      legVolumeBreakdown: "लेग वॉल्यूम विभाजन",
      leg: "लेग {index}",
      maxCredited: "(अधिकतम ${amount})",
      rankTargetsTitle: "रैंक लक्ष्य और वेतन",
      rankCol: "रैंक",
      teamVolumeTargetCol: "टीम वॉल्यूम लक्ष्य",
      salaryCol: "वेतन / अवधि",
      progressCol: "प्रगति",
      statusCol: "स्थिति",
      achieved: "प्राप्त",
      nextTarget: "अगला लक्ष्य",
      locked: "लॉक्ड",
      salaryHistoryTitle: "वेतन इतिहास",
      records: "{count} रिकॉर्ड्स",
      loadingHistory: "इतिहास लोड हो रहा है...",
      noSalaryHistory: "अभी कोई वेतन इतिहास नहीं। कमाई शुरू करने के लिए रैंक प्राप्त करें!",
      typeCol: "प्रकार",
      dateCol: "तारीख",
      amountCol: "राशि",
      txCol: "Tx",
      salaryCredited: "वेतन जमा",
      harvestedLabel: "हार्वेस्टेड"
    },
    teamDividend: {
      title: "टीम डिविडेंड",
      subtitle: "अपने सीधे रेफरल संख्या के आधार पर टीम कंपाउंड लाभ के 15 स्तरों से कमाएं। श्रृंखला में निष्क्रिय उपयोगकर्ताओं को छोड़ दिया जाता है — केवल सक्रिय स्टेकहोल्डर स्तर के रूप में गिने जाते हैं।",
      connectWalletTitle: "अपना वॉलेट कनेक्ट करें",
      connectWalletDesc: "अपनी टीम डिविडेंड आय देखें",
      unlockedLevels: "अनलॉक स्तर",
      directReferrals: "सीधे रेफरल",
      moreForNext: "अगले स्तर के लिए {count} और",
      maxLevelsUnlocked: "अधिकतम स्तर अनलॉक",
      directBusiness: "सीधा व्यवसाय",
      referralStakes: "रेफरल स्टेक्स",
      teamVolume: "टीम वॉल्यूम",
      totalDownlineVolume: "कुल डाउनलाइन वॉल्यूम",
      teamDividend: "टीम डिविडेंड",
      harvest: "हार्वेस्ट",
      activeLabel: "सक्रिय",
      levelBreakdownTitle: "स्तर विभाजन — पूर्ण विवरण",
      levelBreakdownDesc: "प्रत्येक स्तर उस संकुचित गहराई पर सक्रिय उपयोगकर्ताओं द्वारा उत्पन्न कंपाउंड लाभ का प्रतिशत कमाता है। निष्क्रिय उपयोगकर्ताओं को छोड़ दिया जाता है — वे स्तर के रूप में नहीं गिने जाते। L1: 10%, L2-L10: 5% प्रत्येक, L11-L15: 2% प्रत्येक। सीधे रेफरल जोड़कर स्तर अनलॉक करें: 1-5 सीधे = 1-5 स्तर, फिर प्रत्येक अतिरिक्त सीधा = 2 और स्तर (10 सीधे पर अधिकतम 15)।",
      levelCol: "स्तर",
      rateCol: "दर",
      membersCol: "सदस्य",
      businessCol: "व्यवसाय",
      earnedCol: "अर्जित",
      statusCol: "स्थिति",
      statusActive: "सक्रिय",
      statusNext: "अगला",
      statusLocked: "लॉक्ड",
      total: "कुल",
      levelLabel: "स्तर {level}",
      directsNeeded: "{count} सीधे",
      levelActivationTracker: "स्तर सक्रियण ट्रैकर",
      levelActivationDesc: "आपके पास {directs} सीधे रेफरल हैं, जो {unlocked} / 15 टीम डिविडेंड स्तर अनलॉक करते हैं।",
      ppl: "लोग",
      legs: "{count} लेग्स",
      legVolumeBreakdown: "लेग वॉल्यूम विभाजन",
      legVolumeDesc: "प्रत्येक सीधा रेफरल एक \"लेग\" बनाता है। उनका कुल डाउनस्ट्रीम वॉल्यूम आपके टीम वॉल्यूम और रैंक योग्यता में योगदान देता है।",
      refCol: "रेफरल",
      selfStakeCol: "स्वयं का स्टेक",
      legVolumeCol: "लेग वॉल्यूम",
      shareCol: "हिस्सा",
      howItWorks: "टीम डिविडेंड कैसे काम करते हैं",
      how1: "जब आपकी टीम में कोई भी उपयोगकर्ता अपने स्टेक को कंपाउंड करता है, तो लाभ उत्पन्न होता है (0.15% प्रति अंतराल)।",
      how2: "आप स्तर के आधार पर उस लाभ का प्रतिशत कमाते हैं: L1=10%, L2-L10=5%, L11-L15=2%।",
      how3: "सक्रिय स्टेक और FIFO कैप स्थान आवश्यक। आय आपके कुल स्टेक के 3X तक सीमित है।"
    },
    cms: {
      subtitle: "CMS सदस्यताएं खरीदें और KAIRO पुरस्कार अर्जित करें",
      connectWalletTitle: "कोर मेम्बरशिप",
      notAvailable: "CMS उपलब्ध नहीं",
      notAvailableDesc: "कोर मेम्बरशिप सदस्यता अनुबंध अभी तैनात नहीं है।",
      yourSubscriptions: "आपकी सदस्यताएं",
      remainingSlots: "शेष स्लॉट",
      subscriptionStatus: "सदस्यता स्थिति",
      active: "सक्रिय",
      ended: "समाप्त",
      purchaseSubscription: "सदस्यता खरीदें",
      subscriptionEnded: "सदस्यता अवधि समाप्त हो गई",
      numberOfSubscriptions: "सदस्यताओं की संख्या",
      enterAmount: "राशि दर्ज करें...",
      subscriptionDetails: "सदस्यता विवरण",
      pricePerSub: "प्रति सदस्यता मूल्य:",
      loyaltyRewardPerSub: "प्रति सदस्यता लयल्टी पुरस्कार:",
      totalCost: "कुल लागत:",
      youllEarn: "आप कमाएंगे:",
      approveUsdt: "USDT अनुमोदित करें",
      subscribeBtn: "सदस्यता लें ({cost} USDT)",
      completeRegistrationFirst: "कृपया पहले पंजीकरण पूरा करें",
      claimRewards: "पुरस्कार क्लेम करें",
      alreadyClaimed: "आपने पहले ही अपने पुरस्कार क्लेम कर लिए हैं",
      loyaltyRewards: "लयल्टी पुरस्कार",
      leadershipRewards: "लीडरशिप पुरस्कार",
      totalClaimable: "कुल क्लेमेबल",
      claimRules: "क्लेम नियम",
      claimRule1: "केवल एकबार क्लेम (इस्तेमाल करें या खो दें)",
      claimRule2: "StakingManager में सक्रिय स्टेक आवश्यक",
      claimRule3: "सक्रिय स्टेक मूल्य द्वारा सीमित (अतिरिक्त हटाया जाता है)",
      claimRule4: "90% आपको मिंट, 10% डिफ्लेशनरी (मिंट नहीं)",
      excessWarning: "चेतावनी: {amount} KAIRO स्थायी रूप से हटाए जाएंगे (स्टेक कैप से अधिक)",
      maxClaimable: "अधिकतम क्लेमेबल (स्टेक के आधार पर):",
      claimRewardsBtn: "पुरस्कार क्लेम करें",
      leadershipRewardsTitle: "लीडरशिप पुरस्कार (5 स्तर)",
      levelCol: "स्तर",
      requiredDirectsCol: "आवश्यक सीधे",
      rewardPerSubCol: "पुरस्कार/सदस्यता",
      subscriptionsCol: "सदस्यताएं",
      earnedCol: "अर्जित (KAIRO)",
      levelLabel: "स्तर {level}",
      howCmsWorks: "CMS कैसे काम करता है",
      subscriptionBenefits: "सदस्यता लाभ",
      benefit1: "प्रति सदस्यता 10 USDT (अधिकतम 10,000 कुल)",
      benefit2: "प्रति सदस्यता 5 KAIRO लयल्टी पुरस्कार कमाएं",
      benefit3: "5 रेफरल स्तरों से लीडरशिप पुरस्कार कमाएं",
      benefit4: "सक्रिय स्टेक के साथ एकबार क्लेम करें (इस्तेमाल करें या खो दें)",
      referralRewards: "रेफरल पुरस्कार",
      level1Desc: "प्रति सदस्यता 1 KAIRO (0 सीधे आवश्यक)",
      level2Desc: "प्रति सदस्यता 0.5 KAIRO (2 सीधे आवश्यक)",
      level3Desc: "प्रति सदस्यता 0.5 KAIRO (3 सीधे आवश्यक)",
      level4Desc: "प्रति सदस्यता 0.25 KAIRO (4 सीधे आवश्यक)",
      level5Desc: "प्रति सदस्यता 0.25 KAIRO (5 सीधे आवश्यक)",
      level1: "स्तर 1:",
      level2: "स्तर 2:",
      level3: "स्तर 3:",
      level4: "स्तर 4:",
      level5: "स्तर 5:"
    },
    analytics: {
      title: "प्रोटोकॉल एनालिटिक्स",
      subtitle: "रियल-टाइम KAIRO इकोसिस्टम सांख्यिकी",
      kairoPrice: "KAIRO मूल्य",
      marketCap: "मार्केट कैप",
      poolLiquidityUsdt: "पूल लिक्विडिटी (USDT)",
      totalBurned: "कुल बर्न",
      tokenSupply: "टोकन सप्लाई",
      deflationaryNote: "बर्न के माध्यम से डिफ्लेशनरी तंत्र",
      circulating: "सर्कुलेटिंग",
      burned: "बर्न",
      effectiveSupply: "प्रभावी सप्लाई",
      socialLock: "सोशल लॉक",
      burnRate: "बर्न रेट",
      liquidityPool: "लिक्विडिटी पूल",
      dexPoolComposition: "DEX पूल रचना",
      kairoInPool: "पूल में KAIRO",
      usdtInPool: "पूल में USDT",
      pricePerSupply: "मूल्य (USDT / कुल सप्लाई)"
    },
    portfolio: {
      totalPortfolioValue: "कुल पोर्टफोलियो मूल्य",
      activeStakes: "सक्रिय स्टेक्स",
      totalStaked: "कुल स्टेक्ड",
      totalEarned: "कुल अर्जित",
      remainingCapping: "शेष कैपिंग",
      kairoPrice: "KAIRO मूल्य",
      poolLiquidity: "पूल लिक्विडिटी",
      totalCirculation: "कुल सर्कुलेशन",
      harvestableAffiliate: "हार्वेस्टेबल (एफिलिएट)",
      activeDirects: "सक्रिय सीधे"
    },
    activeStakesTable: {
      title: "सक्रिय स्टेक्स",
      loading: "स्टेक्स लोड हो रहे हैं...",
      empty: "कोई सक्रिय स्टेक नहीं। पुरस्कार कमाने के लिए स्टेकिंग शुरू करें!",
      tierCount: "{count} स्तर(एं)",
      stakeCount: "{count} स्टेक",
      stakedAmount: "स्टेक्ड राशि",
      capProgress: "3X कैप प्रगति",
      harvestable: "हार्वेस्टेबल",
      harvested: "हार्वेस्टेड",
      totalEarned: "कुल अर्जित",
      pendingCompoundProfit: "लंबित कंपाउंड लाभ",
      autoCompound: "ऑटो-कंपाउंड",
      autoCompoundBtn: "ऑटो-कंपाउंड ({count})",
      accruing: "संचयी",
      harvest: "हार्वेस्ट ${amount}",
      minHarvestStake: "न्यूनतम $10/स्टेक",
      minHarvestAmount: "न्यूनतम $10",
      intervals: "अंतराल"
    },
    income: {
      title: "आय सारांश",
      typesCount: "{count} प्रकार",
      direct: "सीधा कमीशन",
      team: "टीम डिविडेंड",
      rank: "रैंक वेतन",
      harvest: "हार्वेस्ट",
      pendingHarvest: "लंबित हार्वेस्ट",
      affiliateHarvested: "एफिलिएट हार्वेस्टेड",
      directLabel: "सीधा",
      teamLabel: "टीम",
      rankLabel: "रैंक",
      stakingEarnings: "स्टेकिंग आय",
      harvestedLabel: "हार्वेस्टेड",
      harvestableLabel: "हार्वेस्टेबल"
    },
    faucet: {
      testnetFaucet: "टेस्टनेट फॉसेट · मॉक USDT",
      mintDesc: "विकास के लिए टेस्ट USDT मिंट करें। वर्तमान बैलेंस:",
      mint10000: "10,000 USDT मिंट करें",
      mint: "मिंट",
      customPlaceholder: "कस्टम",
      mintingPending: "टेस्ट USDT मिंट हो रहा है…",
      mintingDesc: "आपके वॉलेट में {amount} USDT भेजा जा रहा है",
      mintedSuccess: "{amount} टेस्ट USDT मिंट किए",
      mintFailed: "मिंट विफल",
      invalidAmount: "अमान्य राशि"
    },
    common: {
      connectWalletTitle: "अपना वॉलेट कनेक्ट करें",
      connectWalletDesc: "अपना पोर्टफोलियो देखने, स्टेक प्रबंधित करने और आय ट्रैक करने के लिए अपना वॉलेट कनेक्ट करें।"
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
