import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  pt: {
    staking: {
      connectWalletTitle: "Conecte sua carteira para staking",
      closingInterval: "intervalo de encerramento",
      newStake: "Novo Stake",
      amount: "Valor (USDT)",
      amountPlaceholder: "Digite o valor...",
      balanceHelper: "Saldo: {balance} USDT | Mín: 10 USDT | Sem limite máximo",
      autoCompoundEvery: "Composição automática a cada {interval}",
      approveAndStake: "Aprovar & Stakar ${amount}",
      stakeBtn: "Stakar ${amount}",
      yourStakes: "Seus Stakes",
      active: "ativo",
      noActiveStakesDesc: "Sem stakes ativos. Crie seu primeiro stake para começar a ganhar!",
      stakeCount: "{count} stake{count, plural, =1 {} other {s}}",
      totalStaked: "Total Stakado",
      tierHeader: "Limite 3X",
      pendingCompoundProfit: "Lucro de composição pendente",
      autoCompoundBtn: "Composição automática ({count})",
      accruing: "Acumulando",
      harvestBtn: "Colher ${amount}",
      minHarvestStake: "Mín $10/stake",
      minHarvestAmount: "Mín $10",
      total: "total",
      tierCol: "Nível",
      stakedCol: "Stakado",
      earnedCol: "Ganho",
      harvestedCol: "Colhido",
      capCol: "Limite 3X",
      startedCol: "Iniciado",
      statusCol: "Status",
      actionCol: "Ação",
      statusActive: "Ativo",
      statusCapped: "Limitado",
      statusClosed: "Fechado",
      unstake: "Retirar",
      unstakeConfirm: "Retirar stake #{index}?\n\nVocê stakou ${original} USDT.\nVocê receberá ~${preview} em KAIRO\n(80% do principal, menos qualquer renda colhida pendente).\n\nEsta ação é irreversível. Continuar?",
      calcTitle: "Calculadora de Composição",
      calcSubtitle: "Projetar acúmulo potencial de lucro ao longo do tempo",
      calcStakeAmount: "Valor do Stake (USDT)",
      calcEnterAmount: "Digite o valor do stake...",
      calcDuration: "Duração: {count} {count, plural, =1 {mês} other {meses}}",
      calcProjectedProfit: "Lucro Projetado",
      calcTier: "Nível",
      calcFrequency: "Frequência",
      calcCompounds: "Composições",
      calcNote: "0,15% por composição · Nível e frequência detectados automaticamente pelo valor",
      levelUnlockTitle: "Desbloqueio de Nível de Dividendo de Equipe",
      levelUnlockDesc: "Desbloqueie mais níveis de dividendo de equipe adicionando referências diretas. Você tem atualmente {count} referências diretas e {unlocked} / 15 níveis desbloqueados.",
      directs: "diretos",
      intervals: "intervalos"
    },
    p2p: {
      subtitle: "Trading KAIRO peer-to-peer atômico",
      connectWalletTitle: "Conecte sua carteira para negociar",
      connectWalletDesc: "Acesse trading KAIRO peer-to-peer",
      dexPrice: "Preço DEX",
      vol: "vol",
      noActiveBuyOrders: "Sem ordens de compra ativas",
      noActiveSellOrders: "Sem ordens de venda ativas",
      fill: "Preencher",
      enterAmount: "Digite o valor...",
      usdtAmount: "Valor USDT",
      kairoAmount: "Valor KAIRO",
      max: "MÁX: {amount}",
      balanceLabel: "Saldo: {amount} {token}",
      dexReferencePrice: "Preço de Referência DEX",
      tradingFee: "Taxa de Trading",
      estimated: "{token} estimado",
      approveAndCreateBuy: "Aprovar & Criar Ordem de Compra",
      createBuyOrder: "Criar Ordem de Compra",
      approveAndCreateSell: "Aprovar & Criar Ordem de Venda",
      createSellOrder: "Criar Ordem de Venda",
      noActiveOrders: "Você não tem ordens ativas.",
      noActiveOrdersDesc: "Crie uma ordem de compra ou venda para começar.",
      myBuyOrders: "Minhas Ordens de Compra",
      mySellOrders: "Minhas Ordens de Venda",
      cancel: "Cancelar",
      remaining: "${amount} restante",
      filledOfTotal: "${filled} preenchido de ${total} total",
      kairoRemaining: "{amount} KAIRO restante"
    },
    swap: {
      title: "Swap",
      subtitle: "Swap unidirecional com taxa de {fee}% e queima deflacionária",
      connectWalletTitle: "Conecte sua carteira para swap",
      connectWalletDesc: "Swap unidirecional KAIRO para USDT com queima deflacionária",
      poolUsdt: "USDT do Pool",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap inclui queima deflacionária",
      youPay: "Você Paga",
      youReceive: "Você Recebe (estimado)",
      rate: "Taxa",
      fee: "Taxa ({percent}%)",
      minOutput: "Saída Mín. ({slippage}% slippage)",
      slippage: "Slippage:",
      priceImpact: "Impacto no Preço",
      approveAndSwap: "Aprovar & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "MÁX: {amount}"
    },
    referralNetwork: {
      title: "Rede de Referência",
      rank: "Rango",
      directReferrals: "Referências Diretas",
      directActive: "{count} ativas",
      directBusiness: "Volume Direto",
      referralStakes: "stakes de referência",
      teamBusiness: "Volume da Equipe",
      totalDownlineVolume: "volume total da downline",
      shareLink: "Compartilhe seu link para convidar novos membros e ganhar comissões multinível.",
      earnDirect: "Ganhe 5% comissão direta + dividendos de equipe de 15 níveis em cada stake de referência."
    },
    rankDividend: {
      title: "Dividendo de Rango",
      subtitle: "Alcance rangos através do volume da equipe e ganhe recompensas de salário periódicas",
      connectWalletTitle: "Conecte sua carteira",
      rankChangeDetected: "Mudança de Rango Detectada: {from} → {to}",
      rankChangeDesc: "Seu timer de salário será redefinido ao confirmar. Clique abaixo para atualizar seu rango.",
      updateRank: "Atualizar Rango",
      currentRank: "Rango Atual",
      rankLevel: "Nível {level} / 10",
      rankSalary: "Salário de Rango",
      perPeriod: "por período",
      harvestable: "Colhível",
      crystallized: "cristalizado",
      harvested: "Colhido",
      totalClaimed: "total reivindicado",
      rankProgress: "Progresso de Rango",
      earningPerPeriod: "Ganhando ${amount} / período",
      pending: "Pendente: ${amount} · clique Sincronizar para cristalizar",
      syncRankChange: "Sincronizar Mudança de Rango",
      syncRankSalary: "Sincronizar Salário de Rango (+${amount})",
      nothingToSync: "Nada para Sincronizar",
      harvestBtn: "Colher ${amount}",
      nothingToHarvest: "Nada para Colher",
      teamVolumeTitle: "Volume da Equipe",
      totalTeamVolume: "Volume Total da Equipe",
      next: "Próximo: {rank}",
      targetMet: "Meta atingida!",
      needMoreVolume: "Precisa de ${amount} mais volume qualificante",
      progressAchieved: "{percent}% atingido",
      directReferrals: "Referências Diretas",
      activeDirects: "Diretos Ativos",
      unlockedLevels: "Níveis Desbloqueados",
      harvestIncomeTitle: "Renda de Colheita",
      direct: "Direto",
      team: "Equipe",
      rank: "Rango",
      harvest: "Colheita",
      fiftyPctCapRule: "Regra de Limite de 50% por Perna",
      fiftyPctDesc: "Para cada meta de rango, no máximo 50% do limite daquele rango específico pode ser creditado de qualquer perna única. Seu volume pessoal não conta para qualificação de rango. Mesmo se uma perna única tiver volume massivo, apenas 50% da meta de rango será creditado.",
      totalTeamVolumeLabel: "Volume Total da Equipe",
      largestLeg: "Maior Perna",
      numberOfLegs: "Número de Pernas",
      qualifyingVolume: "Volume Qualificante",
      legVolumeBreakdown: "Detalhamento de Volume por Perna",
      leg: "Perna {index}",
      maxCredited: "(máx ${amount})",
      rankTargetsTitle: "Metas e Salários de Rango",
      rankCol: "Rango",
      teamVolumeTargetCol: "Meta de Volume da Equipe",
      salaryCol: "Salário / Período",
      progressCol: "Progresso",
      statusCol: "Status",
      achieved: "Alcançado",
      nextTarget: "Próxima Meta",
      locked: "Bloqueado",
      salaryHistoryTitle: "Histórico de Salário",
      records: "{count} registros",
      loadingHistory: "Carregando histórico...",
      noSalaryHistory: "Sem histórico de salário ainda. Alcance um rango para começar a ganhar!",
      typeCol: "Tipo",
      dateCol: "Data",
      amountCol: "Valor",
      txCol: "Tx",
      salaryCredited: "Salário Creditado",
      harvestedLabel: "Colhido"
    },
    teamDividend: {
      title: "Dividendo de Equipe",
      subtitle: "Ganhe de 15 níveis de lucros de composição da equipe com base no seu número de referências diretas. Usuários inativos na cadeia são pulados — apenas participantes ativos contam como níveis.",
      connectWalletTitle: "Conecte sua carteira",
      connectWalletDesc: "Veja seus ganhos de dividendo de equipe",
      unlockedLevels: "Níveis Desbloqueados",
      directReferrals: "Referências Diretas",
      moreForNext: "{count} mais para o próximo nível",
      maxLevelsUnlocked: "Níveis máximos desbloqueados",
      directBusiness: "Volume Direto",
      referralStakes: "Stakes de Referência",
      teamVolume: "Volume da Equipe",
      totalDownlineVolume: "Volume total da downline",
      teamDividend: "Dividendo de Equipe",
      harvest: "Colher",
      activeLabel: "ativo",
      levelBreakdownTitle: "Detalhamento de Nível — Detalhes Completos",
      levelBreakdownDesc: "Cada nível ganha uma porcentagem dos lucros de composição gerados por usuários ativos naquela profundidade comprimida. Usuários inativos são pulados — não contam como nível. L1: 10%, L2-L10: 5% cada, L11-L15: 2% cada. Desbloqueie níveis adicionando referências diretas: 1-5 diretos = 1-5 níveis, depois cada direto adicional = mais 2 níveis (máx 15 com 10 diretos).",
      levelCol: "Nível",
      rateCol: "Taxa",
      membersCol: "Membros",
      businessCol: "Volume",
      earnedCol: "Ganho",
      statusCol: "Status",
      statusActive: "Ativo",
      statusNext: "Próximo",
      statusLocked: "Bloqueado",
      total: "Total",
      levelLabel: "Nível {level}",
      directsNeeded: "{count} direto{count, plural, =1 {} other {s}}",
      levelActivationTracker: "Rastreador de Ativação de Nível",
      levelActivationDesc: "Você tem {directs} referências diretas, desbloqueando {unlocked} / 15 níveis de dividendo de equipe.",
      ppl: "pessoas",
      legs: "{count} pernas",
      legVolumeBreakdown: "Detalhamento de Volume por Perna",
      legVolumeDesc: "Cada referência direta forma uma \"perna\". O volume total a jusante delas contribui para seu volume de equipe e qualificação de rango.",
      refCol: "Referência",
      selfStakeCol: "Stake Próprio",
      legVolumeCol: "Volume da Perna",
      shareCol: "Participação",
      howItWorks: "Como Funcionam os Dividendos de Equipe",
      how1: "Quando qualquer usuário em sua equipe compõe seu stake, lucro é gerado (0,15% por intervalo).",
      how2: "Você ganha uma porcentagem daquele lucro baseado no nível: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Requer stake ativo e espaço de limite FIFO. Ganhos limitados a 3X do seu stake total."
    },
    cms: {
      subtitle: "Compre assinaturas CMS e ganhe recompensas KAIRO",
      connectWalletTitle: "Membro Principal",
      notAvailable: "CMS Indisponível",
      notAvailableDesc: "O contrato de Assinatura de Membro Principal ainda não foi implantado.",
      yourSubscriptions: "Suas Assinaturas",
      remainingSlots: "Vagas Restantes",
      subscriptionStatus: "Status da Assinatura",
      active: "Ativa",
      ended: "Encerrada",
      purchaseSubscription: "Comprar Assinatura",
      subscriptionEnded: "O período de assinatura terminou",
      numberOfSubscriptions: "Número de Assinaturas",
      enterAmount: "Digite o valor...",
      subscriptionDetails: "Detalhes da Assinatura",
      pricePerSub: "Preço por assinatura:",
      loyaltyRewardPerSub: "Recompensa de fidelidade por assinatura:",
      totalCost: "Custo total:",
      youllEarn: "Você ganhará:",
      approveUsdt: "Aprovar USDT",
      subscribeBtn: "Assinar ({cost} USDT)",
      completeRegistrationFirst: "Complete o registro primeiro",
      claimRewards: "Reivindicar Recompensas",
      alreadyClaimed: "Você já reivindicou suas recompensas",
      loyaltyRewards: "Recompensas de Fidelidade",
      leadershipRewards: "Recompensas de Liderança",
      totalClaimable: "Total Reivindicável",
      claimRules: "Regras de Reivindicação",
      claimRule1: "Reivindicação única (use ou perca)",
      claimRule2: "Requer stake ativo no StakingManager",
      claimRule3: "Limitado pelo valor do stake ativo (excesso é deletado)",
      claimRule4: "90% cunhado para você, 10% deflacionário (não cunhado)",
      excessWarning: "Aviso: {amount} KAIRO serão permanentemente deletados (excede limite do stake)",
      maxClaimable: "Máx. reivindicável (baseado no stake):",
      claimRewardsBtn: "Reivindicar Recompensas",
      leadershipRewardsTitle: "Recompensas de Liderança (5 Níveis)",
      levelCol: "Nível",
      requiredDirectsCol: "Diretos Necessários",
      rewardPerSubCol: "Recompensa/Assinatura",
      subscriptionsCol: "Assinaturas",
      earnedCol: "Ganho (KAIRO)",
      levelLabel: "Nível {level}",
      howCmsWorks: "Como o CMS Funciona",
      subscriptionBenefits: "Benefícios da Assinatura",
      benefit1: "10 USDT por assinatura (máx 10.000 no total)",
      benefit2: "Ganhe 5 KAIRO de recompensa de fidelidade por assinatura",
      benefit3: "Ganhe recompensas de liderança de 5 níveis de referência",
      benefit4: "Reivindique uma vez com stake ativo (use ou perca)",
      referralRewards: "Recompensas de Referência",
      level1Desc: "1 KAIRO por assinatura (0 diretos necessários)",
      level2Desc: "0.5 KAIRO por assinatura (2 diretos necessários)",
      level3Desc: "0.5 KAIRO por assinatura (3 diretos necessários)",
      level4Desc: "0.25 KAIRO por assinatura (4 diretos necessários)",
      level5Desc: "0.25 KAIRO por assinatura (5 diretos necessários)",
      level1: "Nível 1:",
      level2: "Nível 2:",
      level3: "Nível 3:",
      level4: "Nível 4:",
      level5: "Nível 5:"
    },
    analytics: {
      title: "Análise do Protocolo",
      subtitle: "Estatísticas do ecossistema KAIRO em tempo real",
      kairoPrice: "Preço KAIRO",
      marketCap: "Valor de Mercado",
      poolLiquidityUsdt: "Liquidez do Pool (USDT)",
      totalBurned: "Total Queimado",
      tokenSupply: "Oferta de Token",
      deflationaryNote: "Mecanismos deflacionários via queima",
      circulating: "Em circulação",
      burned: "Queimado",
      effectiveSupply: "Oferta Efetiva",
      socialLock: "Social Lock",
      burnRate: "Taxa de Queima",
      liquidityPool: "Pool de Liquidez",
      dexPoolComposition: "Composição do pool DEX",
      kairoInPool: "KAIRO no Pool",
      usdtInPool: "USDT no Pool",
      pricePerSupply: "Preço (USDT / Oferta Total)"
    },
    portfolio: {
      totalPortfolioValue: "Valor Total do Portfólio",
      activeStakes: "Stakes Ativos",
      totalStaked: "Total Stakado",
      totalEarned: "Total Ganho",
      remainingCapping: "Limite Restante",
      kairoPrice: "Preço KAIRO",
      poolLiquidity: "Liquidez do Pool",
      totalCirculation: "Circulação Total",
      harvestableAffiliate: "Colhível (Afiliado)",
      activeDirects: "Diretos Ativos"
    },
    activeStakesTable: {
      title: "Stakes Ativos",
      loading: "Carregando stakes...",
      empty: "Sem stakes ativos. Comece a stakar para ganhar recompensas!",
      tierCount: "{count} nível(s)",
      stakeCount: "{count} stake{count, plural, =1 {} other {s}}",
      stakedAmount: "Valor Stakado",
      capProgress: "Progresso do Limite 3X",
      harvestable: "Colhível",
      harvested: "Colhido",
      totalEarned: "Total Ganho",
      pendingCompoundProfit: "Lucro de composição pendente",
      autoCompound: "Composição Automática",
      autoCompoundBtn: "Composição Automática ({count})",
      accruing: "Acumulando",
      harvest: "Colher ${amount}",
      minHarvestStake: "Mín $10/stake",
      minHarvestAmount: "Mín $10",
      intervals: "intervalos"
    },
    income: {
      title: "Resumo de Renda",
      typesCount: "{count} tipos",
      direct: "Comissão Direta",
      team: "Dividendos de Equipe",
      rank: "Salário de Rango",
      harvest: "Colheita",
      pendingHarvest: "Colheita Pendente",
      affiliateHarvested: "Afiliado Colhido",
      directLabel: "Direto",
      teamLabel: "Equipe",
      rankLabel: "Rango",
      stakingEarnings: "Rendimentos de Staking",
      harvestedLabel: "Colhido",
      harvestableLabel: "Colhível"
    },
    faucet: {
      testnetFaucet: "Torneira Testnet · USDT Simulado",
      mintDesc: "Crie USDT de teste para desenvolvimento. Saldo atual:",
      mint10000: "Criar 10.000 USDT",
      mint: "Criar",
      customPlaceholder: "personalizado",
      mintingPending: "Criando USDT de teste…",
      mintingDesc: "Enviando {amount} USDT para sua carteira",
      mintedSuccess: "Criado {amount} USDT de teste",
      mintFailed: "Falha na criação",
      invalidAmount: "Valor inválido"
    },
    common: {
      connectWalletTitle: "Conecte Sua Carteira",
      connectWalletDesc: "Conecte sua carteira para ver seu portfólio, gerenciar stakes e acompanhar rendimentos."
    }
  },

  sw: {
    staking: {
      connectWalletTitle: "Unganisha mkoba wako kwa staking",
      closingInterval: "kipindi cha kufunga",
      newStake: "Stake Mpya",
      amount: "Kiasi (USDT)",
      amountPlaceholder: "Ingiza kiasi...",
      balanceHelper: "Salio: {balance} USDT | Chini: 10 USDT | Hakuna Kikomo cha Juu",
      autoCompoundEvery: "Auto-compound kila {interval}",
      approveAndStake: "Idhinisha & Stake ${amount}",
      stakeBtn: "Stake ${amount}",
      yourStakes: "Stakes Zako",
      active: "hai",
      noActiveStakesDesc: "Hakuna stakes zinazofanya kazi. Unda stake yako ya kwanza kuanza kupata!",
      stakeCount: "{count} stake",
      totalStaked: "Jumla Iliyostakishwa",
      tierHeader: "Kikomo cha 3X",
      pendingCompoundProfit: "Faida ya compound inayosubiri",
      autoCompoundBtn: "Auto-compound ({count})",
      accruing: "Inakusanyika",
      harvestBtn: "Vuna ${amount}",
      minHarvestStake: "Chini $10/stake",
      minHarvestAmount: "Chini $10",
      total: "jumla",
      tierCol: "Daraja",
      stakedCol: "Imestakishwa",
      earnedCol: "Imepatwa",
      harvestedCol: "Imevunwa",
      capCol: "Kikomo cha 3X",
      startedCol: "Imeanzishwa",
      statusCol: "Hali",
      actionCol: "Kitendo",
      statusActive: "Hai",
      statusCapped: "Imefikia kikomo",
      statusClosed: "Imefungwa",
      unstake: "Ondoa stake",
      unstakeConfirm: "Ondoa stake #{index}?\n\nUlistakisha ${original} USDT.\nUtapokea ~${preview} katika KAIRO\n(80% ya kiasi kuu, ukiondoa mapato yoyote yaliyovunwa yanayosubiri).\n\nKitendo hiki hakiwezi kurudishwa. Endelea?",
      calcTitle: "Kikokotoo cha Compound",
      calcSubtitle: "Tega makusanyiko ya faida inayowezekana kwa muda",
      calcStakeAmount: "Kiasi cha Stake (USDT)",
      calcEnterAmount: "Ingiza kiasi cha stake...",
      calcDuration: "Muda: miezi {count}",
      calcProjectedProfit: "Faida Iliyotegwa",
      calcTier: "Daraja",
      calcFrequency: "Marudio",
      calcCompounds: "Compounds",
      calcNote: "0.15% kwa compound · Daraja na marudio hugunduliwa moja kwa moja kutoka kiasi",
      levelUnlockTitle: "Fungua Daraja la Divideni ya Timu",
      levelUnlockDesc: "Fungua daraja zaidi za divideni ya timu kwa kuongeza rufaa za moja kwa moja. Kwa sasa una rufaa {count} za moja kwa moja na {unlocked} / 15 daraja zilizofunguliwa.",
      directs: "za moja kwa moja",
      intervals: "vipindi"
    },
    p2p: {
      subtitle: "Biashari ya KAIRO kati ya watu binafsi kwa njia ya atomiki",
      connectWalletTitle: "Unganisha mkoba wako kwa biashara",
      connectWalletDesc: "Pata ufikiaji wa biashari ya KAIRO kati ya watu binafsi",
      dexPrice: "Bei ya DEX",
      vol: "vol",
      noActiveBuyOrders: "Hakuna maagizo ya kununua yanayofanya kazi",
      noActiveSellOrders: "Hakuna maagizo ya kuuza yanayofanya kazi",
      fill: "Jaza",
      enterAmount: "Ingiza kiasi...",
      usdtAmount: "Kiasi cha USDT",
      kairoAmount: "Kiasi cha KAIRO",
      max: "KIWANGO: {amount}",
      balanceLabel: "Salio: {amount} {token}",
      dexReferencePrice: "Bei ya Kumbukumbu ya DEX",
      tradingFee: "Ada ya Biashara",
      estimated: "{token} iliyokadirwa",
      approveAndCreateBuy: "Idhinisha & Unda Agizo la Kununua",
      createBuyOrder: "Unda Agizo la Kununua",
      approveAndCreateSell: "Idhinisha & Unda Agizo la Kuuza",
      createSellOrder: "Unda Agizo la Kuuza",
      noActiveOrders: "Huna maagizo yanayofanya kazi.",
      noActiveOrdersDesc: "Unda agizo la kununua au kuuza kuanza.",
      myBuyOrders: "Maagizo Yangu ya Kununua",
      mySellOrders: "Maagizo Yangu ya Kuuza",
      cancel: "Ghairi",
      remaining: "${amount} iliyobaki",
      filledOfTotal: "${filled} imejazwa kati ya ${total} jumla",
      kairoRemaining: "{amount} KAIRO imebakia"
    },
    swap: {
      title: "Swap",
      subtitle: "Swap ya upande mmoja na ada ya {fee}% na kuchoma kunakata",
      connectWalletTitle: "Unganisha mkoba wako kwa swap",
      connectWalletDesc: "Swap ya KAIRO kwenda USDT upande mmoja na kuchoma kunakata",
      poolUsdt: "USDT kwenye Pool",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap inajumuisha kuchoma kunakata",
      youPay: "Unalipa",
      youReceive: "Unapokea (imekadirwa)",
      rate: "Kiwango",
      fee: "Ada ({percent}%)",
      minOutput: "Toleo la Chini ({slippage}% slippage)",
      slippage: "Slippage:",
      priceImpact: "Athari ya Bei",
      approveAndSwap: "Idhinisha & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "KIWANGO: {amount}"
    },
    referralNetwork: {
      title: "Mtandao wa Rufaa",
      rank: "Daraja",
      directReferrals: "Rufaa za Moja kwa Moja",
      directActive: "{count} hai",
      directBusiness: "Biashara ya Moja kwa Moja",
      referralStakes: "stakes za rufaa",
      teamBusiness: "Biashara ya Timu",
      totalDownlineVolume: "jumla ya kiasi cha downline",
      shareLink: "Shiriki kiungo chako kualiko wanachama wapya na kupata komesheni za ngazi nyingi.",
      earnDirect: "Pata komesheni ya moja kwa moja ya 5% + divideni za timu za ngazi 15 kwenye kila stake ya rufaa."
    },
    rankDividend: {
      title: "Divideni ya Daraja",
      subtitle: "Fikia daraja kupitia kiasi cha timu na pata tuzo za mishahara za mara kwa mara",
      connectWalletTitle: "Unganisha Mkoba",
      rankChangeDetected: "Mabadiliko ya Daraja Yamegunduliwa: {from} → {to}",
      rankChangeDesc: "Mtoa wa muda wa mshahara wako utawekwa upya unapothibitisha. Bonyeza hapa chini kusasisha daraja lako.",
      updateRank: "Sasisha Daraja",
      currentRank: "Daraja la Sasa",
      rankLevel: "Ngazi {level} / 10",
      rankSalary: "Mshahara wa Daraja",
      perPeriod: "kwa kipindi",
      harvestable: "Inayoweza Kuvunwa",
      crystallized: "imekithaa",
      harvested: "Imevunwa",
      totalClaimed: "jumla iliyodaiwa",
      rankProgress: "Maendeleo ya Daraja",
      earningPerPeriod: "Inapata ${amount} / kipindi",
      pending: "Inasubiri: ${amount} · bonyeza Sink kwa kukithaa",
      syncRankChange: "Sink Mabadiliko ya Daraja",
      syncRankSalary: "Sink Mshahara wa Daraja (+${amount})",
      nothingToSync: "Hakuna cha Kusink",
      harvestBtn: "Vuna ${amount}",
      nothingToHarvest: "Hakuna cha Kuvuna",
      teamVolumeTitle: "Kiasi cha Timu",
      totalTeamVolume: "Jumla ya Kiasi cha Timu",
      next: "Inayofuata: {rank}",
      targetMet: "Lengo limefikiwa!",
      needMoreVolume: "Unahitaji ${amount} zaidi kiasi kinachostahili",
      progressAchieved: "{percent}% imefikiwa",
      directReferrals: "Rufaa za Moja kwa Moja",
      activeDirects: "Za Moja kwa Moja Hai",
      unlockedLevels: "Ngazi Zilizofunguliwa",
      harvestIncomeTitle: "Mapato ya Uvuno",
      direct: "Moja kwa Moja",
      team: "Timu",
      rank: "Daraja",
      harvest: "Uvuno",
      fiftyPctCapRule: "Kanuni ya Kikomo cha 50% kwa Mguu",
      fiftyPctDesc: "Kwa kila lengo la daraja, kiwango cha juu cha 50% cha kilele cha daraja husika kinaweza kuhesabika kutoka mguu mmoja. Kiasi chako cha kibinafsi hakihesabiki kwa sifa ya daraja. Hata kama mguu mmoja una kiasi kikubwa, ni 50% tu ya lengo la daraja kitaahesabika.",
      totalTeamVolumeLabel: "Jumla ya Kiasi cha Timu",
      largestLeg: "Mguu Mkubwa Zaidi",
      numberOfLegs: "Idadi ya Miguu",
      qualifyingVolume: "Kiasi Kinachostahili",
      legVolumeBreakdown: "Uchambuzi wa Kiasi kwa Mguu",
      leg: "Mguu {index}",
      maxCredited: "(kiwango ${amount})",
      rankTargetsTitle: "Malengo na Mishahara ya Daraja",
      rankCol: "Daraja",
      teamVolumeTargetCol: "Lengo la Kiasi cha Timu",
      salaryCol: "Mshahara / Kipindi",
      progressCol: "Maendeleo",
      statusCol: "Hali",
      achieved: "Imefikiwa",
      nextTarget: "Lengo Linalofuata",
      locked: "Imefungwa",
      salaryHistoryTitle: "Historia ya Mshahara",
      records: "rekodi {count}",
      loadingHistory: "Inapakia historia...",
      noSalaryHistory: "Hakuna historia ya mshahara bado. Fikia daraja kuanza kupata!",
      typeCol: "Aina",
      dateCol: "Tarehe",
      amountCol: "Kiasi",
      txCol: "Tx",
      salaryCredited: "Mshahara Umehesabiwa",
      harvestedLabel: "Imevunwa"
    },
    teamDividend: {
      title: "Divideni ya Timu",
      subtitle: "Pata kutoka ngazi 15 za faida za compound za timu kulingana na idadi yako ya rufaa za moja kwa moja. Watumiaji wasio hai katika mnyororo warukwa — wadau hai tu huhesabika kama ngazi.",
      connectWalletTitle: "Unganisha Mkoba",
      connectWalletDesc: "Angalia mapato yako ya divideni ya timu",
      unlockedLevels: "Ngazi Zilizofunguliwa",
      directReferrals: "Rufaa za Moja kwa Moja",
      moreForNext: "{count} zaidi kwa ngazi inayofuata",
      maxLevelsUnlocked: "Ngazi za juu zaidi zimefunguliwa",
      directBusiness: "Biashara ya Moja kwa Moja",
      referralStakes: "Stakes za Rufaa",
      teamVolume: "Kiasi cha Timu",
      totalDownlineVolume: "Jumla ya kiasi cha downline",
      teamDividend: "Divideni ya Timu",
      harvest: "Vuna",
      activeLabel: "hai",
      levelBreakdownTitle: "Uchambuzi wa Ngazi — Maelezo Kamili",
      levelBreakdownDesc: "Kila ngazi inapata asilimia ya faida za compound zilizozalishwa na watumiaji hai kwenye kina kilichobanwa. Watumiaji wasio hai warukwa — hawahesabiki kama ngazi. L1: 10%, L2-L10: 5% kila moja, L11-L15: 2% kila moja. Fungua ngazi kwa kuongeza rufaa za moja kwa moja: 1-5 za moja kwa moja = ngazi 1-5, kisha kila ya moja kwa moja ya ziada = ngazi 2 zaidi (kiwango cha juu 15 kwa 10 za moja kwa moja).",
      levelCol: "Ngazi",
      rateCol: "Kiwango",
      membersCol: "Wanachama",
      businessCol: "Biashara",
      earnedCol: "Imepatwa",
      statusCol: "Hali",
      statusActive: "Hai",
      statusNext: "Inayofuata",
      statusLocked: "Imefungwa",
      total: "Jumla",
      levelLabel: "Ngazi {level}",
      directsNeeded: "{count} za moja kwa moja",
      levelActivationTracker: "Kifuatiliaji cha Uanzishwaji wa Ngazi",
      levelActivationDesc: "Una rufaa {directs} za moja kwa moja, kufungua {unlocked} / 15 ngazi za divideni ya timu.",
      ppl: "watu",
      legs: "miguu {count}",
      legVolumeBreakdown: "Uchambuzi wa Kiasi kwa Mguu",
      legVolumeDesc: "Kila rufaa ya moja kwa moja inaunda \"mguu\". Kiasi chao cha jumla cha chini ya mto huchangia kwenye kiasi cha timu na sifa ya daraja lako.",
      refCol: "Rufaa",
      selfStakeCol: "Stake yako",
      legVolumeCol: "Kiasi cha Mguu",
      shareCol: "Sehemu",
      howItWorks: "Jinsi Divideni ya Timu Inavyofanya Kazi",
      how1: "Mtumiaji yeyote katika timu yako anapocompound stake yao, faida inazalishwa (0.15% kwa kipindi).",
      how2: "Unapata asilimia ya hiyo faida kulingana na ngazi: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Inahitaji stake hai na nafasi ya kikomo cha FIFO. Mapato yamepimizwa kwa 3X ya jumla ya stake yako."
    },
    cms: {
      subtitle: "Nunua usajili wa CMS na pata tuzo za KAIRO",
      connectWalletTitle: "Uanachama wa Msingi",
      notAvailable: "CMS Haipatikani",
      notAvailableDesc: "Mkataba wa Usajili wa Uanachama wa Msingi bado haujapelekwa.",
      yourSubscriptions: "Usajili Wako",
      remainingSlots: "Nafasi Zilizobaki",
      subscriptionStatus: "Hali ya Usajili",
      active: "Hai",
      ended: "Imeisha",
      purchaseSubscription: "Nunua Usajili",
      subscriptionEnded: "Kipindi cha usajili kimeisha",
      numberOfSubscriptions: "Idadi ya Usajili",
      enterAmount: "Ingiza kiasi...",
      subscriptionDetails: "Maelezo ya Usajili",
      pricePerSub: "Bei kwa kila usajili:",
      loyaltyRewardPerSub: "Tuzo ya uaminifu kwa kila usajili:",
      totalCost: "Gharama ya jumla:",
      youllEarn: "Utapata:",
      approveUsdt: "Idhinisha USDT",
      subscribeBtn: "Jisajili ({cost} USDT)",
      completeRegistrationFirst: "Tafadhali kamaliza usajili kwanza",
      claimRewards: "Dai Tuzo",
      alreadyClaimed: "Umeshadai tuzo zako",
      loyaltyRewards: "Tuzo za Uaminifu",
      leadershipRewards: "Tuzo za Uongozi",
      totalClaimable: "Jumla Inayoweza Kudaiwa",
      claimRules: "Kanuni za Kudai",
      claimRule1: "Kudai mara moja tu (itumie au ipoteze)",
      claimRule2: "Inahitaji stake hai kwenye StakingManager",
      claimRule3: "Imepunguzwa na thamani ya stake hai (ziada inafutwa)",
      claimRule4: "90% imeundwa kwako, 10% kunakata (haijaundwa)",
      excessWarning: "Onyo: {amount} KAIRO itafutwa kabisa (inazidi kikomo cha stake)",
      maxClaimable: "Kiango cha juu cha kudai (kulingana na stake):",
      claimRewardsBtn: "Dai Tuzo",
      leadershipRewardsTitle: "Tuzo za Uongozi (Ngazi 5)",
      levelCol: "Ngazi",
      requiredDirectsCol: "Za Moja kwa Moja Zinahitajika",
      rewardPerSubCol: "Tuzo/Usajili",
      subscriptionsCol: "Usajili",
      earnedCol: "Imepatwa (KAIRO)",
      levelLabel: "Ngazi {level}",
      howCmsWorks: "Jinsi CMS Inavyofanya Kazi",
      subscriptionBenefits: "Faida za Usajili",
      benefit1: "USDT 10 kwa kila usajili (kiwango cha juu 10,000 jumla)",
      benefit2: "Pata KAIRO 5 tuzo ya uaminifu kwa kila usajili",
      benefit3: "Pata tuzo za uongozi kutoka ngazi 5 za rufaa",
      benefit4: "Dai mara moja na stake hai (itumie au ipoteze)",
      referralRewards: "Tuzo za Rufaa",
      level1Desc: "KAIRO 1 kwa kila usajili (0 za moja kwa moja zinahitajika)",
      level2Desc: "KAIRO 0.5 kwa kila usajili (2 za moja kwa moja zinahitajika)",
      level3Desc: "KAIRO 0.5 kwa kila usajili (3 za moja kwa moja zinahitajika)",
      level4Desc: "KAIRO 0.25 kwa kila usajili (4 za moja kwa moja zinahitajika)",
      level5Desc: "KAIRO 0.25 kwa kila usajili (5 za moja kwa moja zinahitajika)",
      level1: "Ngazi 1:",
      level2: "Ngazi 2:",
      level3: "Ngazi 3:",
      level4: "Ngazi 4:",
      level5: "Ngazi 5:"
    },
    analytics: {
      title: "Uchanganuzi wa Itifaki",
      subtitle: "Takwimu za mfumo wa KAIRO kwa wakati halisi",
      kairoPrice: "Bei ya KAIRO",
      marketCap: "Thamani ya Soko",
      poolLiquidityUsdt: "Liquidity ya Pool (USDT)",
      totalBurned: "Jumla Iliyochomwa",
      tokenSupply: "Usambazaji wa Token",
      deflationaryNote: "Mekaniki za kunakata kupitia kuchoma",
      circulating: "Kwenye mzunguko",
      burned: "Imechomwa",
      effectiveSupply: "Usambazaji Mfanisi",
      socialLock: "Social Lock",
      burnRate: "Kiwango cha Uchomaji",
      liquidityPool: "Pool ya Liquidity",
      dexPoolComposition: "Muundo wa pool ya DEX",
      kairoInPool: "KAIRO kwenye Pool",
      usdtInPool: "USDT kwenye Pool",
      pricePerSupply: "Bei (USDT / Jumla ya Usambazaji)"
    },
    portfolio: {
      totalPortfolioValue: "Jumla ya Thamani ya Portifolio",
      activeStakes: "Stakes Hai",
      totalStaked: "Jumla Iliyostakishwa",
      totalEarned: "Jumla Ilivyopatwa",
      remainingCapping: "Kikomo Kilichobaki",
      kairoPrice: "Bei ya KAIRO",
      poolLiquidity: "Liquidity ya Pool",
      totalCirculation: "Mzunguko wa Jumla",
      harvestableAffiliate: "Inayoweza Kuvunwa (Afiliyeti)",
      activeDirects: "Za Moja kwa Moja Hai"
    },
    activeStakesTable: {
      title: "Stakes Hai",
      loading: "Inapakia stakes...",
      empty: "Hakuna stakes hai. Anza kustakishwa kupata tuzo!",
      tierCount: "daraja {count}",
      stakeCount: "stake {count}",
      stakedAmount: "Kiasi Kilichostakishwa",
      capProgress: "Maendeleo ya Kikomo cha 3X",
      harvestable: "Inayoweza Kuvunwa",
      harvested: "Imevunwa",
      totalEarned: "Jumla Ilivyopatwa",
      pendingCompoundProfit: "Faida ya compound inayosubiri",
      autoCompound: "Compound Otomatiki",
      autoCompoundBtn: "Compound Otomatiki ({count})",
      accruing: "Inakusanyika",
      harvest: "Vuna ${amount}",
      minHarvestStake: "Chini $10/stake",
      minHarvestAmount: "Chini $10",
      intervals: "vipindi"
    },
    income: {
      title: "Muhtasari wa Mapato",
      typesCount: "aina {count}",
      direct: "Komesheni ya Moja kwa Moja",
      team: "Divideni za Timu",
      rank: "Mshahara wa Daraja",
      harvest: "Uvuno",
      pendingHarvest: "Uvuno Unasubiri",
      affiliateHarvested: "Afiliyeti Imevunwa",
      directLabel: "Moja kwa Moja",
      teamLabel: "Timu",
      rankLabel: "Daraja",
      stakingEarnings: "Mapato ya Staking",
      harvestedLabel: "Imevunwa",
      harvestableLabel: "Inayoweza Kuvunwa"
    },
    faucet: {
      testnetFaucet: "Mwoko wa Testnet · USDT ya Jaribio",
      mintDesc: "Tengeneza USDT ya majaribio kwa maendeleo. Salio la sasa:",
      mint10000: "Tengeneza USDT 10,000",
      mint: "Tengeneza",
      customPlaceholder: "maalum",
      mintingPending: "Inatengeneza USDT ya majaribio…",
      mintingDesc: "Inatuma {amount} USDT kwenye mkoba wako",
      mintedSuccess: "Imetengeneza {amount} USDT ya majaribio",
      mintFailed: "Utengenezaji umeshindwa",
      invalidAmount: "Kiasi batili"
    },
    common: {
      connectWalletTitle: "Unganisha Mkoba Wako",
      connectWalletDesc: "Unganisha mkoba wako kuona portifolio yako, kudhibiti stakes, na kufuatilia mapato."
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
