import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  id: {
    staking: {
      connectWalletTitle: "Hubungkan dompet untuk stake",
      closingInterval: "interval penutupan",
      newStake: "Stake Baru",
      amount: "Jumlah (USDT)",
      amountPlaceholder: "Masukkan jumlah...",
      balanceHelper: "Saldo: {balance} USDT | Min: 10 USDT | Tanpa Batas Maks",
      autoCompoundEvery: "Auto-compound setiap {interval}",
      approveAndStake: "Setujui & Stake ${amount}",
      stakeBtn: "Stake ${amount}",
      yourStakes: "Stake Anda",
      active: "aktif",
      noActiveStakesDesc: "Belum ada stake aktif. Buat stake pertama Anda untuk mulai mendapatkan!",
      stakeCount: "{count} stake",
      totalStaked: "Total Staked",
      tierHeader: "Batas 3X",
      pendingCompoundProfit: "Keuntungan compound tertunda",
      autoCompoundBtn: "Auto-compound ({count})",
      accruing: "Bertambah",
      harvestBtn: "Panen ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      total: "total",
      tierCol: "Tingkat",
      stakedCol: "Staked",
      earnedCol: "Diperoleh",
      harvestedCol: "Dipanen",
      capCol: "Batas 3X",
      startedCol: "Dimulai",
      statusCol: "Status",
      actionCol: "Aksi",
      statusActive: "Aktif",
      statusCapped: "Batas Tercapai",
      statusClosed: "Ditutup",
      unstake: "Unstake",
      unstakeConfirm: "Unstake #{index}?\n\nAnda telah staked ${original} USDT.\nAnda akan menerima ~${preview} dalam KAIRO\n(80% dari pokok, dikurangi pendapatan panen tertunda).\n\nTindakan ini tidak dapat dibatalkan. Lanjutkan?",
      calcTitle: "Kalkulator Compound",
      calcSubtitle: "Proyeksikan akumulasi keuntungan potensial dari waktu ke waktu",
      calcStakeAmount: "Jumlah Stake (USDT)",
      calcEnterAmount: "Masukkan jumlah stake...",
      calcDuration: "Durasi: {count} bulan",
      calcProjectedProfit: "Keuntungan Diproyeksikan",
      calcTier: "Tingkat",
      calcFrequency: "Frekuensi",
      calcCompounds: "Compound",
      calcNote: "0.15% per compound · Tingkat & frekuensi otomatis dari jumlah",
      levelUnlockTitle: "Buka Kunci Tingkat Dividen Tim",
      levelUnlockDesc: "Buka lebih banyak tingkat dividen tim dengan menambah referral langsung. Anda saat ini memiliki {count} referral langsung dan {unlocked} / 15 tingkat terbuka.",
      directs: "langsung",
      intervals: "interval"
    },
    p2p: {
      subtitle: "Perdagangan KAIRO peer-to-peer atomik",
      connectWalletTitle: "Hubungkan dompet untuk berdagang",
      connectWalletDesc: "Akses perdagangan KAIRO peer-to-peer",
      dexPrice: "Harga DEX",
      vol: "vol",
      noActiveBuyOrders: "Tidak ada order beli aktif",
      noActiveSellOrders: "Tidak ada order jual aktif",
      fill: "Isi",
      enterAmount: "Masukkan jumlah...",
      usdtAmount: "Jumlah USDT",
      kairoAmount: "Jumlah KAIRO",
      max: "MAKS: {amount}",
      balanceLabel: "Saldo: {amount} {token}",
      dexReferencePrice: "Harga Referensi DEX",
      tradingFee: "Biaya Perdagangan",
      estimated: "Estimasi {token}",
      approveAndCreateBuy: "Setujui & Buat Order Beli",
      createBuyOrder: "Buat Order Beli",
      approveAndCreateSell: "Setujui & Buat Order Jual",
      createSellOrder: "Buat Order Jual",
      noActiveOrders: "Anda tidak punya order aktif.",
      noActiveOrdersDesc: "Buat order beli atau jual untuk memulai.",
      myBuyOrders: "Order Beli Saya",
      mySellOrders: "Order Jual Saya",
      cancel: "Batal",
      remaining: "${amount} tersisa",
      filledOfTotal: "${filled} terisi dari ${total} total",
      kairoRemaining: "{amount} KAIRO tersisa"
    },
    swap: {
      title: "Swap",
      subtitle: "Swap satu arah dengan biaya {fee}% dan pembakaran deflasi",
      connectWalletTitle: "Hubungkan dompet untuk swap",
      connectWalletDesc: "Swap KAIRO ke USDT satu arah dengan pembakaran deflasi",
      poolUsdt: "USDT Pool",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap termasuk pembakaran deflasi",
      youPay: "Anda Bayar",
      youReceive: "Anda Terima (estimasi)",
      rate: "Kurs",
      fee: "Biaya ({percent}%)",
      minOutput: "Output Min ({slippage}% slippage)",
      slippage: "Slippage:",
      priceImpact: "Dampak Harga",
      approveAndSwap: "Setujui & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "MAKS: {amount}"
    },
    referralNetwork: {
      title: "Jaringan Referral",
      rank: "Pangkat",
      directReferrals: "Referral Langsung",
      directActive: "{count} aktif",
      directBusiness: "Bisnis Langsung",
      referralStakes: "stake referral",
      teamBusiness: "Bisnis Tim",
      totalDownlineVolume: "total volum downline",
      shareLink: "Bagikan tautan Anda untuk mengundang anggota baru dan mendapatkan komisi berbagai tingkat.",
      earnDirect: "Dapatkan 5% komisi langsung + dividen tim 15 tingkat pada setiap stake referral."
    },
    rankDividend: {
      title: "Dividen Pangkat",
      subtitle: "Capai pangkat melalui volum tim dan dapatkan imbalan gaji berkala",
      connectWalletTitle: "Hubungkan Dompet",
      rankChangeDetected: "Perubahan Pangkat Terdeteksi: {from} → {to}",
      rankChangeDesc: "Timer gaji Anda akan direset saat Anda konfirmasi. Klik di bawah untuk memperbarui pangkat Anda.",
      updateRank: "Perbarui Pangkat",
      currentRank: "Pangkat Saat Ini",
      rankLevel: "Tingkat {level} / 10",
      rankSalary: "Gaji Pangkat",
      perPeriod: "per periode",
      harvestable: "Dapat Dipanen",
      crystallized: "mengkristal",
      harvested: "Dipanen",
      totalClaimed: "total diklaim",
      rankProgress: "Kemajuan Pangkat",
      earningPerPeriod: "Mendapatkan ${amount} / periode",
      pending: "Tertunda: ${amount} · klik Sync untuk mengkristal",
      syncRankChange: "Sync Perubahan Pangkat",
      syncRankSalary: "Sync Gaji Pangkat (+${amount})",
      nothingToSync: "Tidak ada untuk Sync",
      harvestBtn: "Panen ${amount}",
      nothingToHarvest: "Tidak ada untuk Dipanen",
      teamVolumeTitle: "Volum Tim",
      totalTeamVolume: "Total Volum Tim",
      next: "Berikutnya: {rank}",
      targetMet: "Target tercapai!",
      needMoreVolume: "Butuh ${amount} lagi volum kualifikasi",
      progressAchieved: "{percent}% tercapai",
      directReferrals: "Referral Langsung",
      activeDirects: "Langsung Aktif",
      unlockedLevels: "Tingkat Terbuka",
      harvestIncomeTitle: "Pendapatan Panen",
      direct: "Langsung",
      team: "Tim",
      rank: "Pangkat",
      harvest: "Panen",
      fiftyPctCapRule: "Aturan Batas 50% per Kaki",
      fiftyPctDesc: "Untuk setiap target pangkat, maksimum 50% dari ambang batas pangkat tersebut dapat dikreditkan dari satu kaki. Volum pribadi Anda tidak dihitung untuk kualifikasi pangkat. Bahkan jika satu kaki memiliki volum besar, hanya 50% target pangkat yang akan dikreditkan.",
      totalTeamVolumeLabel: "Total Volum Tim",
      largestLeg: "Kaki Terbesar",
      numberOfLegs: "Jumlah Kaki",
      qualifyingVolume: "Volum Kualifikasi",
      legVolumeBreakdown: "Rincian Volum Kaki",
      leg: "Kaki {index}",
      maxCredited: "(maks ${amount})",
      rankTargetsTitle: "Target & Gaji Pangkat",
      rankCol: "Pangkat",
      teamVolumeTargetCol: "Target Volum Tim",
      salaryCol: "Gaji / Periode",
      progressCol: "Kemajuan",
      statusCol: "Status",
      achieved: "Tercapai",
      nextTarget: "Target Berikutnya",
      locked: "Terkunci",
      salaryHistoryTitle: "Riwayat Gaji",
      records: "{count} catatan",
      loadingHistory: "Memuat riwayat...",
      noSalaryHistory: "Belum ada riwayat gaji. Capai pangkat untuk mulai mendapatkan!",
      typeCol: "Tipe",
      dateCol: "Tanggal",
      amountCol: "Jumlah",
      txCol: "Tx",
      salaryCredited: "Gaji Dikreditkan",
      harvestedLabel: "Dipanen"
    },
    teamDividend: {
      title: "Dividen Tim",
      subtitle: "Dapatkan dari 15 tingkat keuntungan compound tim berdasarkan jumlah referral langsung Anda. Pengguna tidak aktif dalam rantai dilewati — hanya pemangku stake aktif yang dihitung sebagai tingkat.",
      connectWalletTitle: "Hubungkan Dompet",
      connectWalletDesc: "Lihat pendapatan dividen tim Anda",
      unlockedLevels: "Tingkat Terbuka",
      directReferrals: "Referral Langsung",
      moreForNext: "{count} lagi untuk tingkat berikutnya",
      maxLevelsUnlocked: "Tingkat maksimum terbuka",
      directBusiness: "Bisnis Langsung",
      referralStakes: "Stake Referral",
      teamVolume: "Volum Tim",
      totalDownlineVolume: "Total volum downline",
      teamDividend: "Dividen Tim",
      harvest: "Panen",
      activeLabel: "aktif",
      levelBreakdownTitle: "Rincian Tingkat — Detail Lengkap",
      levelBreakdownDesc: "Setiap tingkat mendapatkan persentase keuntungan compound yang dihasilkan oleh pengguna aktif pada kedalaman terkompresi tersebut. Pengguna tidak aktif dilewati — mereka tidak dihitung sebagai tingkat. L1: 10%, L2-L10: 5% masing-masing, L11-L15: 2% masing-masing. Buka tingkat dengan menambah referral langsung: 1-5 langsung = 1-5 tingkat, lalu setiap langsung tambahan = 2 tingkat lagi (maks 15 pada 10 langsung).",
      levelCol: "Tingkat",
      rateCol: "Rate",
      membersCol: "Anggota",
      businessCol: "Bisnis",
      earnedCol: "Diperoleh",
      statusCol: "Status",
      statusActive: "Aktif",
      statusNext: "Berikutnya",
      statusLocked: "Terkunci",
      total: "Total",
      levelLabel: "Tingkat {level}",
      directsNeeded: "{count} langsung",
      levelActivationTracker: "Pelacak Aktivasi Tingkat",
      levelActivationDesc: "Anda memiliki {directs} referral langsung, membuka {unlocked} / 15 tingkat dividen tim.",
      ppl: "org",
      legs: "{count} kaki",
      legVolumeBreakdown: "Rincian Volum Kaki",
      legVolumeDesc: "Setiap referral langsung membentuk \"kaki\". Total volum hilir mereka berkontribusi pada volum tim dan kualifikasi pangkat Anda.",
      refCol: "Referral",
      selfStakeCol: "Stake Sendiri",
      legVolumeCol: "Volum Kaki",
      shareCol: "Porsi",
      howItWorks: "Cara Dividen Tim Bekerja",
      how1: "Ketika pengguna mana pun di tim Anda compound stake mereka, keuntungan dihasilkan (0.15% per interval).",
      how2: "Anda mendapatkan persentase dari keuntungan tersebut berdasarkan tingkat: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Memerlukan stake aktif dan ruang batas FIFO. Pendapatan dibatasi pada 3X total stake Anda."
    },
    cms: {
      subtitle: "Beli langganan CMS dan dapatkan imbalan KAIRO",
      connectWalletTitle: "Keanggotaan Inti",
      notAvailable: "CMS Tidak Tersedia",
      notAvailableDesc: "Kontrak Langganan Keanggotaan Inti belum di-deploy.",
      yourSubscriptions: "Langganan Anda",
      remainingSlots: "Slot Tersisa",
      subscriptionStatus: "Status Langganan",
      active: "Aktif",
      ended: "Berakhir",
      purchaseSubscription: "Beli Langganan",
      subscriptionEnded: "Periode langganan telah berakhir",
      numberOfSubscriptions: "Jumlah Langganan",
      enterAmount: "Masukkan jumlah...",
      subscriptionDetails: "Detail Langganan",
      pricePerSub: "Harga per langganan:",
      loyaltyRewardPerSub: "Imbalan loyalitas per langganan:",
      totalCost: "Total biaya:",
      youllEarn: "Anda akan dapat:",
      approveUsdt: "Setujui USDT",
      subscribeBtn: "Langgan ({cost} USDT)",
      completeRegistrationFirst: "Silakan lengkapi pendaftaran terlebih dahulu",
      claimRewards: "Klaim Imbalan",
      alreadyClaimed: "Anda telah mengklaim imbalan Anda",
      loyaltyRewards: "Imbalan Loyalitas",
      leadershipRewards: "Imbalan Kepemimpinan",
      totalClaimable: "Total Dapat Diklaim",
      claimRules: "Aturan Klaim",
      claimRule1: "Klaim sekali saja (pakai atau hilang)",
      claimRule2: "Memerlukan stake aktif di StakingManager",
      claimRule3: "Dibatasi oleh nilai stake aktif (kelebihan dihapus)",
      claimRule4: "90% dimintakan untuk Anda, 10% deflasi (tidak dimintakan)",
      excessWarning: "Peringatan: {amount} KAIRO akan dihapus permanen (melebihi batas stake)",
      maxClaimable: "Maksimum dapat diklaim (berdasarkan stake):",
      claimRewardsBtn: "Klaim Imbalan",
      leadershipRewardsTitle: "Imbalan Kepemimpinan (5 Tingkat)",
      levelCol: "Tingkat",
      requiredDirectsCol: "Langsung Dibutuhkan",
      rewardPerSubCol: "Imbalan/Langganan",
      subscriptionsCol: "Langganan",
      earnedCol: "Diperoleh (KAIRO)",
      levelLabel: "Tingkat {level}",
      howCmsWorks: "Cara CMS Bekerja",
      subscriptionBenefits: "Manfaat Langganan",
      benefit1: "10 USDT per langganan (maks 10.000 total)",
      benefit2: "Dapatkan 5 KAIRO imbalan loyalitas per langganan",
      benefit3: "Dapatkan imbalan kepemimpinan dari 5 tingkat referral",
      benefit4: "Klaim sekali dengan stake aktif (pakai atau hilang)",
      referralRewards: "Imbalan Referral",
      level1Desc: "1 KAIRO per langganan (0 langsung dibutuhkan)",
      level2Desc: "0.5 KAIRO per langganan (2 langsung dibutuhkan)",
      level3Desc: "0.5 KAIRO per langganan (3 langsung dibutuhkan)",
      level4Desc: "0.25 KAIRO per langganan (4 langsung dibutuhkan)",
      level5Desc: "0.25 KAIRO per langganan (5 langsung dibutuhkan)",
      level1: "Tingkat 1:",
      level2: "Tingkat 2:",
      level3: "Tingkat 3:",
      level4: "Tingkat 4:",
      level5: "Tingkat 5:"
    },
    analytics: {
      title: "Analitik Protokol",
      subtitle: "Statistik ekosistem KAIRO real-time",
      kairoPrice: "Harga KAIRO",
      marketCap: "Kapitalisasi Pasar",
      poolLiquidityUsdt: "Likuiditas Pool (USDT)",
      totalBurned: "Total Dibakar",
      tokenSupply: "Pasokan Token",
      deflationaryNote: "Mekanisme deflasi melalui pembakaran",
      circulating: "Beredar",
      burned: "Dibakar",
      effectiveSupply: "Pasokan Efektif",
      socialLock: "Social Lock",
      burnRate: "Tingkat Pembakaran",
      liquidityPool: "Pool Likuiditas",
      dexPoolComposition: "Komposisi pool DEX",
      kairoInPool: "KAIRO di Pool",
      usdtInPool: "USDT di Pool",
      pricePerSupply: "Harga (USDT / Total Pasokan)"
    },
    portfolio: {
      totalPortfolioValue: "Total Nilai Portfolio",
      activeStakes: "Stake Aktif",
      totalStaked: "Total Staked",
      totalEarned: "Total Diperoleh",
      remainingCapping: "Batas Tersisa",
      kairoPrice: "Harga KAIRO",
      poolLiquidity: "Likuiditas Pool",
      totalCirculation: "Total Sirkulasi",
      harvestableAffiliate: "Dapat Dipanen (Afiliasi)",
      activeDirects: "Langsung Aktif"
    },
    activeStakesTable: {
      title: "Stake Aktif",
      loading: "Memuat stake...",
      empty: "Tidak ada stake aktif. Mulai staking untuk mendapatkan imbalan!",
      tierCount: "{count} tingkat",
      stakeCount: "{count} stake",
      stakedAmount: "Jumlah Staked",
      capProgress: "Kemajuan Batas 3X",
      harvestable: "Dapat Dipanen",
      harvested: "Dipanen",
      totalEarned: "Total Diperoleh",
      pendingCompoundProfit: "Keuntungan compound tertunda",
      autoCompound: "Auto Compound",
      autoCompoundBtn: "Auto Compound ({count})",
      accruing: "Bertambah",
      harvest: "Panen ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      intervals: "interval"
    },
    income: {
      title: "Ringkasan Pendapatan",
      typesCount: "{count} jenis",
      direct: "Komisi Langsung",
      team: "Dividen Tim",
      rank: "Gaji Pangkat",
      harvest: "Panen",
      pendingHarvest: "Panen Tertunda",
      affiliateHarvested: "Afiliasi Dipanen",
      directLabel: "Langsung",
      teamLabel: "Tim",
      rankLabel: "Pangkat",
      stakingEarnings: "Pendapatan Staking",
      harvestedLabel: "Dipanen",
      harvestableLabel: "Dapat Dipanen"
    },
    faucet: {
      testnetFaucet: "Faucet Testnet · USDT Mock",
      mintDesc: "Buat USDT uji untuk pengembangan. Saldo saat ini:",
      mint10000: "Buat 10.000 USDT",
      mint: "Buat",
      customPlaceholder: "kustom",
      mintingPending: "Membuat USDT uji…",
      mintingDesc: "Mengirim {amount} USDT ke dompet Anda",
      mintedSuccess: "Berhasil membuat {amount} USDT uji",
      mintFailed: "Pembuatan gagal",
      invalidAmount: "Jumlah tidak valid"
    },
    common: {
      connectWalletTitle: "Hubungkan Dompet Anda",
      connectWalletDesc: "Hubungkan dompet Anda untuk melihat portfolio, mengelola stake, dan melacak pendapatan."
    }
  },

  zh: {
    staking: {
      connectWalletTitle: "连接钱包以质押",
      closingInterval: "关闭间隔",
      newStake: "新质押",
      amount: "金额 (USDT)",
      amountPlaceholder: "输入金额...",
      balanceHelper: "余额: {balance} USDT | 最低: 10 USDT | 无上限",
      autoCompoundEvery: "每 {interval} 自动复利",
      approveAndStake: "授权 & 质押 ${amount}",
      stakeBtn: "质押 ${amount}",
      yourStakes: "您的质押",
      active: "活跃",
      noActiveStakesDesc: "暂无活跃质押。创建您的第一个质押开始赚取!",
      stakeCount: "{count} 笔质押",
      totalStaked: "总质押",
      tierHeader: "3X上限",
      pendingCompoundProfit: "待复利利润",
      autoCompoundBtn: "自动复利 ({count})",
      accruing: "累积中",
      harvestBtn: "收获 ${amount}",
      minHarvestStake: "最低 $10/质押",
      minHarvestAmount: "最低 $10",
      total: "总计",
      tierCol: "等级",
      stakedCol: "已质押",
      earnedCol: "已赚取",
      harvestedCol: "已收获",
      capCol: "3X上限",
      startedCol: "开始时间",
      statusCol: "状态",
      actionCol: "操作",
      statusActive: "活跃",
      statusCapped: "已满额",
      statusClosed: "已关闭",
      unstake: "解除质押",
      unstakeConfirm: "解除质押 #{index}?\n\n您质押了 ${original} USDT。\n您将收到 ~${preview} KAIRO\n(80%本金,扣除未结算已收获收益)。\n\n此操作不可逆。继续?",
      calcTitle: "复利计算器",
      calcSubtitle: "预测潜在利润随时间累积",
      calcStakeAmount: "质押金额 (USDT)",
      calcEnterAmount: "输入质押金额...",
      calcDuration: "期限: {count} 个月",
      calcProjectedProfit: "预计利润",
      calcTier: "等级",
      calcFrequency: "频率",
      calcCompounds: "复利次数",
      calcNote: "每次复利 0.15% · 等级和频率根据金额自动检测",
      levelUnlockTitle: "团队分红等级解锁",
      levelUnlockDesc: "通过添加直接推荐人来解锁更多团队分红等级。您目前有 {count} 个直接推荐人和 {unlocked} / 15 个已解锁等级。",
      directs: "直接",
      intervals: "间隔"
    },
    p2p: {
      subtitle: "原子级点对点 KAIRO 交易",
      connectWalletTitle: "连接钱包以交易",
      connectWalletDesc: "访问点对点 KAIRO 交易",
      dexPrice: "DEX价格",
      vol: "量",
      noActiveBuyOrders: "无活跃买单",
      noActiveSellOrders: "无活跃卖单",
      fill: "成交",
      enterAmount: "输入金额...",
      usdtAmount: "USDT金额",
      kairoAmount: "KAIRO金额",
      max: "最大: {amount}",
      balanceLabel: "余额: {amount} {token}",
      dexReferencePrice: "DEX参考价",
      tradingFee: "交易费",
      estimated: "预估 {token}",
      approveAndCreateBuy: "授权 & 创建买单",
      createBuyOrder: "创建买单",
      approveAndCreateSell: "授权 & 创建卖单",
      createSellOrder: "创建卖单",
      noActiveOrders: "您没有活跃订单。",
      noActiveOrdersDesc: "创建一个买单或卖单开始交易。",
      myBuyOrders: "我的买单",
      mySellOrders: "我的卖单",
      cancel: "取消",
      remaining: "${amount} 剩余",
      filledOfTotal: "${filled} 已成交 / ${total} 总计",
      kairoRemaining: "{amount} KAIRO 剩余"
    },
    swap: {
      title: "兑换",
      subtitle: "单向兑换,手续费 {fee}%,通缩销毁",
      connectWalletTitle: "连接钱包以兑换",
      connectWalletDesc: "KAIRO单向兑换为USDT,通缩销毁",
      poolUsdt: "池中USDT",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "兑换包含通缩销毁",
      youPay: "您支付",
      youReceive: "您收到 (预估)",
      rate: "汇率",
      fee: "手续费 ({percent}%)",
      minOutput: "最小输出 ({slippage}% 滑点)",
      slippage: "滑点:",
      priceImpact: "价格影响",
      approveAndSwap: "授权 & 兑换",
      swapBtn: "兑换 KAIRO → USDT",
      max: "最大: {amount}"
    },
    referralNetwork: {
      title: "推荐网络",
      rank: "等级",
      directReferrals: "直接推荐",
      directActive: "{count} 活跃",
      directBusiness: "直接业务量",
      referralStakes: "推荐质押",
      teamBusiness: "团队业务量",
      totalDownlineVolume: "总下线业务量",
      shareLink: "分享您的链接邀请新成员并赚取多级佣金。",
      earnDirect: "每笔推荐质押赚取 5% 直接佣金 + 15级团队分红。"
    },
    rankDividend: {
      title: "等级分红",
      subtitle: "通过团队业务量达成等级并赚取定期薪资奖励",
      connectWalletTitle: "连接钱包",
      rankChangeDetected: "检测到等级变更: {from} → {to}",
      rankChangeDesc: "确认后您的薪资计时器将重置。点击下方更新您的等级。",
      updateRank: "更新等级",
      currentRank: "当前等级",
      rankLevel: "等级 {level} / 10",
      rankSalary: "等级薪资",
      perPeriod: "每期",
      harvestable: "可收获",
      crystallized: "已结晶",
      harvested: "已收获",
      totalClaimed: "总计已领取",
      rankProgress: "等级进度",
      earningPerPeriod: "赚取 ${amount} / 期",
      pending: "待处理: ${amount} · 点击同步以结晶",
      syncRankChange: "同步等级变更",
      syncRankSalary: "同步等级薪资 (+${amount})",
      nothingToSync: "无可同步",
      harvestBtn: "收获 ${amount}",
      nothingToHarvest: "无可收获",
      teamVolumeTitle: "团队业务量",
      totalTeamVolume: "总团队业务量",
      next: "下一级: {rank}",
      targetMet: "目标达成!",
      needMoreVolume: "还需 ${amount} 合格业务量",
      progressAchieved: "达成 {percent}%",
      directReferrals: "直接推荐",
      activeDirects: "活跃直接",
      unlockedLevels: "已解锁等级",
      harvestIncomeTitle: "收获收益",
      direct: "直接",
      team: "团队",
      rank: "等级",
      harvest: "收获",
      fiftyPctCapRule: "每腿50%上限规则",
      fiftyPctDesc: "对于每个等级目标,最多50%的该等级门槛可从任何单腿计入。您的个人业务量不计入等级资格。即使单腿有巨大业务量,也只计入等级目标的50%。",
      totalTeamVolumeLabel: "总团队业务量",
      largestLeg: "最大腿",
      numberOfLegs: "腿数",
      qualifyingVolume: "合格业务量",
      legVolumeBreakdown: "腿业务量明细",
      leg: "腿 {index}",
      maxCredited: "(最多 ${amount})",
      rankTargetsTitle: "等级目标与薪资",
      rankCol: "等级",
      teamVolumeTargetCol: "团队业务量目标",
      salaryCol: "薪资 / 期",
      progressCol: "进度",
      statusCol: "状态",
      achieved: "已达成",
      nextTarget: "下一目标",
      locked: "已锁定",
      salaryHistoryTitle: "薪资历史",
      records: "{count} 条记录",
      loadingHistory: "加载历史中...",
      noSalaryHistory: "暂无薪资历史。达成等级开始赚取!",
      typeCol: "类型",
      dateCol: "日期",
      amountCol: "金额",
      txCol: "交易",
      salaryCredited: "薪资已入账",
      harvestedLabel: "已收获"
    },
    teamDividend: {
      title: "团队分红",
      subtitle: "根据您的直接推荐数量从15级团队复利利润中赚取。链中的非活跃用户将被跳过 — 只有活跃质押者算作等级。",
      connectWalletTitle: "连接钱包",
      connectWalletDesc: "查看您的团队分红收益",
      unlockedLevels: "已解锁等级",
      directReferrals: "直接推荐",
      moreForNext: "还需 {count} 人解锁下一级",
      maxLevelsUnlocked: "已解锁最高等级",
      directBusiness: "直接业务量",
      referralStakes: "推荐质押",
      teamVolume: "团队业务量",
      totalDownlineVolume: "总下线业务量",
      teamDividend: "团队分红",
      harvest: "收获",
      activeLabel: "活跃",
      levelBreakdownTitle: "等级明细 — 完整详情",
      levelBreakdownDesc: "每个等级赚取该压缩深度活跃用户产生的复利利润百分比。非活跃用户将被跳过 — 不算作等级。L1: 10%, L2-L10: 各5%, L11-L15: 各2%。通过添加直接推荐解锁等级: 1-5直接 = 1-5级,然后每多一个直接 = 再加2级 (10个直接时最多15级)。",
      levelCol: "等级",
      rateCol: "比率",
      membersCol: "成员",
      businessCol: "业务量",
      earnedCol: "已赚取",
      statusCol: "状态",
      statusActive: "活跃",
      statusNext: "下一级",
      statusLocked: "已锁定",
      total: "总计",
      levelLabel: "等级 {level}",
      directsNeeded: "{count} 直接",
      levelActivationTracker: "等级激活追踪器",
      levelActivationDesc: "您有 {directs} 个直接推荐,解锁 {unlocked} / 15 个团队分红等级。",
      ppl: "人",
      legs: "{count} 腿",
      legVolumeBreakdown: "腿业务量明细",
      legVolumeDesc: "每个直接推荐形成一个\"腿\"。其全部下游业务量贡献到您的团队业务量和等级资格。",
      refCol: "推荐",
      selfStakeCol: "自身质押",
      legVolumeCol: "腿业务量",
      shareCol: "份额",
      howItWorks: "团队分红如何运作",
      how1: "当您团队中任何用户复利其质押时,产生利润 (每间隔0.15%)。",
      how2: "您根据等级赚取该利润的百分比: L1=10%, L2-L10=5%, L11-L15=2%。",
      how3: "需要活跃质押和FIFO上限空间。收益上限为总质押的3X。"
    },
    cms: {
      subtitle: "购买CMS订阅并赚取KAIRO奖励",
      connectWalletTitle: "核心会员",
      notAvailable: "CMS不可用",
      notAvailableDesc: "核心会员订阅合约尚未部署。",
      yourSubscriptions: "您的订阅",
      remainingSlots: "剩余名额",
      subscriptionStatus: "订阅状态",
      active: "活跃",
      ended: "已结束",
      purchaseSubscription: "购买订阅",
      subscriptionEnded: "订阅期已结束",
      numberOfSubscriptions: "订阅数量",
      enterAmount: "输入金额...",
      subscriptionDetails: "订阅详情",
      pricePerSub: "每份订阅价格:",
      loyaltyRewardPerSub: "每份订阅忠诚奖励:",
      totalCost: "总费用:",
      youllEarn: "您将赚取:",
      approveUsdt: "授权USDT",
      subscribeBtn: "订阅 ({cost} USDT)",
      completeRegistrationFirst: "请先完成注册",
      claimRewards: "领取奖励",
      alreadyClaimed: "您已领取奖励",
      loyaltyRewards: "忠诚奖励",
      leadershipRewards: "领导奖励",
      totalClaimable: "总计可领取",
      claimRules: "领取规则",
      claimRule1: "仅限一次领取 (用或不用)",
      claimRule2: "需要在StakingManager中有活跃质押",
      claimRule3: "受活跃质押价值限制 (超出部分删除)",
      claimRule4: "90%铸造给您, 10%通缩 (不铸造)",
      excessWarning: "警告: {amount} KAIRO 将被永久删除 (超过质押上限)",
      maxClaimable: "最大可领取 (基于质押):",
      claimRewardsBtn: "领取奖励",
      leadershipRewardsTitle: "领导奖励 (5级)",
      levelCol: "等级",
      requiredDirectsCol: "所需直接",
      rewardPerSubCol: "每份奖励",
      subscriptionsCol: "订阅",
      earnedCol: "已赚取 (KAIRO)",
      levelLabel: "等级 {level}",
      howCmsWorks: "CMS如何运作",
      subscriptionBenefits: "订阅福利",
      benefit1: "每份订阅 10 USDT (总计最多 10,000)",
      benefit2: "每份订阅赚取 5 KAIRO 忠诚奖励",
      benefit3: "从5个推荐等级赚取领导奖励",
      benefit4: "有活跃质押时一次领取 (用或不用)",
      referralRewards: "推荐奖励",
      level1Desc: "每份订阅 1 KAIRO (无需直接推荐)",
      level2Desc: "每份订阅 0.5 KAIRO (需2个直接推荐)",
      level3Desc: "每份订阅 0.5 KAIRO (需3个直接推荐)",
      level4Desc: "每份订阅 0.25 KAIRO (需4个直接推荐)",
      level5Desc: "每份订阅 0.25 KAIRO (需5个直接推荐)",
      level1: "等级 1:",
      level2: "等级 2:",
      level3: "等级 3:",
      level4: "等级 4:",
      level5: "等级 5:"
    },
    analytics: {
      title: "协议分析",
      subtitle: "实时KAIRO生态系统统计",
      kairoPrice: "KAIRO价格",
      marketCap: "市值",
      poolLiquidityUsdt: "池流动性 (USDT)",
      totalBurned: "总销毁",
      tokenSupply: "代币供应",
      deflationaryNote: "通过销毁实现通缩机制",
      circulating: "流通中",
      burned: "已销毁",
      effectiveSupply: "有效供应",
      socialLock: "社交锁",
      burnRate: "销毁率",
      liquidityPool: "流动性池",
      dexPoolComposition: "DEX池构成",
      kairoInPool: "池中KAIRO",
      usdtInPool: "池中USDT",
      pricePerSupply: "价格 (USDT / 总供应)"
    },
    portfolio: {
      totalPortfolioValue: "总组合价值",
      activeStakes: "活跃质押",
      totalStaked: "总质押",
      totalEarned: "总赚取",
      remainingCapping: "剩余上限",
      kairoPrice: "KAIRO价格",
      poolLiquidity: "池流动性",
      totalCirculation: "总流通",
      harvestableAffiliate: "可收获 (推荐)",
      activeDirects: "活跃直接"
    },
    activeStakesTable: {
      title: "活跃质押",
      loading: "加载质押中...",
      empty: "无活跃质押。开始质押赚取奖励!",
      tierCount: "{count} 个等级",
      stakeCount: "{count} 笔质押",
      stakedAmount: "质押金额",
      capProgress: "3X上限进度",
      harvestable: "可收获",
      harvested: "已收获",
      totalEarned: "总赚取",
      pendingCompoundProfit: "待复利利润",
      autoCompound: "自动复利",
      autoCompoundBtn: "自动复利 ({count})",
      accruing: "累积中",
      harvest: "收获 ${amount}",
      minHarvestStake: "最低 $10/质押",
      minHarvestAmount: "最低 $10",
      intervals: "间隔"
    },
    income: {
      title: "收入汇总",
      typesCount: "{count} 种",
      direct: "直接佣金",
      team: "团队分红",
      rank: "等级薪资",
      harvest: "收获",
      pendingHarvest: "待收获",
      affiliateHarvested: "推荐已收获",
      directLabel: "直接",
      teamLabel: "团队",
      rankLabel: "等级",
      stakingEarnings: "质押收益",
      harvestedLabel: "已收获",
      harvestableLabel: "可收获"
    },
    faucet: {
      testnetFaucet: "测试网水龙头 · 模拟USDT",
      mintDesc: "铸造测试USDT用于开发。当前余额:",
      mint10000: "铸造 10,000 USDT",
      mint: "铸造",
      customPlaceholder: "自定义",
      mintingPending: "正在铸造测试USDT…",
      mintingDesc: "发送 {amount} USDT 到您的钱包",
      mintedSuccess: "已铸造 {amount} 测试USDT",
      mintFailed: "铸造失败",
      invalidAmount: "无效金额"
    },
    common: {
      connectWalletTitle: "连接您的钱包",
      connectWalletDesc: "连接钱包查看您的组合、管理质押并追踪收益。"
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
