import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  ja: {
    staking: {
      connectWalletTitle: "ステーキングのためにウォレットを接続",
      closingInterval: "クロージング間隔",
      newStake: "新しいステーク",
      amount: "金額 (USDT)",
      amountPlaceholder: "金額を入力...",
      balanceHelper: "残高: {balance} USDT | 最小: 10 USDT | 最大制限なし",
      autoCompoundEvery: "{interval}ごとに自動複利",
      approveAndStake: "承認 & ステーク ${amount}",
      stakeBtn: "ステーク ${amount}",
      yourStakes: "あなたのステーク",
      active: "アクティブ",
      noActiveStakesDesc: "アクティブなステークがありません。最初のステークを作成して収益を開始しましょう！",
      stakeCount: "{count} ステーク",
      totalStaked: "合計ステーク",
      tierHeader: "3X上限",
      pendingCompoundProfit: "保留中の複利利益",
      autoCompoundBtn: "自動複利 ({count})",
      accruing: "蓄積中",
      harvestBtn: "収穫 ${amount}",
      minHarvestStake: "最小 $10/ステーク",
      minHarvestAmount: "最小 $10",
      total: "合計",
      tierCol: "ティア",
      stakedCol: "ステーク",
      earnedCol: "獲得",
      harvestedCol: "収穫済み",
      capCol: "3X上限",
      startedCol: "開始",
      statusCol: "ステータス",
      actionCol: "アクション",
      statusActive: "アクティブ",
      statusCapped: "上限到達",
      statusClosed: "終了",
      unstake: "アンステーク",
      unstakeConfirm: "ステーク #{index} をアンステークしますか？\n\n${original} USDTをステークしました。\n~${preview} KAIROを受け取ります\n(元本の80%、保留中の収穫収入を差し引き)。\n\nこの操作は取り消せません。続行しますか？",
      calcTitle: "複利計算機",
      calcSubtitle: "時間の経過に伴う潜在的な利益蓄積を予測",
      calcStakeAmount: "ステーク金額 (USDT)",
      calcEnterAmount: "ステーク金額を入力...",
      calcDuration: "期間: {count}ヶ月",
      calcProjectedProfit: "予想利益",
      calcTier: "ティア",
      calcFrequency: "頻度",
      calcCompounds: "複利回数",
      calcNote: "複利あたり0.15% · ティアと頻度は金額から自動検出",
      levelUnlockTitle: "チーム配当レベルのロック解除",
      levelUnlockDesc: "直接紹介者を追加してチーム配当レベルをさらに解除しましょう。現在 {count} 人の直接紹介者と {unlocked} / 15 レベルが解除されています。",
      directs: "直接",
      intervals: "間隔"
    },
    p2p: {
      subtitle: "原子ピアツーピアKAIRO取引",
      connectWalletTitle: "取引のためにウォレットを接続",
      connectWalletDesc: "ピアツーピアKAIRO取引にアクセス",
      dexPrice: "DEX価格",
      vol: "出来高",
      noActiveBuyOrders: "アクティブな買い注文なし",
      noActiveSellOrders: "アクティブな売り注文なし",
      fill: "約定",
      enterAmount: "金額を入力...",
      usdtAmount: "USDT金額",
      kairoAmount: "KAIRO金額",
      max: "最大: {amount}",
      balanceLabel: "残高: {amount} {token}",
      dexReferencePrice: "DEX参照価格",
      tradingFee: "取引手数料",
      estimated: "推定 {token}",
      approveAndCreateBuy: "承認 & 買い注文作成",
      createBuyOrder: "買い注文作成",
      approveAndCreateSell: "承認 & 売り注文作成",
      createSellOrder: "売り注文作成",
      noActiveOrders: "アクティブな注文がありません。",
      noActiveOrdersDesc: "開始するには買い注文または売り注文を作成してください。",
      myBuyOrders: "自分の買い注文",
      mySellOrders: "自分の売り注文",
      cancel: "キャンセル",
      remaining: "${amount} 残り",
      filledOfTotal: "${total} 合計中 ${filled} 約定",
      kairoRemaining: "{amount} KAIRO 残り"
    },
    swap: {
      title: "スワップ",
      subtitle: "{fee}%手数料とデフレーションバーン付き一方通行スワップ",
      connectWalletTitle: "スワップのためにウォレットを接続",
      connectWalletDesc: "デフレーションバーン付きKAIROからUSDTへ一方通行スワップ",
      poolUsdt: "プールUSDT",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "スワップにはデフレーションバーンが含まれます",
      youPay: "支払い",
      youReceive: "受取 (推定)",
      rate: "レート",
      fee: "手数料 ({percent}%)",
      minOutput: "最小出力 ({slippage}% スリッページ)",
      slippage: "スリッページ:",
      priceImpact: "価格影響",
      approveAndSwap: "承認 & スワップ",
      swapBtn: "KAIRO → USDT スワップ",
      max: "最大: {amount}"
    },
    referralNetwork: {
      title: "紹介ネットワーク",
      rank: "ランク",
      directReferrals: "直接紹介者",
      directActive: "{count} アクティブ",
      directBusiness: "直接取引高",
      referralStakes: "紹介ステーク",
      teamBusiness: "チーム取引高",
      totalDownlineVolume: "総ダウンライン取引高",
      shareLink: "リンクを共有して新しいメンバーを招待し、多段階コミッションを獲得しましょう。",
      earnDirect: "各紹介ステークで5%直接コミッション + 15レベルのチーム配当を獲得。"
    },
    rankDividend: {
      title: "ランク配当",
      subtitle: "チーム取引高でランクを達成し、定期的な給与報酬を獲得",
      connectWalletTitle: "ウォレットを接続",
      rankChangeDetected: "ランク変更を検出: {from} → {to}",
      rankChangeDesc: "確認すると給与タイマーがリセットされます。下をクリックしてランクを更新してください。",
      updateRank: "ランク更新",
      currentRank: "現在のランク",
      rankLevel: "レベル {level} / 10",
      rankSalary: "ランク給与",
      perPeriod: "期間あたり",
      harvestable: "収穫可能",
      crystallized: "結晶化済み",
      harvested: "収穫済み",
      totalClaimed: "請求合計",
      rankProgress: "ランク進捗",
      earningPerPeriod: "${amount} / 期間 獲得",
      pending: "保留中: ${amount} · 結晶化するには同期をクリック",
      syncRankChange: "ランク変更を同期",
      syncRankSalary: "ランク給与を同期 (+${amount})",
      nothingToSync: "同期するものなし",
      harvestBtn: "収穫 ${amount}",
      nothingToHarvest: "収穫するものなし",
      teamVolumeTitle: "チーム取引高",
      totalTeamVolume: "総チーム取引高",
      next: "次: {rank}",
      targetMet: "目標達成！",
      needMoreVolume: "あと ${amount} の適格取引高が必要",
      progressAchieved: "{percent}% 達成",
      directReferrals: "直接紹介者",
      activeDirects: "アクティブ直接",
      unlockedLevels: "ロック解除済みレベル",
      harvestIncomeTitle: "収穫収入",
      direct: "直接",
      team: "チーム",
      rank: "ランク",
      harvest: "収穫",
      fiftyPctCapRule: "レグあたり50%上限ルール",
      fiftyPctDesc: "各ランク目標について、そのランクの閾値の最大50%までを単一レグから計上できます。個人取引高はランク資格に含まれません。単一レグが巨額の取引高を持っていても、ランク目標の50%のみが計上されます。",
      totalTeamVolumeLabel: "総チーム取引高",
      largestLeg: "最大レグ",
      numberOfLegs: "レグ数",
      qualifyingVolume: "適格取引高",
      legVolumeBreakdown: "レグ別取引高内訳",
      leg: "レグ {index}",
      maxCredited: "(最大 ${amount})",
      rankTargetsTitle: "ランク目標と給与",
      rankCol: "ランク",
      teamVolumeTargetCol: "チーム取引高目標",
      salaryCol: "給与 / 期間",
      progressCol: "進捗",
      statusCol: "ステータス",
      achieved: "達成",
      nextTarget: "次の目標",
      locked: "ロック",
      salaryHistoryTitle: "給与履歴",
      records: "{count} レコード",
      loadingHistory: "履歴を読み込み中...",
      noSalaryHistory: "給与履歴がありません。ランクを達成して収益を開始しましょう！",
      typeCol: "タイプ",
      dateCol: "日付",
      amountCol: "金額",
      txCol: "Tx",
      salaryCredited: "給与計上済み",
      harvestedLabel: "収穫済み"
    },
    teamDividend: {
      title: "チーム配当",
      subtitle: "直接紹介者数に基づき15レベルのチーム複利利益から獲得します。チェーン内の非アクティブユーザーはスキップされます — アクティブなステーク参加者のみがレベルとしてカウントされます。",
      connectWalletTitle: "ウォレットを接続",
      connectWalletDesc: "チーム配当収入を表示",
      unlockedLevels: "ロック解除済みレベル",
      directReferrals: "直接紹介者",
      moreForNext: "次のレベルまであと {count}",
      maxLevelsUnlocked: "最大レベル解除済み",
      directBusiness: "直接取引高",
      referralStakes: "紹介ステーク",
      teamVolume: "チーム取引高",
      totalDownlineVolume: "総ダウンライン取引高",
      teamDividend: "チーム配当",
      harvest: "収穫",
      activeLabel: "アクティブ",
      levelBreakdownTitle: "レベル内訳 — 全詳細",
      levelBreakdownDesc: "各レベルは、その圧縮深度のアクティブユーザーが生成した複利利益のパーセンテージを獲得します。非アクティブユーザーはスキップされます — レベルとしてカウントされません。L1: 10%、L2-L10: 各5%、L11-L15: 各2%。直接紹介者を追加してレベルを解除: 1-5直接 = 1-5レベル、その後追加直接ごとに2レベル (10直接で最大15)。",
      levelCol: "レベル",
      rateCol: "レート",
      membersCol: "メンバー",
      businessCol: "取引高",
      earnedCol: "獲得",
      statusCol: "ステータス",
      statusActive: "アクティブ",
      statusNext: "次",
      statusLocked: "ロック",
      total: "合計",
      levelLabel: "レベル {level}",
      directsNeeded: "{count} 直接",
      levelActivationTracker: "レベル有効化トラッカー",
      levelActivationDesc: "直接紹介者 {directs} 人、チーム配当レベル {unlocked} / 15 解除。",
      ppl: "人",
      legs: "{count} レグ",
      legVolumeBreakdown: "レグ別取引高内訳",
      legVolumeDesc: "各直接紹介者が「レグ」を形成します。その下流の合計取引高はチーム取引高とランク資格に貢献します。",
      refCol: "紹介者",
      selfStakeCol: "自己ステーク",
      legVolumeCol: "レグ取引高",
      shareCol: "シェア",
      howItWorks: "チーム配当の仕組み",
      how1: "チーム内のユーザーがステークを複利化すると利益が生成されます (間隔あたり0.15%)。",
      how2: "レベルに応じてその利益のパーセンテージを獲得します: L1=10%、L2-L10=5%、L11-L15=2%。",
      how3: "アクティブなステークとFIFO上限スペースが必要です。収入は合計ステークの3Xまで制限されます。"
    },
    cms: {
      subtitle: "CMSサブスクリプションを購入しKAIRO報酬を獲得",
      connectWalletTitle: "コアメンバーシップ",
      notAvailable: "CMS利用不可",
      notAvailableDesc: "コアメンバーシップサブスクリプションコントラクトはまだデプロイされていません。",
      yourSubscriptions: "あなたのサブスクリプション",
      remainingSlots: "残りスロット",
      subscriptionStatus: "サブスクリプション状態",
      active: "アクティブ",
      ended: "終了",
      purchaseSubscription: "サブスクリプション購入",
      subscriptionEnded: "サブスクリプション期間が終了しました",
      numberOfSubscriptions: "サブスクリプション数",
      enterAmount: "金額を入力...",
      subscriptionDetails: "サブスクリプション詳細",
      pricePerSub: "サブスクリプションあたりの価格:",
      loyaltyRewardPerSub: "サブスクリプションあたりのロイヤリティ報酬:",
      totalCost: "合計コスト:",
      youllEarn: "獲得予定:",
      approveUsdt: "USDT承認",
      subscribeBtn: "購読 ({cost} USDT)",
      completeRegistrationFirst: "まず登録を完了してください",
      claimRewards: "報酬請求",
      alreadyClaimed: "報酬はすでに請求済みです",
      loyaltyRewards: "ロイヤリティ報酬",
      leadershipRewards: "リーダーシップ報酬",
      totalClaimable: "請求可能合計",
      claimRules: "請求ルール",
      claimRule1: "1回限りの請求 (使うか失う)",
      claimRule2: "StakingManagerにアクティブなステークが必要",
      claimRule3: "アクティブステーク価値で制限 (超過分は削除)",
      claimRule4: "90%があなたにミント、10%デフレーション (ミントなし)",
      excessWarning: "警告: {amount} KAIROが永久に削除されます (ステーク上限を超過)",
      maxClaimable: "最大請求可能 (ステークベース):",
      claimRewardsBtn: "報酬請求",
      leadershipRewardsTitle: "リーダーシップ報酬 (5レベル)",
      levelCol: "レベル",
      requiredDirectsCol: "必要直接",
      rewardPerSubCol: "サブスクあたり報酬",
      subscriptionsCol: "サブスクリプション",
      earnedCol: "獲得 (KAIRO)",
      levelLabel: "レベル {level}",
      howCmsWorks: "CMSの仕組み",
      subscriptionBenefits: "サブスクリプション特典",
      benefit1: "サブスクリプションあたり10 USDT (合計最大10,000)",
      benefit2: "サブスクリプションあたり5 KAIROロイヤリティ報酬を獲得",
      benefit3: "5つの紹介レベルからリーダーシップ報酬を獲得",
      benefit4: "アクティブステークで1回請求 (使うか失う)",
      referralRewards: "紹介報酬",
      level1Desc: "サブスクリプションあたり1 KAIRO (直接0名必要)",
      level2Desc: "サブスクリプションあたり0.5 KAIRO (直接2名必要)",
      level3Desc: "サブスクリプションあたり0.5 KAIRO (直接3名必要)",
      level4Desc: "サブスクリプションあたり0.25 KAIRO (直接4名必要)",
      level5Desc: "サブスクリプションあたり0.25 KAIRO (直接5名必要)",
      level1: "レベル 1:",
      level2: "レベル 2:",
      level3: "レベル 3:",
      level4: "レベル 4:",
      level5: "レベル 5:"
    },
    analytics: {
      title: "プロトコル分析",
      subtitle: "リアルタイムKAIROエコシステム統計",
      kairoPrice: "KAIRO価格",
      marketCap: "時価総額",
      poolLiquidityUsdt: "プール流動性 (USDT)",
      totalBurned: "総バーン",
      tokenSupply: "トークン供給",
      deflationaryNote: "バーンによるデフレーションメカニズム",
      circulating: "流通中",
      burned: "バーン済み",
      effectiveSupply: "有効供給",
      socialLock: "ソーシャルロック",
      burnRate: "バーン率",
      liquidityPool: "流動性プール",
      dexPoolComposition: "DEXプール構成",
      kairoInPool: "プール内KAIRO",
      usdtInPool: "プール内USDT",
      pricePerSupply: "価格 (USDT / 総供給)"
    },
    portfolio: {
      totalPortfolioValue: "総ポートフォリオ価値",
      activeStakes: "アクティブステーク",
      totalStaked: "合計ステーク",
      totalEarned: "合計獲得",
      remainingCapping: "残上限",
      kairoPrice: "KAIRO価格",
      poolLiquidity: "プール流動性",
      totalCirculation: "総流通",
      harvestableAffiliate: "収穫可能 (アフィリエイト)",
      activeDirects: "アクティブ直接"
    },
    activeStakesTable: {
      title: "アクティブステーク",
      loading: "ステークを読み込み中...",
      empty: "アクティブなステークがありません。報酬を獲得するにはステーキングを開始してください！",
      tierCount: "{count} ティア",
      stakeCount: "{count} ステーク",
      stakedAmount: "ステーク金額",
      capProgress: "3X上限進捗",
      harvestable: "収穫可能",
      harvested: "収穫済み",
      totalEarned: "合計獲得",
      pendingCompoundProfit: "保留中の複利利益",
      autoCompound: "自動複利",
      autoCompoundBtn: "自動複利 ({count})",
      accruing: "蓄積中",
      harvest: "収穫 ${amount}",
      minHarvestStake: "最小 $10/ステーク",
      minHarvestAmount: "最小 $10",
      intervals: "間隔"
    },
    income: {
      title: "収入サマリー",
      typesCount: "{count} 種類",
      direct: "直接コミッション",
      team: "チーム配当",
      rank: "ランク給与",
      harvest: "収穫",
      pendingHarvest: "保留収穫",
      affiliateHarvested: "アフィリエイト収穫済み",
      directLabel: "直接",
      teamLabel: "チーム",
      rankLabel: "ランク",
      stakingEarnings: "ステーキング収入",
      harvestedLabel: "収穫済み",
      harvestableLabel: "収穫可能"
    },
    faucet: {
      testnetFaucet: "テストネットフォーセット · モックUSDT",
      mintDesc: "開発用のテストUSDTをミント。現在の残高:",
      mint10000: "10,000 USDT ミント",
      mint: "ミント",
      customPlaceholder: "カスタム",
      mintingPending: "テストUSDTをミント中…",
      mintingDesc: "あなたのウォレットに {amount} USDTを送信中",
      mintedSuccess: "{amount} テストUSDTをミントしました",
      mintFailed: "ミント失敗",
      invalidAmount: "無効な金額"
    },
    common: {
      connectWalletTitle: "ウォレットを接続",
      connectWalletDesc: "ポートフォリオを表示し、ステークを管理し、収入を追跡するためにウォレットを接続してください。"
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
