import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  th: {
    staking: {
      connectWalletTitle: "เชื่อมต่อกระเป๋าเงินเพื่อสเตก",
      closingInterval: "ช่วงปิด",
      newStake: "สเตกใหม่",
      amount: "จำนวน (USDT)",
      amountPlaceholder: "ป้อนจำนวน...",
      balanceHelper: "ยอดคงเหลือ: {balance} USDT | ขั้นต่ำ: 10 USDT | ไม่จำกัดสูงสุด",
      autoCompoundEvery: "ทบต้นอัตโนมัติทุก {interval}",
      approveAndStake: "อนุมัติ & สเตก ${amount}",
      stakeBtn: "สเตก ${amount}",
      yourStakes: "สเตกของคุณ",
      active: "ใช้งาน",
      noActiveStakesDesc: "ยังไม่มีสเตกที่ใช้งาน สร้างสเตกแรกเพื่อเริ่มสร้างรายได้!",
      stakeCount: "{count} สเตก",
      totalStaked: "สเตกรวม",
      tierHeader: "ขีดจำกัด 3X",
      pendingCompoundProfit: "กำไรทบต้นรอดำเนินการ",
      autoCompoundBtn: "ทบต้นอัตโนมัติ ({count})",
      accruing: "สะสม",
      harvestBtn: "เก็บเกี่ยว ${amount}",
      minHarvestStake: "ขั้นต่ำ $10/สเตก",
      minHarvestAmount: "ขั้นต่ำ $10",
      total: "รวม",
      tierCol: "ระดับ",
      stakedCol: "สเตก",
      earnedCol: "ได้รับ",
      harvestedCol: "เก็บเกี่ยวแล้ว",
      capCol: "ขีดจำกัด 3X",
      startedCol: "เริ่มต้น",
      statusCol: "สถานะ",
      actionCol: "การกระทำ",
      statusActive: "ใช้งาน",
      statusCapped: "ถึงขีดจำกัด",
      statusClosed: "ปิดแล้ว",
      unstake: "ถอนสเตก",
      unstakeConfirm: "ถอนสเตก #{index}?\n\nคุณสเตก ${original} USDT\nคุณจะได้รับ ~${preview} KAIRO\n(80% ของเงินต้น หักรายได้ที่เก็บเกี่ยวค้างอยู่)\n\nการกระทำนี้ไม่สามารถย้อนกลับได้ ดำเนินการต่อ?",
      calcTitle: "เครื่องคำนวณทบต้น",
      calcSubtitle: "คาดการณ์กำไรสะสมตามเวลา",
      calcStakeAmount: "จำนวนสเตก (USDT)",
      calcEnterAmount: "ป้อนจำนวนสเตก...",
      calcDuration: "ระยะเวลา: {count} เดือน",
      calcProjectedProfit: "กำไรที่คาดการณ์",
      calcTier: "ระดับ",
      calcFrequency: "ความถี่",
      calcCompounds: "จำนวนทบต้น",
      calcNote: "0.15% ต่อการทบต้น · ระดับและความถี่ตรวจหาอัตโนมัติจากจำนวน",
      levelUnlockTitle: "ปลดล็อกระดับเงินปันผลทีม",
      levelUnlockDesc: "ปลดล็อกระดับเงินปันผลทีมเพิ่มเติมโดยเพิ่มผู้แนะนำโดยตรง ปัจจุบันคุณมีผู้แนะนำโดยตรง {count} คน และปลดล็อก {unlocked} / 15 ระดับ",
      directs: "โดยตรง",
      intervals: "ช่วงเวลา"
    },
    p2p: {
      subtitle: "การเทรด KAIRO แบบเพียร์ทูเพียร์อะตอมิก",
      connectWalletTitle: "เชื่อมต่อกระเป๋าเงินเพื่อเทรด",
      connectWalletDesc: "เข้าถึงการเทรด KAIRO แบบเพียร์ทูเพียร์",
      dexPrice: "ราคา DEX",
      vol: "ปริมาณ",
      noActiveBuyOrders: "ไม่มีคำสั่งซื้อที่ใช้งาน",
      noActiveSellOrders: "ไม่มีคำสั่งขายที่ใช้งาน",
      fill: "เติม",
      enterAmount: "ป้อนจำนวน...",
      usdtAmount: "จำนวน USDT",
      kairoAmount: "จำนวน KAIRO",
      max: "สูงสุด: {amount}",
      balanceLabel: "ยอดคงเหลือ: {amount} {token}",
      dexReferencePrice: "ราคาอ้างอิง DEX",
      tradingFee: "ค่าธรรมเนียมเทรด",
      estimated: "ประมาณการ {token}",
      approveAndCreateBuy: "อนุมัติ & สร้างคำสั่งซื้อ",
      createBuyOrder: "สร้างคำสั่งซื้อ",
      approveAndCreateSell: "อนุมัติ & สร้างคำสั่งขาย",
      createSellOrder: "สร้างคำสั่งขาย",
      noActiveOrders: "คุณไม่มีคำสั่งที่ใช้งาน",
      noActiveOrdersDesc: "สร้างคำสั่งซื้อหรือขายเพื่อเริ่มต้น",
      myBuyOrders: "คำสั่งซื้อของฉัน",
      mySellOrders: "คำสั่งขายของฉัน",
      cancel: "ยกเลิก",
      remaining: "${amount} คงเหลือ",
      filledOfTotal: "${filled} เติมจาก ${total} รวม",
      kairoRemaining: "{amount} KAIRO คงเหลือ"
    },
    swap: {
      title: "สลับ",
      subtitle: "สลับทางเดียวด้วยค่าธรรมเนียม {fee}% และการเผ่าโทเคนแบบฝืดตัว",
      connectWalletTitle: "เชื่อมต่อกระเป๋าเงินเพื่อสลับ",
      connectWalletDesc: "สลับ KAIRO เป็น USDT ทางเดียวพร้อมการเผ่าแบบฝืดตัว",
      poolUsdt: "USDT ในพูล",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "การสลับรวมการเผ่าแบบฝืดตัว",
      youPay: "คุณจ่าย",
      youReceive: "คุณรับ (ประมาณการ)",
      rate: "อัตรา",
      fee: "ค่าธรรมเนียม ({percent}%)",
      minOutput: "ผลลัพธ์ขั้นต่ำ ({slippage}% สไลป์เพจ)",
      slippage: "สไลป์เพจ:",
      priceImpact: "ผลกระทบราคา",
      approveAndSwap: "อนุมัติ & สลับ",
      swapBtn: "สลับ KAIRO → USDT",
      max: "สูงสุด: {amount}"
    },
    referralNetwork: {
      title: "เครือข่ายผู้แนะนำ",
      rank: "ระดับ",
      directReferrals: "ผู้แนะนำโดยตรง",
      directActive: "{count} ใช้งาน",
      directBusiness: "ปริมาณโดยตรง",
      referralStakes: "สเตกผู้แนะนำ",
      teamBusiness: "ปริมาณทีม",
      totalDownlineVolume: "ปริมาณดาวน์ไลน์รวม",
      shareLink: "แชร์ลิงก์ของคุณเพื่อเชิญสมาชิกใหม่และรับค่าคอมมิชั่นหลายระดับ",
      earnDirect: "รับค่าคอมมิชั่นโดยตรง 5% + เงินปันผลทีม 15 ระดับจากทุกสเตกผู้แนะนำ"
    },
    rankDividend: {
      title: "เงินปันผลระดับ",
      subtitle: "บรรลุระดับผ่านปริมาณทีมและรับรางวัลเงินเดือนเป็นคาบ",
      connectWalletTitle: "เชื่อมต่อกระเป๋าเงิน",
      rankChangeDetected: "ตรวจพบการเปลี่ยนระดับ: {from} → {to}",
      rankChangeDesc: "ตัวจับเวลาเงินเดือนของคุณจะรีเซ็ตเมื่อยืนยัน คลิกด้านล่างเพื่ออัปเดตระดับของคุณ",
      updateRank: "อัปเดตระดับ",
      currentRank: "ระดับปัจจุบัน",
      rankLevel: "เลเวล {level} / 10",
      rankSalary: "เงินเดือนระดับ",
      perPeriod: "ต่อช่วง",
      harvestable: "เก็บเกี่ยวได้",
      crystallized: "ตกผลึกแล้ว",
      harvested: "เก็บเกี่ยวแล้ว",
      totalClaimed: "รับรวม",
      rankProgress: "ความคืบหน้าระดับ",
      earningPerPeriod: "รับ ${amount} / ช่วง",
      pending: "รอดำเนินการ: ${amount} · คลิกซิงค์เพื่อตกผลึก",
      syncRankChange: "ซิงค์การเปลี่ยนระดับ",
      syncRankSalary: "ซิงค์เงินเดือนระดับ (+${amount})",
      nothingToSync: "ไม่มีอะไรต้องซิงค์",
      harvestBtn: "เก็บเกี่ยว ${amount}",
      nothingToHarvest: "ไม่มีอะไรเก็บเกี่ยว",
      teamVolumeTitle: "ปริมาณทีม",
      totalTeamVolume: "ปริมาณทีมรวม",
      next: "ถัดไป: {rank}",
      targetMet: "บรรลุเป้าหมาย!",
      needMoreVolume: "ต้องการปริมาณที่ผ่านเกณฑ์อีก ${amount}",
      progressAchieved: "บรรลุ {percent}%",
      directReferrals: "ผู้แนะนำโดยตรง",
      activeDirects: "ผู้แนะนำโดยตรงที่ใช้งาน",
      unlockedLevels: "ระดับที่ปลดล็อก",
      harvestIncomeTitle: "รายได้จากการเก็บเกี่ยว",
      direct: "โดยตรง",
      team: "ทีม",
      rank: "ระดับ",
      harvest: "เก็บเกี่ยว",
      fiftyPctCapRule: "กฎขีดจำกัด 50% ต่อสาย",
      fiftyPctDesc: "สำหรับเป้าหมายระดับแต่ละอัน สูงสุด 50% ของเกณฑ์ระดับนั้นสามารถนับจากสายเดียวได้ ปริมาณส่วนตัวของคุณไม่นับสำหรับการผ่านเกณฑ์ระดับ แม้สายเดียวมีปริมาณมหาศาล จะนับเพียง 50% ของเป้าหมายระดับเท่านั้น",
      totalTeamVolumeLabel: "ปริมาณทีมรวม",
      largestLeg: "สายใหญ่สุด",
      numberOfLegs: "จำนวนสาย",
      qualifyingVolume: "ปริมาณที่ผ่านเกณฑ์",
      legVolumeBreakdown: "รายละเอียดปริมาณต่อสาย",
      leg: "สาย {index}",
      maxCredited: "(สูงสุด ${amount})",
      rankTargetsTitle: "เป้าหมายและเงินเดือนระดับ",
      rankCol: "ระดับ",
      teamVolumeTargetCol: "เป้าหมายปริมาณทีม",
      salaryCol: "เงินเดือน / ช่วง",
      progressCol: "ความคืบหน้า",
      statusCol: "สถานะ",
      achieved: "บรรลุ",
      nextTarget: "เป้าหมายถัดไป",
      locked: "ล็อก",
      salaryHistoryTitle: "ประวัติเงินเดือน",
      records: "{count} รายการ",
      loadingHistory: "กำลังโหลดประวัติ...",
      noSalaryHistory: "ยังไม่มีประวัติเงินเดือน บรรลุระดับเพื่อเริ่มรับรายได้!",
      typeCol: "ประเภท",
      dateCol: "วันที่",
      amountCol: "จำนวน",
      txCol: "ทรานแซคชั่น",
      salaryCredited: "เงินเดือนเข้าบัญชี",
      harvestedLabel: "เก็บเกี่ยวแล้ว"
    },
    teamDividend: {
      title: "เงินปันผลทีม",
      subtitle: "รับรายได้จากกำไรทบต้นทีม 15 ระดับ ตามจำนวนผู้แนะนำโดยตรงของคุณ ผู้ใช้ที่ไม่ใช้งานในสายโซ่จะถูกข้าม — เฉพาะผู้ถือสเตกที่ใช้งานเท่านั้นที่นับเป็นระดับ",
      connectWalletTitle: "เชื่อมต่อกระเป๋าเงิน",
      connectWalletDesc: "ดูรายได้เงินปันผลทีมของคุณ",
      unlockedLevels: "ระดับที่ปลดล็อก",
      directReferrals: "ผู้แนะนำโดยตรง",
      moreForNext: "ต้องการอีก {count} สำหรับระดับถัดไป",
      maxLevelsUnlocked: "ปลดล็อกระดับสูงสุดแล้ว",
      directBusiness: "ปริมาณโดยตรง",
      referralStakes: "สเตกผู้แนะนำ",
      teamVolume: "ปริมาณทีม",
      totalDownlineVolume: "ปริมาณดาวน์ไลน์รวม",
      teamDividend: "เงินปันผลทีม",
      harvest: "เก็บเกี่ยว",
      activeLabel: "ใช้งาน",
      levelBreakdownTitle: "รายละเอียดระดับ — ข้อมูลครบถ้วน",
      levelBreakdownDesc: "แต่ละระดับรับเปอร์เซ็นต์ของกำไรทบต้นที่สร้างโดยผู้ใช้ที่ใช้งานที่ความลึกอัดแน่นนั้น ผู้ใช้ที่ไม่ใช้งานจะถูกข้าม — ไม่นับเป็นระดับ L1: 10%, L2-L10: 5% ต่อระดับ, L11-L15: 2% ต่อระดับ ปลดล็อกระดับโดยเพิ่มผู้แนะนำโดยตรง: 1-5 คน = 1-5 ระดับ จากนั้นผู้แนะนำเพิ่มเติม = 2 ระดับ (สูงสุด 15 ที่ 10 คน)",
      levelCol: "ระดับ",
      rateCol: "อัตรา",
      membersCol: "สมาชิก",
      businessCol: "ปริมาณ",
      earnedCol: "ได้รับ",
      statusCol: "สถานะ",
      statusActive: "ใช้งาน",
      statusNext: "ถัดไป",
      statusLocked: "ล็อก",
      total: "รวม",
      levelLabel: "ระดับ {level}",
      directsNeeded: "{count} โดยตรง",
      levelActivationTracker: "ติดตามการเปิดใช้งานระดับ",
      levelActivationDesc: "คุณมีผู้แนะนำโดยตรง {directs} คน ปลดล็อก {unlocked} / 15 ระดับเงินปันผลทีม",
      ppl: "คน",
      legs: "{count} สาย",
      legVolumeBreakdown: "รายละเอียดปริมาณต่อสาย",
      legVolumeDesc: "ผู้แนะนำโดยตรงแต่ละคนสร้าง \"สาย\" หนึ่ง ปริมาณดาวน์สตรีมรวมของพวกเขามีส่วนร่วมในปริมาณทีมและการผ่านเกณฑ์ระดับของคุณ",
      refCol: "ผู้แนะนำ",
      selfStakeCol: "สเตกตัวเอง",
      legVolumeCol: "ปริมาณสาย",
      shareCol: "สัดส่วน",
      howItWorks: "วิธีการทำงานของเงินปันผลทีม",
      how1: "เมื่อผู้ใช้ใดในทีมของคุณทบต้นสเตก จะสร้างกำไร (0.15% ต่อช่วงเวลา)",
      how2: "คุณรับเปอร์เซ็นต์ของกำไรนั้นตามระดับ: L1=10%, L2-L10=5%, L11-L15=2%",
      how3: "ต้องมีสเตกที่ใช้งานและเนื้อที่ขีดจำกัด FIFO รายได้จำกัดที่ 3X ของสเตกรวมของคุณ"
    },
    cms: {
      subtitle: "ซื้อสมาชิก CMS และรับรางวัล KAIRO",
      connectWalletTitle: "สมาชิกหลัก",
      notAvailable: "CMS ไม่พร้อมใช้งาน",
      notAvailableDesc: "สัญญาสมาชิกหลักยังไม่ถูกปรับใช้",
      yourSubscriptions: "การสมัครของคุณ",
      remainingSlots: "ช่องคงเหลือ",
      subscriptionStatus: "สถานะการสมัคร",
      active: "ใช้งาน",
      ended: "สิ้นสุด",
      purchaseSubscription: "ซื้อการสมัคร",
      subscriptionEnded: "ระยะเวลาสมัครสมาชิกสิ้นสุดแล้ว",
      numberOfSubscriptions: "จำนวนการสมัคร",
      enterAmount: "ป้อนจำนวน...",
      subscriptionDetails: "รายละเอียดการสมัคร",
      pricePerSub: "ราคาต่อการสมัคร:",
      loyaltyRewardPerSub: "รางวัลความภักดีต่อการสมัคร:",
      totalCost: "ค่าใช้จ่ายรวม:",
      youllEarn: "คุณจะได้รับ:",
      approveUsdt: "อนุมัติ USDT",
      subscribeBtn: "สมัคร ({cost} USDT)",
      completeRegistrationFirst: "กรุณาสมัครสมาชิกให้เสร็จสิ้นก่อน",
      claimRewards: "รับรางวัล",
      alreadyClaimed: "คุณรับรางวัลไปแล้ว",
      loyaltyRewards: "รางวัลความภักดี",
      leadershipRewards: "รางวัลผู้นำ",
      totalClaimable: "รับได้รวม",
      claimRules: "กฎการรับ",
      claimRule1: "รับครั้งเดียวเท่านั้น (ใช้หรือหมดสิทธิ์)",
      claimRule2: "ต้องมีสเตกที่ใช้งานใน StakingManager",
      claimRule3: "จำกัดด้วยมูลค่าสเตกที่ใช้งาน (ส่วนเกินถูกลบ)",
      claimRule4: "90% ถูกสร้างให้คุณ, 10% ฝืดตัว (ไม่ถูกสร้าง)",
      excessWarning: "คำเตือน: {amount} KAIRO จะถูกลบถาวร (เกินขีดจำกัดสเตก)",
      maxClaimable: "รับได้สูงสุด (ตามสเตก):",
      claimRewardsBtn: "รับรางวัล",
      leadershipRewardsTitle: "รางวัลผู้นำ (5 ระดับ)",
      levelCol: "ระดับ",
      requiredDirectsCol: "ผู้แนะนำโดยตรงที่ต้องการ",
      rewardPerSubCol: "รางวัล/การสมัคร",
      subscriptionsCol: "การสมัคร",
      earnedCol: "ได้รับ (KAIRO)",
      levelLabel: "ระดับ {level}",
      howCmsWorks: "วิธีการทำงานของ CMS",
      subscriptionBenefits: "สิทธิประโยชน์การสมัคร",
      benefit1: "10 USDT ต่อการสมัคร (สูงสุด 10,000 รวม)",
      benefit2: "รับ 5 KAIRO รางวัลความภักดีต่อการสมัคร",
      benefit3: "รับรางวัลผู้นำจาก 5 ระดับผู้แนะนำ",
      benefit4: "รับครั้งเดียวพร้อมสเตกที่ใช้งาน (ใช้หรือหมดสิทธิ์)",
      referralRewards: "รางวัลผู้แนะนำ",
      level1Desc: "1 KAIRO ต่อการสมัคร (ไม่ต้องมีผู้แนะนำโดยตรง)",
      level2Desc: "0.5 KAIRO ต่อการสมัคร (ต้องมี 2 ผู้แนะนำโดยตรง)",
      level3Desc: "0.5 KAIRO ต่อการสมัคร (ต้องมี 3 ผู้แนะนำโดยตรง)",
      level4Desc: "0.25 KAIRO ต่อการสมัคร (ต้องมี 4 ผู้แนะนำโดยตรง)",
      level5Desc: "0.25 KAIRO ต่อการสมัคร (ต้องมี 5 ผู้แนะนำโดยตรง)",
      level1: "ระดับ 1:",
      level2: "ระดับ 2:",
      level3: "ระดับ 3:",
      level4: "ระดับ 4:",
      level5: "ระดับ 5:"
    },
    analytics: {
      title: "การวิเคราะห์โปรโตคอล",
      subtitle: "สถิติระบบนิเวศ KAIRO แบบเรียลไทม์",
      kairoPrice: "ราคา KAIRO",
      marketCap: "มูลค่าตลาด",
      poolLiquidityUsdt: "สภาพคล่องพูล (USDT)",
      totalBurned: "เผ่ารวม",
      tokenSupply: "ปริมาณโทเคน",
      deflationaryNote: "กลไกฝืดตัวผ่านการเผ่า",
      circulating: "หมุนเวียน",
      burned: "เผ่าแล้ว",
      effectiveSupply: "ปริมาณโทเคนที่มีผล",
      socialLock: "ล็อกสังคม",
      burnRate: "อัตราการเผ่า",
      liquidityPool: "พูลสภาพคล่อง",
      dexPoolComposition: "องค์ประกอบพูล DEX",
      kairoInPool: "KAIRO ในพูล",
      usdtInPool: "USDT ในพูล",
      pricePerSupply: "ราคา (USDT / ปริมาณโทเคนรวม)"
    },
    portfolio: {
      totalPortfolioValue: "มูลค่าพอร์ตโฟลิโอรวม",
      activeStakes: "สเตกที่ใช้งาน",
      totalStaked: "สเตกรวม",
      totalEarned: "รับรวม",
      remainingCapping: "ขีดจำกัดคงเหลือ",
      kairoPrice: "ราคา KAIRO",
      poolLiquidity: "สภาพคล่องพูล",
      totalCirculation: "หมุนเวียนรวม",
      harvestableAffiliate: "เก็บเกี่ยวได้ (แนะนำ)",
      activeDirects: "ผู้แนะนำโดยตรงที่ใช้งาน"
    },
    activeStakesTable: {
      title: "สเตกที่ใช้งาน",
      loading: "กำลังโหลดสเตก...",
      empty: "ไม่มีสเตกที่ใช้งาน เริ่มสเตกเพื่อรับรางวัล!",
      tierCount: "{count} ระดับ",
      stakeCount: "{count} สเตก",
      stakedAmount: "จำนวนสเตก",
      capProgress: "ความคืบหน้าขีดจำกัด 3X",
      harvestable: "เก็บเกี่ยวได้",
      harvested: "เก็บเกี่ยวแล้ว",
      totalEarned: "รับรวม",
      pendingCompoundProfit: "กำไรทบต้นรอดำเนินการ",
      autoCompound: "ทบต้นอัตโนมัติ",
      autoCompoundBtn: "ทบต้นอัตโนมัติ ({count})",
      accruing: "สะสม",
      harvest: "เก็บเกี่ยว ${amount}",
      minHarvestStake: "ขั้นต่ำ $10/สเตก",
      minHarvestAmount: "ขั้นต่ำ $10",
      intervals: "ช่วงเวลา"
    },
    income: {
      title: "สรุปรายได้",
      typesCount: "{count} ประเภท",
      direct: "ค่าคอมมิชั่นโดยตรง",
      team: "เงินปันผลทีม",
      rank: "เงินเดือนระดับ",
      harvest: "เก็บเกี่ยว",
      pendingHarvest: "เก็บเกี่ยวรอดำเนินการ",
      affiliateHarvested: "แนะนำที่เก็บเกี่ยวแล้ว",
      directLabel: "โดยตรง",
      teamLabel: "ทีม",
      rankLabel: "ระดับ",
      stakingEarnings: "รายได้สเตก",
      harvestedLabel: "เก็บเกี่ยวแล้ว",
      harvestableLabel: "เก็บเกี่ยวได้"
    },
    faucet: {
      testnetFaucet: "ก๊อก Testnet · USDT จำลอง",
      mintDesc: "สร้าง USDT ทดสอบสำหรับการพัฒนา ยอดคงเหลือปัจจุบัน:",
      mint10000: "สร้าง 10,000 USDT",
      mint: "สร้าง",
      customPlaceholder: "กำหนดเอง",
      mintingPending: "กำลังสร้าง USDT ทดสอบ…",
      mintingDesc: "ส่ง {amount} USDT ไปยังกระเป๋าเงินของคุณ",
      mintedSuccess: "สร้าง {amount} USDT ทดสอบแล้ว",
      mintFailed: "การสร้างล้มเหลว",
      invalidAmount: "จำนวนไม่ถูกต้อง"
    },
    common: {
      connectWalletTitle: "เชื่อมต่อกระเป๋าเงินของคุณ",
      connectWalletDesc: "เชื่อมต่อกระเป๋าเงินเพื่อดูพอร์ตโฟลิโอ จัดการสเตก และติดตามรายได้"
    }
  },

  ms: {
    staking: {
      connectWalletTitle: "Hubungkan dompet untuk stake",
      closingInterval: "selang penutupan",
      newStake: "Stake Baharu",
      amount: "Jumlah (USDT)",
      amountPlaceholder: "Masukkan jumlah...",
      balanceHelper: "Baki: {balance} USDT | Min: 10 USDT | Tiada Had Maksimum",
      autoCompoundEvery: "Auto-compound setiap {interval}",
      approveAndStake: "Lulus & Stake ${amount}",
      stakeBtn: "Stake ${amount}",
      yourStakes: "Stake Anda",
      active: "aktif",
      noActiveStakesDesc: "Belum ada stake aktif. Cipta stake pertama anda untuk mula mendapat!",
      stakeCount: "{count} stake",
      totalStaked: "Jumlah Staked",
      tierHeader: "Had 3X",
      pendingCompoundProfit: "Keuntungan compound tertunggu",
      autoCompoundBtn: "Auto-compound ({count})",
      accruing: "Berkembang",
      harvestBtn: "Tuai ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      total: "jumlah",
      tierCol: "Tahap",
      stakedCol: "Staked",
      earnedCol: "Diperoleh",
      harvestedCol: "Dituai",
      capCol: "Had 3X",
      startedCol: "Bermula",
      statusCol: "Status",
      actionCol: "Tindakan",
      statusActive: "Aktif",
      statusCapped: "Had Cap",
      statusClosed: "Tertutup",
      unstake: "Unstake",
      unstakeConfirm: "Unstake #{index}?\n\nAnda telah staked ${original} USDT.\nAnda akan menerima ~${preview} dalam KAIRO\n(80% daripada prinsipal, tolak sebarang pendapatan diperoleh tertunggu).\n\nTindakan ini tidak boleh diundur. Teruskan?",
      calcTitle: "Kalkulator Compound",
      calcSubtitle: "Unjur pengumpulan keuntungan berpotensi dari masa ke masa",
      calcStakeAmount: "Jumlah Stake (USDT)",
      calcEnterAmount: "Masukkan jumlah stake...",
      calcDuration: "Tempoh: {count} bulan",
      calcProjectedProfit: "Keuntungan Dijangka",
      calcTier: "Tahap",
      calcFrequency: "Frekuensi",
      calcCompounds: "Compound",
      calcNote: "0.15% setiap compound · Tahap & frekuensi autoikesan dari jumlah",
      levelUnlockTitle: "Buka Kunci Tahap Dividen Pasukan",
      levelUnlockDesc: "Buka lebih banyak tahap dividen pasukan dengan menambah rujukan langsung. Anda mempunyai {count} rujukan langsung dan {unlocked} / 15 tahap dibuka kunci.",
      directs: "langsung",
      intervals: "selang"
    },
    p2p: {
      subtitle: "Perdagangan KAIRO peer-to-peer atomik",
      connectWalletTitle: "Hubungkan dompet untuk berdagang",
      connectWalletDesc: "Akses perdagangan KAIRO peer-to-peer",
      dexPrice: "Harga DEX",
      vol: "vol",
      noActiveBuyOrders: "Tiada pesanan beli aktif",
      noActiveSellOrders: "Tiada pesanan jual aktif",
      fill: "Isi",
      enterAmount: "Masukkan jumlah...",
      usdtAmount: "Jumlah USDT",
      kairoAmount: "Jumlah KAIRO",
      max: "MAKS: {amount}",
      balanceLabel: "Baki: {amount} {token}",
      dexReferencePrice: "Harga Rujukan DEX",
      tradingFee: "Yuran Perdagangan",
      estimated: "Anggaran {token}",
      approveAndCreateBuy: "Lulus & Cipta Pesanan Beli",
      createBuyOrder: "Cipta Pesanan Beli",
      approveAndCreateSell: "Lulus & Cipta Pesanan Jual",
      createSellOrder: "Cipta Pesanan Jual",
      noActiveOrders: "Anda tiada pesanan aktif.",
      noActiveOrdersDesc: "Cipta pesanan beli atau jual untuk bermula.",
      myBuyOrders: "Pesanan Beli Saya",
      mySellOrders: "Pesanan Jual Saya",
      cancel: "Batal",
      remaining: "${amount} baki",
      filledOfTotal: "${filled} diisi daripada ${total} jumlah",
      kairoRemaining: "{amount} KAIRO baki"
    },
    swap: {
      title: "Swap",
      subtitle: "Swap sehala dengan yuran {fee}% dan bakar deflasi",
      connectWalletTitle: "Hubungkan dompet untuk swap",
      connectWalletDesc: "Swap KAIRO ke USDT sehala dengan bakar deflasi",
      poolUsdt: "USDT Pool",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap termasuk bakar deflasi",
      youPay: "Anda Bayar",
      youReceive: "Anda Terima (anggaran)",
      rate: "Kadar",
      fee: "Yuran ({percent}%)",
      minOutput: "Output Min ({slippage}% slippage)",
      slippage: "Slippage:",
      priceImpact: "Kesan Harga",
      approveAndSwap: "Lulus & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "MAKS: {amount}"
    },
    referralNetwork: {
      title: "Rangkaian Rujukan",
      rank: "Pangkat",
      directReferrals: "Rujukan Langsung",
      directActive: "{count} aktif",
      directBusiness: "Perdagangan Langsung",
      referralStakes: "stake rujukan",
      teamBusiness: "Perdagangan Pasukan",
      totalDownlineVolume: "jumlah volum downline",
      shareLink: "Kongsi pautan anda untuk menjemput ahli baharu dan memperoleh komisen berbilang tahap.",
      earnDirect: "Peroleh 5% komisen langsung + dividen pasukan 15 tahap pada setiap stake rujukan."
    },
    rankDividend: {
      title: "Dividen Pangkat",
      subtitle: "Capai pangkat melalui volum pasukan dan peroleh ganjaran gaji berkala",
      connectWalletTitle: "Hubungkan Dompet",
      rankChangeDetected: "Perubahan Pangkat Dikesan: {from} → {to}",
      rankChangeDesc: "Pemasa gaji anda akan diset semula apabila anda mengesahkan. Klik di bawah untuk mengemas kini pangkat anda.",
      updateRank: "Kemas Kini Pangkat",
      currentRank: "Pangkat Semasa",
      rankLevel: "Tahap {level} / 10",
      rankSalary: "Gaji Pangkat",
      perPeriod: "setiap tempoh",
      harvestable: "Boleh Dituai",
      crystallized: "hablur",
      harvested: "Dituai",
      totalClaimed: "jumlah dituntut",
      rankProgress: "Kemajuan Pangkat",
      earningPerPeriod: "Memperoleh ${amount} / tempoh",
      pending: "Tertunggu: ${amount} · klik Sync untuk menghablur",
      syncRankChange: "Sync Perubahan Pangkat",
      syncRankSalary: "Sync Gaji Pangkat (+${amount})",
      nothingToSync: "Tiada untuk Sync",
      harvestBtn: "Tuai ${amount}",
      nothingToHarvest: "Tiada untuk Dituai",
      teamVolumeTitle: "Volum Pasukan",
      totalTeamVolume: "Jumlah Volum Pasukan",
      next: "Seterusnya: {rank}",
      targetMet: "Sasaran tercapai!",
      needMoreVolume: "Perlu ${amount} lagi volum yang layak",
      progressAchieved: "{percent}% tercapai",
      directReferrals: "Rujukan Langsung",
      activeDirects: "Langsung Aktif",
      unlockedLevels: "Tahap Dibuka Kunci",
      harvestIncomeTitle: "Pendapatan Tuai",
      direct: "Langsung",
      team: "Pasukan",
      rank: "Pangkat",
      harvest: "Tuai",
      fiftyPctCapRule: "Peraturan Had 50% Setiap Kaki",
      fiftyPctDesc: "Untuk setiap sasaran pangkat, maksimum 50% daripada ambang pangkat tersebut boleh dikreditkan daripada mana-mana satu kaki. Volum peribadi anda tidak dikira untuk kelayakan pangkat. Walaupun satu kaki mempunyai volum besar, hanya 50% sasaran pangkat akan dikreditkan.",
      totalTeamVolumeLabel: "Jumlah Volum Pasukan",
      largestLeg: "Kaki Terbesar",
      numberOfLegs: "Bilangan Kaki",
      qualifyingVolume: "Volum Layak",
      legVolumeBreakdown: "Pecahan Volum Kaki",
      leg: "Kaki {index}",
      maxCredited: "(maks ${amount})",
      rankTargetsTitle: "Sasaran & Gaji Pangkat",
      rankCol: "Pangkat",
      teamVolumeTargetCol: "Sasaran Volum Pasukan",
      salaryCol: "Gaji / Tempoh",
      progressCol: "Kemajuan",
      statusCol: "Status",
      achieved: "Tercapai",
      nextTarget: "Sasaran Seterusnya",
      locked: "Terkunci",
      salaryHistoryTitle: "Sejarah Gaji",
      records: "{count} rekod",
      loadingHistory: "Memuatkan sejarah...",
      noSalaryHistory: "Tiada sejarah gaji lagi. Capai pangkat untuk mula memperoleh!",
      typeCol: "Jenis",
      dateCol: "Tarikh",
      amountCol: "Jumlah",
      txCol: "Tx",
      salaryCredited: "Gaji Dikreditkan",
      harvestedLabel: "Dituai"
    },
    teamDividend: {
      title: "Dividen Pasukan",
      subtitle: "Peroleh daripada 15 tahap keuntungan compound pasukan berdasarkan bilangan rujukan langsung anda. Pengguna tidak aktif dalam rantai dilangkau — hanya pemegang stake aktif dikira sebagai tahap.",
      connectWalletTitle: "Hubungkan Dompet",
      connectWalletDesc: "Lihat pendapatan dividen pasukan anda",
      unlockedLevels: "Tahap Dibuka Kunci",
      directReferrals: "Rujukan Langsung",
      moreForNext: "{count} lagi untuk tahap seterusnya",
      maxLevelsUnlocked: "Tahap maksimum dibuka kunci",
      directBusiness: "Perdagangan Langsung",
      referralStakes: "Stake Rujukan",
      teamVolume: "Volum Pasukan",
      totalDownlineVolume: "Jumlah volum downline",
      teamDividend: "Dividen Pasukan",
      harvest: "Tuai",
      activeLabel: "aktif",
      levelBreakdownTitle: "Pecahan Tahap — Butiran Penuh",
      levelBreakdownDesc: "Setiap tahap memperoleh peratusan keuntungan compound yang dijana oleh pengguna aktif pada kedalaman termampat itu. Pengguna tidak aktif dilangkau — mereka tidak dikira sebagai tahap. L1: 10%, L2-L10: 5% setiap satu, L11-L15: 2% setiap satu. Buka kunci tahap dengan menambah rujukan langsung: 1-5 langsung = 1-5 tahap, kemudian setiap langsung tambahan = 2 tahap lagi (maks 15 pada 10 langsung).",
      levelCol: "Tahap",
      rateCol: "Kadar",
      membersCol: "Ahli",
      businessCol: "Perdagangan",
      earnedCol: "Diperoleh",
      statusCol: "Status",
      statusActive: "Aktif",
      statusNext: "Seterusnya",
      statusLocked: "Terkunci",
      total: "Jumlah",
      levelLabel: "Tahap {level}",
      directsNeeded: "{count} langsung",
      levelActivationTracker: "Penjejak Pengaktifan Tahap",
      levelActivationDesc: "Anda mempunyai {directs} rujukan langsung, membuka kunci {unlocked} / 15 tahap dividen pasukan.",
      ppl: "org",
      legs: "{count} kaki",
      legVolumeBreakdown: "Pecahan Volum Kaki",
      legVolumeDesc: "Setiap rujukan langsung membentuk \"kaki\". Jumlah volum hilir mereka menyumbang kepada volum pasukan dan kelayakan pangkat anda.",
      refCol: "Rujukan",
      selfStakeCol: "Stake Sendiri",
      legVolumeCol: "Volum Kaki",
      shareCol: "Syer",
      howItWorks: "Cara Dividen Pasukan Berfungsi",
      how1: "Apabila mana-mana pengguna dalam pasukan anda compound stake mereka, keuntungan dijana (0.15% setiap selang).",
      how2: "Anda memperoleh peratusan keuntungan itu berdasarkan tahap: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Memerlukan stake aktif dan ruang had FIFO. Pendapatan dihadkan pada 3X jumlah stake anda."
    },
    cms: {
      subtitle: "Beli langganan CMS dan peroleh ganjaran KAIRO",
      connectWalletTitle: "Keahlian Teras",
      notAvailable: "CMS Tidak Tersedia",
      notAvailableDesc: "Kontrak Langganan Keahlian Teras belum digunakan.",
      yourSubscriptions: "Langganan Anda",
      remainingSlots: "Slot Baki",
      subscriptionStatus: "Status Langganan",
      active: "Aktif",
      ended: "Tamat",
      purchaseSubscription: "Beli Langganan",
      subscriptionEnded: "Tempoh langganan telah tamat",
      numberOfSubscriptions: "Bilangan Langganan",
      enterAmount: "Masukkan jumlah...",
      subscriptionDetails: "Butiran Langganan",
      pricePerSub: "Harga setiap langganan:",
      loyaltyRewardPerSub: "Ganjaran kesetiaan setiap langganan:",
      totalCost: "Jumlah kos:",
      youllEarn: "Anda akan peroleh:",
      approveUsdt: "Lulus USDT",
      subscribeBtn: "Langgan ({cost} USDT)",
      completeRegistrationFirst: "Sila lengkapkan pendaftaran terlebih dahulu",
      claimRewards: "Tuntut Ganjaran",
      alreadyClaimed: "Anda telah menuntut ganjaran anda",
      loyaltyRewards: "Ganjaran Kesetiaan",
      leadershipRewards: "Ganjaran Kepimpinan",
      totalClaimable: "Jumlah Boleh Tuntut",
      claimRules: "Peraturan Tuntutan",
      claimRule1: "Tuntutan sekali sahaja (guna atau hilang)",
      claimRule2: "Memerlukan stake aktif dalam StakingManager",
      claimRule3: "Dihadkan oleh nilai stake aktif (lebihan dipadam)",
      claimRule4: "90% dimintakan kepada anda, 10% deflasi (tidak dimintakan)",
      excessWarning: "Amaran: {amount} KAIRO akan dipadam secara kekal (melebihi had stake)",
      maxClaimable: "Maksimum boleh dituntut (berdasarkan stake):",
      claimRewardsBtn: "Tuntut Ganjaran",
      leadershipRewardsTitle: "Ganjaran Kepimpinan (5 Tahap)",
      levelCol: "Tahap",
      requiredDirectsCol: "Langsung Diperlukan",
      rewardPerSubCol: "Ganjaran/Langganan",
      subscriptionsCol: "Langganan",
      earnedCol: "Diperoleh (KAIRO)",
      levelLabel: "Tahap {level}",
      howCmsWorks: "Cara CMS Berfungsi",
      subscriptionBenefits: "Manfaat Langganan",
      benefit1: "10 USDT setiap langganan (maks 10,000 jumlah)",
      benefit2: "Peroleh 5 KAIRO ganjaran kesetiaan setiap langganan",
      benefit3: "Peroleh ganjaran kepimpinan daripada 5 tahap rujukan",
      benefit4: "Tuntut sekali dengan stake aktif (guna atau hilang)",
      referralRewards: "Ganjaran Rujukan",
      level1Desc: "1 KAIRO setiap langganan (0 langsung diperlukan)",
      level2Desc: "0.5 KAIRO setiap langganan (2 langsung diperlukan)",
      level3Desc: "0.5 KAIRO setiap langganan (3 langsung diperlukan)",
      level4Desc: "0.25 KAIRO setiap langganan (4 langsung diperlukan)",
      level5Desc: "0.25 KAIRO setiap langganan (5 langsung diperlukan)",
      level1: "Tahap 1:",
      level2: "Tahap 2:",
      level3: "Tahap 3:",
      level4: "Tahap 4:",
      level5: "Tahap 5:"
    },
    analytics: {
      title: "Analitik Protokol",
      subtitle: "Statistik ekosistem KAIRO masa nyata",
      kairoPrice: "Harga KAIRO",
      marketCap: "Kapital Pasaran",
      poolLiquidityUsdt: "Kecairan Pool (USDT)",
      totalBurned: "Jumlah Dibakar",
      tokenSupply: "Bekalan Token",
      deflationaryNote: "Mekanisme deflasi melalui bakar",
      circulating: "Beredaran",
      burned: "Dibakar",
      effectiveSupply: "Bekalan Berkesan",
      socialLock: "Kunci Sosial",
      burnRate: "Kadar Bakar",
      liquidityPool: "Pool Kecairan",
      dexPoolComposition: "Komposisi pool DEX",
      kairoInPool: "KAIRO dalam Pool",
      usdtInPool: "USDT dalam Pool",
      pricePerSupply: "Harga (USDT / Jumlah Bekalan)"
    },
    portfolio: {
      totalPortfolioValue: "Jumlah Nilai Portfolio",
      activeStakes: "Stake Aktif",
      totalStaked: "Jumlah Staked",
      totalEarned: "Jumlah Diperoleh",
      remainingCapping: "Baki Had",
      kairoPrice: "Harga KAIRO",
      poolLiquidity: "Kecairan Pool",
      totalCirculation: "Jumlah edaran",
      harvestableAffiliate: "Boleh Dituai (Afiliasi)",
      activeDirects: "Langsung Aktif"
    },
    activeStakesTable: {
      title: "Stake Aktif",
      loading: "Memuatkan stake...",
      empty: "Tiada stake aktif. Mulakan staking untuk memperoleh ganjaran!",
      tierCount: "{count} tahap",
      stakeCount: "{count} stake",
      stakedAmount: "Jumlah Staked",
      capProgress: "Kemajuan Had 3X",
      harvestable: "Boleh Dituai",
      harvested: "Dituai",
      totalEarned: "Jumlah Diperoleh",
      pendingCompoundProfit: "Keuntungan compound tertunggu",
      autoCompound: "Auto Compound",
      autoCompoundBtn: "Auto Compound ({count})",
      accruing: "Berkembang",
      harvest: "Tuai ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      intervals: "selang"
    },
    income: {
      title: "Ringkasan Pendapatan",
      typesCount: "{count} jenis",
      direct: "Komisen Langsung",
      team: "Dividen Pasukan",
      rank: "Gaji Pangkat",
      harvest: "Tuai",
      pendingHarvest: "Tuai Tertunggu",
      affiliateHarvested: "Afiliasi Dituai",
      directLabel: "Langsung",
      teamLabel: "Pasukan",
      rankLabel: "Pangkat",
      stakingEarnings: "Pendapatan Staking",
      harvestedLabel: "Dituai",
      harvestableLabel: "Boleh Dituai"
    },
    faucet: {
      testnetFaucet: "Paip Testnet · USDT Mock",
      mintDesc: "Cipta USDT ujian untuk pembangunan. Baki semasa:",
      mint10000: "Cipta 10,000 USDT",
      mint: "Cipta",
      customPlaceholder: "tersuai",
      mintingPending: "Mencipta USDT ujian…",
      mintingDesc: "Menghantar {amount} USDT ke dompet anda",
      mintedSuccess: "Telah mencipta {amount} USDT ujian",
      mintFailed: "Ciptaan gagal",
      invalidAmount: "Jumlah tidak sah"
    },
    common: {
      connectWalletTitle: "Hubungkan Dompet Anda",
      connectWalletDesc: "Hubungkan dompet anda untuk melihat portfolio, mengurus stake, dan menjejaki pendapatan."
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
