import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  it: {
    staking: {
      connectWalletTitle: "Collega il tuo wallet per lo staking",
      closingInterval: "intervallo di chiusura",
      newStake: "Nuovo Stake",
      amount: "Importo (USDT)",
      amountPlaceholder: "Inserisci importo...",
      balanceHelper: "Saldo: {balance} USDT | Min: 10 USDT | Nessun limite massimo",
      autoCompoundEvery: "Composizione automatica ogni {interval}",
      approveAndStake: "Approva & Stakka ${amount}",
      stakeBtn: "Stakka ${amount}",
      yourStakes: "I Tuoi Stake",
      active: "attivo",
      noActiveStakesDesc: "Nessuno stake attivo. Crea il tuo primo stake per iniziare a guadagnare!",
      stakeCount: "{count} stake",
      totalStaked: "Totale Stakkato",
      tierHeader: "Limite 3X",
      pendingCompoundProfit: "Profitto composizione in sospeso",
      autoCompoundBtn: "Composizione automatica ({count})",
      accruing: "In accumulo",
      harvestBtn: "Raccogli ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      total: "totale",
      tierCol: "Livello",
      stakedCol: "Stakkato",
      earnedCol: "Guadagnato",
      harvestedCol: "Raccolto",
      capCol: "Limite 3X",
      startedCol: "Iniziato",
      statusCol: "Stato",
      actionCol: "Azione",
      statusActive: "Attivo",
      statusCapped: "Al limite",
      statusClosed: "Chiuso",
      unstake: "Ritira",
      unstakeConfirm: "Ritirare lo stake #{index}?\n\nHai stakkato ${original} USDT.\nRiceverai ~${preview} in KAIRO\n(80% del capitale, meno eventuali redditi raccolti in sospeso).\n\nQuesta azione è irreversibile. Continuare?",
      calcTitle: "Calcolatore di Composizione",
      calcSubtitle: "Proietta l'accumulo potenziale dei profitti nel tempo",
      calcStakeAmount: "Importo Stake (USDT)",
      calcEnterAmount: "Inserisci importo stake...",
      calcDuration: "Durata: {count} mese{count, plural, =1 {} other {i}}",
      calcProjectedProfit: "Profitto Proiettato",
      calcTier: "Livello",
      calcFrequency: "Frequenza",
      calcCompounds: "Composizioni",
      calcNote: "0,15% per composizione · Livello e frequenza rilevati automaticamente dall'importo",
      levelUnlockTitle: "Sblocco Livello Dividendo di Squadra",
      levelUnlockDesc: "Sblocca più livelli di dividendo di squadra aggiungendo referral diretti. Attualmente hai {count} referral diretti e {unlocked} / 15 livelli sbloccati.",
      directs: "diretti",
      intervals: "intervalli"
    },
    p2p: {
      subtitle: "Trading KAIRO peer-to-peer atomico",
      connectWalletTitle: "Collega il tuo wallet per il trading",
      connectWalletDesc: "Accedi al trading KAIRO peer-to-peer",
      dexPrice: "Prezzo DEX",
      vol: "vol",
      noActiveBuyOrders: "Nessun ordine di acquisto attivo",
      noActiveSellOrders: "Nessun ordine di vendita attivo",
      fill: "Esegui",
      enterAmount: "Inserisci importo...",
      usdtAmount: "Importo USDT",
      kairoAmount: "Importo KAIRO",
      max: "MAX: {amount}",
      balanceLabel: "Saldo: {amount} {token}",
      dexReferencePrice: "Prezzo di Riferimento DEX",
      tradingFee: "Commissione di Trading",
      estimated: "{token} stimato",
      approveAndCreateBuy: "Approva & Crea Ordine di Acquisto",
      createBuyOrder: "Crea Ordine di Acquisto",
      approveAndCreateSell: "Approva & Crea Ordine di Vendita",
      createSellOrder: "Crea Ordine di Vendita",
      noActiveOrders: "Non hai ordini attivi.",
      noActiveOrdersDesc: "Crea un ordine di acquisto o vendita per iniziare.",
      myBuyOrders: "Miei Ordini di Acquisto",
      mySellOrders: "Miei Ordini di Vendita",
      cancel: "Annulla",
      remaining: "${amount} rimanente",
      filledOfTotal: "${filled} eseguito su ${total} totale",
      kairoRemaining: "{amount} KAIRO rimanente"
    },
    swap: {
      title: "Swap",
      subtitle: "Swap unidirezionale con commissione del {fee}% e burn deflazionario",
      connectWalletTitle: "Collega il tuo wallet per lo swap",
      connectWalletDesc: "Swap unidirezionale da KAIRO a USDT con burn deflazionario",
      poolUsdt: "USDT nel Pool",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Lo swap include un burn deflazionario",
      youPay: "Paghi",
      youReceive: "Ricevi (stimato)",
      rate: "Tasso",
      fee: "Commissione ({percent}%)",
      minOutput: "Output Min. ({slippage}% slippage)",
      slippage: "Slippage:",
      priceImpact: "Impatto sul Prezzo",
      approveAndSwap: "Approva & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "MAX: {amount}"
    },
    referralNetwork: {
      title: "Rete di Referral",
      rank: "Rango",
      directReferrals: "Referral Diretti",
      directActive: "{count} attivi",
      directBusiness: "Volume Diretto",
      referralStakes: "stake di referral",
      teamBusiness: "Volume Squadra",
      totalDownlineVolume: "volume totale downline",
      shareLink: "Condividi il tuo link per invitare nuovi membri e guadagnare commissioni multi-livello.",
      earnDirect: "Guadagna 5% commissione diretta + dividendi di squadra su 15 livelli per ogni stake di referral."
    },
    rankDividend: {
      title: "Dividendo di Rango",
      subtitle: "Raggiungi ranghi attraverso il volume di squadra e guadagna ricompense salariali periodiche",
      connectWalletTitle: "Collega il tuo wallet",
      rankChangeDetected: "Cambio di Rango Rilevato: {from} → {to}",
      rankChangeDesc: "Il tuo timer di salario sarà azzerato alla conferma. Clicca sotto per aggiornare il tuo rango.",
      updateRank: "Aggiorna Rango",
      currentRank: "Rango Attuale",
      rankLevel: "Livello {level} / 10",
      rankSalary: "Salario di Rango",
      perPeriod: "per periodo",
      harvestable: "Raccoglibile",
      crystallized: "cristallizzato",
      harvested: "Raccolto",
      totalClaimed: "totale richiesto",
      rankProgress: "Progresso Rango",
      earningPerPeriod: "Guadagno ${amount} / periodo",
      pending: "In sospeso: ${amount} · clicca Sincronizza per cristallizzare",
      syncRankChange: "Sincronizza Cambio Rango",
      syncRankSalary: "Sincronizza Salario Rango (+${amount})",
      nothingToSync: "Niente da Sincronizzare",
      harvestBtn: "Raccogli ${amount}",
      nothingToHarvest: "Niente da Raccogliere",
      teamVolumeTitle: "Volume Squadra",
      totalTeamVolume: "Volume Totale Squadra",
      next: "Successivo: {rank}",
      targetMet: "Obiettivo raggiunto!",
      needMoreVolume: "Servono altri ${amount} di volume qualificante",
      progressAchieved: "{percent}% raggiunto",
      directReferrals: "Referral Diretti",
      activeDirects: "Diretti Attivi",
      unlockedLevels: "Livelli Sbloccati",
      harvestIncomeTitle: "Reddito da Raccolta",
      direct: "Diretto",
      team: "Squadra",
      rank: "Rango",
      harvest: "Raccolta",
      fiftyPctCapRule: "Regola Limite 50% per Gamba",
      fiftyPctDesc: "Per ogni obiettivo di rango, un massimo del 50% della soglia di quel rango specifico può essere accreditato da una singola gamba. Il tuo volume personale non conta per la qualificazione del rango. Anche se una singola gamba ha un volume massiccio, solo il 50% dell'obiettivo di rango sarà accreditato.",
      totalTeamVolumeLabel: "Volume Totale Squadra",
      largestLeg: "Gamba Più Grande",
      numberOfLegs: "Numero di Gambe",
      qualifyingVolume: "Volume Qualificante",
      legVolumeBreakdown: "Dettaglio Volume per Gamba",
      leg: "Gamba {index}",
      maxCredited: "(max ${amount})",
      rankTargetsTitle: "Obiettivi e Salari di Rango",
      rankCol: "Rango",
      teamVolumeTargetCol: "Obiettivo Volume Squadra",
      salaryCol: "Salario / Periodo",
      progressCol: "Progresso",
      statusCol: "Stato",
      achieved: "Raggiunto",
      nextTarget: "Prossimo Obiettivo",
      locked: "Bloccato",
      salaryHistoryTitle: "Storico Salari",
      records: "{count} record",
      loadingHistory: "Caricamento storico...",
      noSalaryHistory: "Nessuno storico salari ancora. Raggiungi un rango per iniziare a guadagnare!",
      typeCol: "Tipo",
      dateCol: "Data",
      amountCol: "Importo",
      txCol: "Tx",
      salaryCredited: "Salario Accreditato",
      harvestedLabel: "Raccolto"
    },
    teamDividend: {
      title: "Dividendo di Squadra",
      subtitle: "Guadagna da 15 livelli di profitti composizione della squadra in base al tuo numero di referral diretti. Gli utenti inattivi nella catena vengono saltati — solo i partecipanti attivi contano come livelli.",
      connectWalletTitle: "Collega il tuo wallet",
      connectWalletDesc: "Visualizza i tuoi guadagni da dividendo di squadra",
      unlockedLevels: "Livelli Sbloccati",
      directReferrals: "Referral Diretti",
      moreForNext: "{count} di più per il prossimo livello",
      maxLevelsUnlocked: "Livelli massimi sbloccati",
      directBusiness: "Volume Diretto",
      referralStakes: "Stake di Referral",
      teamVolume: "Volume Squadra",
      totalDownlineVolume: "Volume totale downline",
      teamDividend: "Dividendo di Squadra",
      harvest: "Raccogli",
      activeLabel: "attivo",
      levelBreakdownTitle: "Dettaglio Livelli — Dettagli Completi",
      levelBreakdownDesc: "Ogni livello guadagna una percentuale dei profitti composizione generati dagli utenti attivi a quella profondità compressa. Gli utenti inattivi vengono saltati — non contano come livello. L1: 10%, L2-L10: 5% ciascuno, L11-L15: 2% ciascuno. Sblocca livelli aggiungendo referral diretti: 1-5 diretti = 1-5 livelli, poi ogni diretto aggiuntivo = 2 livelli in più (max 15 con 10 diretti).",
      levelCol: "Livello",
      rateCol: "Tasso",
      membersCol: "Membri",
      businessCol: "Volume",
      earnedCol: "Guadagnato",
      statusCol: "Stato",
      statusActive: "Attivo",
      statusNext: "Successivo",
      statusLocked: "Bloccato",
      total: "Totale",
      levelLabel: "Livello {level}",
      directsNeeded: "{count} dirett{count, plural, =1 {o} other {i}}",
      levelActivationTracker: "Tracker Attivazione Livelli",
      levelActivationDesc: "Hai {directs} referral diretti, sbloccando {unlocked} / 15 livelli di dividendo di squadra.",
      ppl: "pers.",
      legs: "{count} gambe",
      legVolumeBreakdown: "Dettaglio Volume per Gamba",
      legVolumeDesc: "Ogni referral diretto forma una \"gamba\". Il loro volume totale a valle contribuisce al tuo volume di squadra e alla qualificazione del rango.",
      refCol: "Referral",
      selfStakeCol: "Stake Proprio",
      legVolumeCol: "Volume Gamba",
      shareCol: "Quota",
      howItWorks: "Come Funzionano i Dividendi di Squadra",
      how1: "Quando qualsiasi utente nella tua squadra compone il proprio stake, viene generato profitto (0,15% per intervallo).",
      how2: "Guadagni una percentuale di quel profitto in base al livello: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Richiede stake attivo e spazio limite FIFO. I guadagni sono limitati a 3X del tuo stake totale."
    },
    cms: {
      subtitle: "Acquista abbonamenti CMS e guadagna ricompense KAIRO",
      connectWalletTitle: "Membreship Core",
      notAvailable: "CMS Non Disponibile",
      notAvailableDesc: "Il contratto di Abbonamento Core Membership non è ancora stato distribuito.",
      yourSubscriptions: "I Tuoi Abbonamenti",
      remainingSlots: "Slot Rimanenti",
      subscriptionStatus: "Stato Abbonamento",
      active: "Attivo",
      ended: "Terminato",
      purchaseSubscription: "Acquista Abbonamento",
      subscriptionEnded: "Il periodo di abbonamento è terminato",
      numberOfSubscriptions: "Numero di Abbonamenti",
      enterAmount: "Inserisci importo...",
      subscriptionDetails: "Dettagli Abbonamento",
      pricePerSub: "Prezzo per abbonamento:",
      loyaltyRewardPerSub: "Ricompensa fedeltà per abbonamento:",
      totalCost: "Costo totale:",
      youllEarn: "Guadagnerai:",
      approveUsdt: "Approva USDT",
      subscribeBtn: "Abbonati ({cost} USDT)",
      completeRegistrationFirst: "Completa prima la registrazione",
      claimRewards: "Richiedi Ricompense",
      alreadyClaimed: "Hai già richiesto le tue ricompense",
      loyaltyRewards: "Ricompense Fedeltà",
      leadershipRewards: "Ricompense Leadership",
      totalClaimable: "Totale Richiedibile",
      claimRules: "Regole di Richiesta",
      claimRule1: "Richiesta una tantum (usala o perdila)",
      claimRule2: "Richiede stake attivo in StakingManager",
      claimRule3: "Limitato dal valore dello stake attivo (l'eccesso viene eliminato)",
      claimRule4: "90% coniato per te, 10% deflazionario (non coniato)",
      excessWarning: "Avviso: {amount} KAIRO verranno eliminati permanentemente (supera il limite stake)",
      maxClaimable: "Max richiedibile (basato su stake):",
      claimRewardsBtn: "Richiedi Ricompense",
      leadershipRewardsTitle: "Ricompense Leadership (5 Livelli)",
      levelCol: "Livello",
      requiredDirectsCol: "Diretti Richiesti",
      rewardPerSubCol: "Ricompensa/Abbonamento",
      subscriptionsCol: "Abbonamenti",
      earnedCol: "Guadagnato (KAIRO)",
      levelLabel: "Livello {level}",
      howCmsWorks: "Come Funziona CMS",
      subscriptionBenefits: "Benefici Abbonamento",
      benefit1: "10 USDT per abbonamento (max 10.000 totali)",
      benefit2: "Guadagna 5 KAIRO ricompensa fedeltà per abbonamento",
      benefit3: "Guadagna ricompense leadership da 5 livelli di referral",
      benefit4: "Richiedi una volta con stake attivo (usala o perdila)",
      referralRewards: "Ricompense Referral",
      level1Desc: "1 KAIRO per abbonamento (0 diretti richiesti)",
      level2Desc: "0,5 KAIRO per abbonamento (2 diretti richiesti)",
      level3Desc: "0,5 KAIRO per abbonamento (3 diretti richiesti)",
      level4Desc: "0,25 KAIRO per abbonamento (4 diretti richiesti)",
      level5Desc: "0,25 KAIRO per abbonamento (5 diretti richiesti)",
      level1: "Livello 1:",
      level2: "Livello 2:",
      level3: "Livello 3:",
      level4: "Livello 4:",
      level5: "Livello 5:"
    },
    analytics: {
      title: "Analisi Protocollo",
      subtitle: "Statistiche ecosistema KAIRO in tempo reale",
      kairoPrice: "Prezzo KAIRO",
      marketCap: "Capitalizzazione di Mercato",
      poolLiquidityUsdt: "Liquidità Pool (USDT)",
      totalBurned: "Totale Bruciato",
      tokenSupply: "Offerta Token",
      deflationaryNote: "Meccanismi deflativi tramite burn",
      circulating: "In circolazione",
      burned: "Bruciato",
      effectiveSupply: "Offerta Effettiva",
      socialLock: "Social Lock",
      burnRate: "Tasso di Burn",
      liquidityPool: "Pool di Liquidità",
      dexPoolComposition: "Composizione pool DEX",
      kairoInPool: "KAIRO nel Pool",
      usdtInPool: "USDT nel Pool",
      pricePerSupply: "Prezzo (USDT / Offerta Totale)"
    },
    portfolio: {
      totalPortfolioValue: "Valore Totale Portafoglio",
      activeStakes: "Stake Attivi",
      totalStaked: "Totale Stakkato",
      totalEarned: "Totale Guadagnato",
      remainingCapping: "Limite Rimanente",
      kairoPrice: "Prezzo KAIRO",
      poolLiquidity: "Liquidità Pool",
      totalCirculation: "Circolazione Totale",
      harvestableAffiliate: "Raccoglibile (Affiliato)",
      activeDirects: "Diretti Attivi"
    },
    activeStakesTable: {
      title: "Stake Attivi",
      loading: "Caricamento stake...",
      empty: "Nessuno stake attivo. Inizia a stakkare per guadagnare ricompense!",
      tierCount: "{count} livello/i",
      stakeCount: "{count} stake",
      stakedAmount: "Importo Stakkato",
      capProgress: "Progresso Limite 3X",
      harvestable: "Raccoglibile",
      harvested: "Raccolto",
      totalEarned: "Totale Guadagnato",
      pendingCompoundProfit: "Profitto composizione in sospeso",
      autoCompound: "Composizione Automatica",
      autoCompoundBtn: "Composizione Automatica ({count})",
      accruing: "In accumulo",
      harvest: "Raccogli ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      intervals: "intervalli"
    },
    income: {
      title: "Riepilogo Redditi",
      typesCount: "{count} tipi",
      direct: "Commissione Diretta",
      team: "Dividendi Squadra",
      rank: "Salario Rango",
      harvest: "Raccolta",
      pendingHarvest: "Raccolta in Sospeso",
      affiliateHarvested: "Affiliato Raccolto",
      directLabel: "Diretto",
      teamLabel: "Squadra",
      rankLabel: "Rango",
      stakingEarnings: "Guadagni Staking",
      harvestedLabel: "Raccolto",
      harvestableLabel: "Raccoglibile"
    },
    faucet: {
      testnetFaucet: "Faucet Testnet · USDT Finto",
      mintDesc: "Crea USDT di test per lo sviluppo. Saldo attuale:",
      mint10000: "Crea 10.000 USDT",
      mint: "Crea",
      customPlaceholder: "personalizzato",
      mintingPending: "Creazione USDT di test…",
      mintingDesc: "Invio di {amount} USDT al tuo wallet",
      mintedSuccess: "Creati {amount} USDT di test",
      mintFailed: "Creazione fallita",
      invalidAmount: "Importo non valido"
    },
    common: {
      connectWalletTitle: "Collega il Tuo Wallet",
      connectWalletDesc: "Collega il tuo wallet per visualizzare il portafoglio, gestire gli stake e monitorare i guadagni."
    }
  },

  tr: {
    staking: {
      connectWalletTitle: "Staking için cüzdanınızı bağlayın",
      closingInterval: "kapanış aralığı",
      newStake: "Yeni Stake",
      amount: "Tutar (USDT)",
      amountPlaceholder: "Tutar girin...",
      balanceHelper: "Bakiye: {balance} USDT | Min: 10 USDT | Maks Sınır Yok",
      autoCompoundEvery: "Her {interval} otomatik bileşik",
      approveAndStake: "Onayla & Stake ${amount}",
      stakeBtn: "Stake ${amount}",
      yourStakes: "Stakeleriniz",
      active: "aktif",
      noActiveStakesDesc: "Henüz aktif stake yok. Kazanmaya başlamak için ilk stakenizi oluşturun!",
      stakeCount: "{count} stake",
      totalStaked: "Toplam Staked",
      tierHeader: "3X Sınır",
      pendingCompoundProfit: "Bekleyen bileşik kâr",
      autoCompoundBtn: "Otomatik Bileşik ({count})",
      accruing: "Birikiyor",
      harvestBtn: "Hasat ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      total: "toplam",
      tierCol: "Kademe",
      stakedCol: "Staked",
      earnedCol: "Kazanılan",
      harvestedCol: "Hasatlanan",
      capCol: "3X Sınır",
      startedCol: "Başladı",
      statusCol: "Durum",
      actionCol: "İşlem",
      statusActive: "Aktif",
      statusCapped: "Sınıra Ulaştı",
      statusClosed: "Kapalı",
      unstake: "Stake'i Kaldır",
      unstakeConfirm: "#{index} stake'i kaldır?\n\n${original} USDT stake ettiniz.\n~${preview} KAIRO alacaksınız\n(Anaparanın %80'i, bekleyen hasatlanmış gelir düşülür).\n\nBu işlem geri alınamaz. Devam edilsin mi?",
      calcTitle: "Bileşik Hesaplayıcı",
      calcSubtitle: "Zamanla potansiyel kâr birikimini öngörün",
      calcStakeAmount: "Stake Tutarı (USDT)",
      calcEnterAmount: "Stake tutarını girin...",
      calcDuration: "Süre: {count} ay",
      calcProjectedProfit: "Öngörülen Kâr",
      calcTier: "Kademe",
      calcFrequency: "Frekans",
      calcCompounds: "Bileşikler",
      calcNote: "Her bileşikte %0,15 · Kademe ve frekans tutardan otomatik algılanır",
      levelUnlockTitle: "Takım Temettü Seviye Kilidi Açma",
      levelUnlockDesc: "Doğrudan yönlendirmeler ekleyerek daha fazla takım temettü seviyesinin kilidini açın. Şu anda {count} doğrudan yönlendirmeniz ve {unlocked} / 15 seviye kilidi açık.",
      directs: "doğrudan",
      intervals: "aralıklar"
    },
    p2p: {
      subtitle: "Atomik peer-to-peer KAIRO ticareti",
      connectWalletTitle: "Ticaret için cüzdanınızı bağlayın",
      connectWalletDesc: "Peer-to-peer KAIRO ticaretine erişin",
      dexPrice: "DEX Fiyatı",
      vol: "hac",
      noActiveBuyOrders: "Aktif alış emri yok",
      noActiveSellOrders: "Aktif satış emri yok",
      fill: "Doldur",
      enterAmount: "Tutar girin...",
      usdtAmount: "USDT Tutarı",
      kairoAmount: "KAIRO Tutarı",
      max: "MAKS: {amount}",
      balanceLabel: "Bakiye: {amount} {token}",
      dexReferencePrice: "DEX Referans Fiyatı",
      tradingFee: "Ticaret Ücreti",
      estimated: "Tahmini {token}",
      approveAndCreateBuy: "Onayla & Alış Emri Oluştur",
      createBuyOrder: "Alış Emri Oluştur",
      approveAndCreateSell: "Onayla & Satış Emri Oluştur",
      createSellOrder: "Satış Emri Oluştur",
      noActiveOrders: "Aktif emriniz yok.",
      noActiveOrdersDesc: "Başlamak için bir alış veya satış emri oluşturun.",
      myBuyOrders: "Alış Emirlerim",
      mySellOrders: "Satış Emirlerim",
      cancel: "İptal",
      remaining: "${amount} kaldı",
      filledOfTotal: "${total} toplamın ${filled} dolması",
      kairoRemaining: "{amount} KAIRO kaldı"
    },
    swap: {
      title: "Swap",
      subtitle: "%{fee} ücret ve deflasyonist yakma ile tek yönlü swap",
      connectWalletTitle: "Swap için cüzdanınızı bağlayın",
      connectWalletDesc: "Deflasyonist yakma ile tek yönlü KAIRO'dan USDT'ye swap",
      poolUsdt: "Havuz USDT",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap deflasyonist yakma içerir",
      youPay: "Ödüyorsunuz",
      youReceive: "Alıyorsunuz (tahmini)",
      rate: "Oran",
      fee: "Ücret ({percent}%)",
      minOutput: "Min Çıktı ({slippage}% kayma)",
      slippage: "Kayma:",
      priceImpact: "Fiyat Etkisi",
      approveAndSwap: "Onayla & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "MAKS: {amount}"
    },
    referralNetwork: {
      title: "Yönlendirme Ağı",
      rank: "Rütbe",
      directReferrals: "Doğrudan Yönlendirmeler",
      directActive: "{count} aktif",
      directBusiness: "Doğrudan Hacim",
      referralStakes: "yönlendirme stakeleri",
      teamBusiness: "Takım Hacmi",
      totalDownlineVolume: "toplam downline hacmi",
      shareLink: "Yeni üyeler davet etmek ve çok seviyeli komisyonlar kazanmak için linkinizi paylaşın.",
      earnDirect: "Her yönlendirme stakinde %5 doğrudan komisyon + 15 seviye takım temettüsü kazanın."
    },
    rankDividend: {
      title: "Rütbe Temettüsü",
      subtitle: "Takım hacmi yoluyla rütbeler kazanın ve periyodik maaş ödülleri kazanın",
      connectWalletTitle: "Cüzdanınızı bağlayın",
      rankChangeDetected: "Rütbe Değişikliği Algılandı: {from} → {to}",
      rankChangeDesc: "Onayladığınızda maaş zamanlayıcınız sıfırlanacak. Rütbenizi güncellemek için aşağıya tıklayın.",
      updateRank: "Rütbe Güncelle",
      currentRank: "Mevcut Rütbe",
      rankLevel: "Seviye {level} / 10",
      rankSalary: "Rütbe Maaşı",
      perPeriod: "periyot başına",
      harvestable: "Hasatlanabilir",
      crystallized: "kristalleşti",
      harvested: "Hasatlandı",
      totalClaimed: "toplam talep edilen",
      rankProgress: "Rütbe İlerleyişi",
      earningPerPeriod: "${amount} / periyot kazanıyor",
      pending: "Bekleyen: ${amount} · kristalleştirmek için Senkronize et",
      syncRankChange: "Rütbe Değişikliğini Senkronize Et",
      syncRankSalary: "Rütbe Maaşını Senkronize Et (+${amount})",
      nothingToSync: "Senkronize Edilecek Şey Yok",
      harvestBtn: "Hasat ${amount}",
      nothingToHarvest: "Hasatlanacak Şey Yok",
      teamVolumeTitle: "Takım Hacmi",
      totalTeamVolume: "Toplam Takım Hacmi",
      next: "Sonraki: {rank}",
      targetMet: "Hedefe ulaşıldı!",
      needMoreVolume: "${amount} daha uygun hacim gerekli",
      progressAchieved: "%{percent} ulaşıldı",
      directReferrals: "Doğrudan Yönlendirmeler",
      activeDirects: "Aktif Doğrudanlar",
      unlockedLevels: "Açık Seviyeler",
      harvestIncomeTitle: "Hasat Geliri",
      direct: "Doğrudan",
      team: "Takım",
      rank: "Rütbe",
      harvest: "Hasat",
      fiftyPctCapRule: "Bacak Başına %50 Sınır Kuralı",
      fiftyPctDesc: "Her rütbe hedefi için, o rütbenin eşiğinin maksimum %50'si tek bir bacaktan kredilendirilebilir. Kişisel hacminiz rütbe niteliğine sayılmaz. Tek bir bacak büyük hacme sahip olsa bile, rütbe hedefinin sadece %50'si kredilendirilir.",
      totalTeamVolumeLabel: "Toplam Takım Hacmi",
      largestLeg: "En Büyük Bacak",
      numberOfLegs: "Bacak Sayısı",
      qualifyingVolume: "Uygun Hacim",
      legVolumeBreakdown: "Bacak Hacim Detayı",
      leg: "Bacak {index}",
      maxCredited: "(maks ${amount})",
      rankTargetsTitle: "Rütbe Hedefleri ve Maaşları",
      rankCol: "Rütbe",
      teamVolumeTargetCol: "Takım Hacmi Hedefi",
      salaryCol: "Maaş / Periyot",
      progressCol: "İlerleyiş",
      statusCol: "Durum",
      achieved: "Ulaşıldı",
      nextTarget: "Sonraki Hedef",
      locked: "Kilitli",
      salaryHistoryTitle: "Maaş Geçmişi",
      records: "{count} kayıt",
      loadingHistory: "Geçmiş yükleniyor...",
      noSalaryHistory: "Henüz maaş geçmişi yok. Kazanmaya başlamak için bir rütbe kazanın!",
      typeCol: "Tür",
      dateCol: "Tarih",
      amountCol: "Tutar",
      txCol: "İşlem",
      salaryCredited: "Maaş Kredilendirildi",
      harvestedLabel: "Hasatlandı"
    },
    teamDividend: {
      title: "Takım Temettüsü",
      subtitle: "Doğrudan yönlendirme sayınıza dayalı olarak takım bileşik kârlarının 15 seviyesinden kazanın. Zincirdeki aktif olmayan kullanıcılar atlanır — sadece aktif pay sahipleri seviye olarak sayılır.",
      connectWalletTitle: "Cüzdanınızı bağlayın",
      connectWalletDesc: "Takım temettü kazançlarınızı görüntüleyin",
      unlockedLevels: "Açık Seviyeler",
      directReferrals: "Doğrudan Yönlendirmeler",
      moreForNext: "Sonraki seviye için {count} daha",
      maxLevelsUnlocked: "Maksimum seviye açık",
      directBusiness: "Doğrudan Hacim",
      referralStakes: "Yönlendirme Stakeleri",
      teamVolume: "Takım Hacmi",
      totalDownlineVolume: "Toplam downline hacmi",
      teamDividend: "Takım Temettüsü",
      harvest: "Hasat",
      activeLabel: "aktif",
      levelBreakdownTitle: "Seviye Detayı — Tam Bilgiler",
      levelBreakdownDesc: "Her seviye, o sıkıştırılmış derinlikte aktif kullanıcılar tarafından üretilen bileşik kâr yüzdesi kazanır. Aktif olmayan kullanıcılar atlanır — seviye olarak sayılmazlar. L1: %10, L2-L10: her biri %5, L11-L15: her biri %2. Doğrudan yönlendirmeler ekleyerek seviyeleri açın: 1-5 doğrudan = 1-5 seviye, sonra her ek doğrudan = 2 seviye daha (10 doğrudanda maks 15).",
      levelCol: "Seviye",
      rateCol: "Oran",
      membersCol: "Üyeler",
      businessCol: "Hacim",
      earnedCol: "Kazanılan",
      statusCol: "Durum",
      statusActive: "Aktif",
      statusNext: "Sonraki",
      statusLocked: "Kilitli",
      total: "Toplam",
      levelLabel: "Seviye {level}",
      directsNeeded: "{count} doğrudan",
      levelActivationTracker: "Seviye Aktivasyon Takipçisi",
      levelActivationDesc: "{directs} doğrudan yönlendirmeniz var, {unlocked} / 15 takım temettü seviyesi açılıyor.",
      ppl: "kişi",
      legs: "{count} bacak",
      legVolumeBreakdown: "Bacak Hacim Detayı",
      legVolumeDesc: "Her doğrudan yönlendirme bir \"bacak\" oluşturur. Toplam aşağı akış hacimleri takım hacminize ve rütbe niteliğinize katkıda bulunur.",
      refCol: "Yönlendirme",
      selfStakeCol: "Kendi Stakeniz",
      legVolumeCol: "Bacak Hacmi",
      shareCol: "Pay",
      howItWorks: "Takım Temettüsü Nasıl Çalışır",
      how1: "Takımınızdaki herhangi bir kullanıcı stakeni bileşiklediğinde kâr üretilir (her aralıkta %0,15).",
      how2: "Seviyeye göre o kârın bir yüzdesini kazanırsınız: L1=%10, L2-L10=%5, L11-L15=%2.",
      how3: "Aktif stake ve FIFO sınır alanı gerektirir. Kazançlar toplam stakenizin 3X ile sınırlıdır."
    },
    cms: {
      subtitle: "CMS abonelikleri satın alın ve KAIRO ödülleri kazanın",
      connectWalletTitle: "Çekirdek Üyelik",
      notAvailable: "CMS Kullanılamıyor",
      notAvailableDesc: "Çekirdek Üyelik Aboneliği sözleşmesi henüz dağıtılmadı.",
      yourSubscriptions: "Abonelikleriniz",
      remainingSlots: "Kalan Slotlar",
      subscriptionStatus: "Abonelik Durumu",
      active: "Aktif",
      ended: "Sona erdi",
      purchaseSubscription: "Abonelik Satın Al",
      subscriptionEnded: "Abonelik dönemi sona erdi",
      numberOfSubscriptions: "Abonelik Sayısı",
      enterAmount: "Tutar girin...",
      subscriptionDetails: "Abonelik Detayları",
      pricePerSub: "Abonelik başına fiyat:",
      loyaltyRewardPerSub: "Abonelik başına sadakat ödülü:",
      totalCost: "Toplam maliyet:",
      youllEarn: "Kazanacağınız:",
      approveUsdt: "USDT Onayla",
      subscribeBtn: "Abone Ol ({cost} USDT)",
      completeRegistrationFirst: "Lütfen önce kaydı tamamlayın",
      claimRewards: "Ödülleri Talep Et",
      alreadyClaimed: "Ödüllerinizi zaten talep ettiniz",
      loyaltyRewards: "Sadakat Ödülleri",
      leadershipRewards: "Liderlik Ödülleri",
      totalClaimable: "Toplam Talep Edilebilir",
      claimRules: "Talep Kuralları",
      claimRule1: "Tek seferlik talep (kullan veya kaybet)",
      claimRule2: "StakingManager'da aktif stake gerektirir",
      claimRule3: "Aktif stake değeriyle sınırlı (fazlalık silinir)",
      claimRule4: "%90 size basılır, %10 deflasyonist (basılmaz)",
      excessWarning: "Uyarı: {amount} KAIRO kalıcı olarak silinecek (stake sınırını aşıyor)",
      maxClaimable: "Maks talep edilebilir (stakee göre):",
      claimRewardsBtn: "Ödülleri Talep Et",
      leadershipRewardsTitle: "Liderlik Ödülleri (5 Seviye)",
      levelCol: "Seviye",
      requiredDirectsCol: "Gerekli Doğrudanlar",
      rewardPerSubCol: "Ödül/Abonelik",
      subscriptionsCol: "Abonelikler",
      earnedCol: "Kazanılan (KAIRO)",
      levelLabel: "Seviye {level}",
      howCmsWorks: "CMS Nasıl Çalışır",
      subscriptionBenefits: "Abonelik Faydaları",
      benefit1: "Abonelik başına 10 USDT (toplam maks 10.000)",
      benefit2: "Abonelik başına 5 KAIRO sadakat ödülü kazanın",
      benefit3: "5 yönlendirme seviyesinden liderlik ödülleri kazanın",
      benefit4: "Aktif stake ile bir kez talep et (kullan veya kaybet)",
      referralRewards: "Yönlendirme Ödülleri",
      level1Desc: "Abonelik başına 1 KAIRO (0 doğrudan gerekli)",
      level2Desc: "Abonelik başına 0,5 KAIRO (2 doğrudan gerekli)",
      level3Desc: "Abonelik başına 0,5 KAIRO (3 doğrudan gerekli)",
      level4Desc: "Abonelik başına 0,25 KAIRO (4 doğrudan gerekli)",
      level5Desc: "Abonelik başına 0,25 KAIRO (5 doğrudan gerekli)",
      level1: "Seviye 1:",
      level2: "Seviye 2:",
      level3: "Seviye 3:",
      level4: "Seviye 4:",
      level5: "Seviye 5:"
    },
    analytics: {
      title: "Protokol Analizi",
      subtitle: "Gerçek zamanlı KAIRO ekosistem istatistikleri",
      kairoPrice: "KAIRO Fiyatı",
      marketCap: "Piyasa Değeri",
      poolLiquidityUsdt: "Havuz Likiditesi (USDT)",
      totalBurned: "Toplam Yakılan",
      tokenSupply: "Token Arzı",
      deflationaryNote: "Yakma yoluyla deflasyonist mekanizmalar",
      circulating: "Dolaşımda",
      burned: "Yakılan",
      effectiveSupply: "Efektif Arz",
      socialLock: "Sosyal Kilit",
      burnRate: "Yakma Oranı",
      liquidityPool: "Likidite Havuzu",
      dexPoolComposition: "DEX havuz kompozisyonu",
      kairoInPool: "Havuzda KAIRO",
      usdtInPool: "Havuzda USDT",
      pricePerSupply: "Fiyat (USDT / Toplam Arz)"
    },
    portfolio: {
      totalPortfolioValue: "Toplam Portföy Değeri",
      activeStakes: "Aktif Stakeler",
      totalStaked: "Toplam Staked",
      totalEarned: "Toplam Kazanılan",
      remainingCapping: "Kalan Sınır",
      kairoPrice: "KAIRO Fiyatı",
      poolLiquidity: "Havuz Likiditesi",
      totalCirculation: "Toplam Dolaşım",
      harvestableAffiliate: "Hasatlanabilir (Affiliate)",
      activeDirects: "Aktif Doğrudanlar"
    },
    activeStakesTable: {
      title: "Aktif Stakeler",
      loading: "Stakeler yükleniyor...",
      empty: "Aktif stake yok. Ödül kazanmak için stakinge başlayın!",
      tierCount: "{count} kademe",
      stakeCount: "{count} stake",
      stakedAmount: "Staked Tutar",
      capProgress: "3X Sınır İlerleyişi",
      harvestable: "Hasatlanabilir",
      harvested: "Hasatlanan",
      totalEarned: "Toplam Kazanılan",
      pendingCompoundProfit: "Bekleyen bileşik kâr",
      autoCompound: "Otomatik Bileşik",
      autoCompoundBtn: "Otomatik Bileşik ({count})",
      accruing: "Birikiyor",
      harvest: "Hasat ${amount}",
      minHarvestStake: "Min $10/stake",
      minHarvestAmount: "Min $10",
      intervals: "aralıklar"
    },
    income: {
      title: "Gelir Özeti",
      typesCount: "{count} tür",
      direct: "Doğrudan Komisyon",
      team: "Takım Temettüleri",
      rank: "Rütbe Maaşı",
      harvest: "Hasat",
      pendingHarvest: "Bekleyen Hasat",
      affiliateHarvested: "Affiliate Hasatlandı",
      directLabel: "Doğrudan",
      teamLabel: "Takım",
      rankLabel: "Rütbe",
      stakingEarnings: "Staking Kazançları",
      harvestedLabel: "Hasatlandı",
      harvestableLabel: "Hasatlanabilir"
    },
    faucet: {
      testnetFaucet: "Testnet Musluğu · Sahte USDT",
      mintDesc: "Geliştirme için test USDT basın. Mevcut bakiye:",
      mint10000: "10.000 USDT Bas",
      mint: "Bas",
      customPlaceholder: "özel",
      mintingPending: "Test USDT basılıyor…",
      mintingDesc: "Cüzdanınıza {amount} USDT gönderiliyor",
      mintedSuccess: "{amount} test USDT basıldı",
      mintFailed: "Basım başarısız",
      invalidAmount: "Geçersiz tutar"
    },
    common: {
      connectWalletTitle: "Cüzdanınızı Bağlayın",
      connectWalletDesc: "Portföyünüzü görüntülemek, stakeleri yönetmek ve kazançları izlemek için cüzdanınızı bağlayın."
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
