import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  vi: {
    staking: {
      connectWalletTitle: "Kết nối ví để stake",
      closingInterval: "khoảng thời gian đóng",
      newStake: "Stake Mới",
      amount: "Số lượng (USDT)",
      amountPlaceholder: "Nhập số lượng...",
      balanceHelper: "Số dư: {balance} USDT | Tối thiểu: 10 USDT | Không giới hạn tối đa",
      autoCompoundEvery: "Tự động gộp lãi mỗi {interval}",
      approveAndStake: "Phê duyệt & Stake ${amount}",
      stakeBtn: "Stake ${amount}",
      yourStakes: "Stake của bạn",
      active: "hoạt động",
      noActiveStakesDesc: "Chưa có stake hoạt động. Tạo stake đầu tiên để bắt đầu kiếm!",
      stakeCount: "{count} stake",
      totalStaked: "Tổng đã stake",
      tierHeader: "Giới hạn 3X",
      pendingCompoundProfit: "Lợi nhuận gộp lãi đang chờ",
      autoCompoundBtn: "Tự động gộp lãi ({count})",
      accruing: "Đang tích lũy",
      harvestBtn: "Thu hoạch ${amount}",
      minHarvestStake: "Tối thiểu $10/stake",
      minHarvestAmount: "Tối thiểu $10",
      total: "tổng",
      tierCol: "Hạng",
      stakedCol: "Đã stake",
      earnedCol: "Đã kiếm",
      harvestedCol: "Đã thu hoạch",
      capCol: "Giới hạn 3X",
      startedCol: "Bắt đầu",
      statusCol: "Trạng thái",
      actionCol: "Hành động",
      statusActive: "Hoạt động",
      statusCapped: "Đạt giới hạn",
      statusClosed: "Đã đóng",
      unstake: "Rút stake",
      unstakeConfirm: "Rút stake #{index}?\n\nBạn đã stake ${original} USDT.\nBạn sẽ nhận ~${preview} KAIRO\n(80% vốn gốc, trừ thu nhập thu hoạch đang chờ).\n\nHành động này không thể hoàn tác. Tiếp tục?",
      calcTitle: "Máy tính gộp lãi",
      calcSubtitle: "Dự kiến tích lũy lợi nhuận tiềm năng theo thời gian",
      calcStakeAmount: "Số lượng Stake (USDT)",
      calcEnterAmount: "Nhập số lượng stake...",
      calcDuration: "Thời gian: {count} tháng",
      calcProjectedProfit: "Lợi nhuận dự kiến",
      calcTier: "Hạng",
      calcFrequency: "Tần suất",
      calcCompounds: "Số lần gộp lãi",
      calcNote: "0,15% mỗi lần gộp · Hạng và tần suất tự động xác định từ số lượng",
      levelUnlockTitle: "Mở khóa cấp cổ tức đội ngũ",
      levelUnlockDesc: "Mở thêm cấp cổ tức đội ngũ bằng cách thêm người giới thiệu trực tiếp. Bạn hiện có {count} người giới thiệu trực tiếp và {unlocked} / 15 cấp đã mở khóa.",
      directs: "trực tiếp",
      intervals: "khoảng thời gian"
    },
    p2p: {
      subtitle: "Giao dịch KAIRO ngang hàng nguyên tử",
      connectWalletTitle: "Kết nối ví để giao dịch",
      connectWalletDesc: "Truy cập giao dịch KAIRO ngang hàng",
      dexPrice: "Giá DEX",
      vol: "khối lượng",
      noActiveBuyOrders: "Không có lệnh mua hoạt động",
      noActiveSellOrders: "Không có lệnh bán hoạt động",
      fill: "Khớp",
      enterAmount: "Nhập số lượng...",
      usdtAmount: "Số lượng USDT",
      kairoAmount: "Số lượng KAIRO",
      max: "TỐI ĐA: {amount}",
      balanceLabel: "Số dư: {amount} {token}",
      dexReferencePrice: "Giá tham chiếu DEX",
      tradingFee: "Phí giao dịch",
      estimated: "Ước tính {token}",
      approveAndCreateBuy: "Phê duyệt & Tạo lệnh mua",
      createBuyOrder: "Tạo lệnh mua",
      approveAndCreateSell: "Phê duyệt & Tạo lệnh bán",
      createSellOrder: "Tạo lệnh bán",
      noActiveOrders: "Bạn không có lệnh nào hoạt động.",
      noActiveOrdersDesc: "Tạo lệnh mua hoặc bán để bắt đầu.",
      myBuyOrders: "Lệnh mua của tôi",
      mySellOrders: "Lệnh bán của tôi",
      cancel: "Hủy",
      remaining: "${amount} còn lại",
      filledOfTotal: "${filled} đã khớp trên ${total} tổng",
      kairoRemaining: "{amount} KAIRO còn lại"
    },
    swap: {
      title: "Swap",
      subtitle: "Swap một chiều với phí {fee}% và đốt giảm phát",
      connectWalletTitle: "Kết nối ví để swap",
      connectWalletDesc: "Swap KAIRO sang USDT một chiều với đốt giảm phát",
      poolUsdt: "USDT trong Pool",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap bao gồm đốt giảm phát",
      youPay: "Bạn trả",
      youReceive: "Bạn nhận (ước tính)",
      rate: "Tỷ giá",
      fee: "Phí ({percent}%)",
      minOutput: "Đầu ra tối thiểu ({slippage}% trượt giá)",
      slippage: "Trượt giá:",
      priceImpact: "Tác động giá",
      approveAndSwap: "Phê duyệt & Swap",
      swapBtn: "Swap KAIRO → USDT",
      max: "TỐI ĐA: {amount}"
    },
    referralNetwork: {
      title: "Mạng lưới giới thiệu",
      rank: "Hạng",
      directReferrals: "Người giới thiệu trực tiếp",
      directActive: "{count} hoạt động",
      directBusiness: "Khối lượng trực tiếp",
      referralStakes: "stake giới thiệu",
      teamBusiness: "Khối lượng đội ngũ",
      totalDownlineVolume: "tổng khối lượng tuyến dưới",
      shareLink: "Chia sẻ liên kết để mời thành viên mới và kiếm hoa hồng đa cấp.",
      earnDirect: "Kiếm 5% hoa hồng trực tiếp + cổ tức đội ngũ 15 cấp trên mỗi stake giới thiệu."
    },
    rankDividend: {
      title: "Cổ tức hạng",
      subtitle: "Đạt hạng thông qua khối lượng đội ngũ và nhận phần thưởng lương định kỳ",
      connectWalletTitle: "Kết nối ví",
      rankChangeDetected: "Phát hiện thay đổi hạng: {from} → {to}",
      rankChangeDesc: "Bộ đếm lương sẽ đặt lại khi bạn xác nhận. Nhấn bên dưới để cập nhật hạng.",
      updateRank: "Cập nhật hạng",
      currentRank: "Hạng hiện tại",
      rankLevel: "Cấp {level} / 10",
      rankSalary: "Lương hạng",
      perPeriod: "mỗi chu kỳ",
      harvestable: "Có thể thu hoạch",
      crystallized: "kết tinh",
      harvested: "Đã thu hoạch",
      totalClaimed: "tổng đã nhận",
      rankProgress: "Tiến độ hạng",
      earningPerPeriod: "Kiếm ${amount} / chu kỳ",
      pending: "Đang chờ: ${amount} · nhấn Đồng bộ để kết tinh",
      syncRankChange: "Đồng bộ thay đổi hạng",
      syncRankSalary: "Đồng bộ lương hạng (+${amount})",
      nothingToSync: "Không có gì để đồng bộ",
      harvestBtn: "Thu hoạch ${amount}",
      nothingToHarvest: "Không có gì thu hoạch",
      teamVolumeTitle: "Khối lượng đội ngũ",
      totalTeamVolume: "Tổng khối lượng đội ngũ",
      next: "Tiếp theo: {rank}",
      targetMet: "Đạt mục tiêu!",
      needMoreVolume: "Cần thêm ${amount} khối lượng hội đủ điều kiện",
      progressAchieved: "Đạt {percent}%",
      directReferrals: "Người giới thiệu trực tiếp",
      activeDirects: "Trực tiếp hoạt động",
      unlockedLevels: "Cấp đã mở khóa",
      harvestIncomeTitle: "Thu nhập thu hoạch",
      direct: "Trực tiếp",
      team: "Đội ngũ",
      rank: "Hạng",
      harvest: "Thu hoạch",
      fiftyPctCapRule: "Quy tắc giới hạn 50% mỗi nhánh",
      fiftyPctDesc: "Cho mỗi mục tiêu hạng, tối đa 50% ngưỡng của hạng cụ thể đó có thể được ghi nhận từ bất kỳ nhánh đơn lẻ nào. Khối lượng cá nhân không tính cho điều kiện hạng. Ngay cả khi một nhánh có khối lượng khổng lồ, chỉ 50% mục tiêu hạng sẽ được ghi nhận.",
      totalTeamVolumeLabel: "Tổng khối lượng đội ngũ",
      largestLeg: "Nhánh lớn nhất",
      numberOfLegs: "Số nhánh",
      qualifyingVolume: "Khối lượng hội đủ điều kiện",
      legVolumeBreakdown: "Phân tích khối lượng theo nhánh",
      leg: "Nhánh {index}",
      maxCredited: "(tối đa ${amount})",
      rankTargetsTitle: "Mục tiêu và lương hạng",
      rankCol: "Hạng",
      teamVolumeTargetCol: "Mục tiêu khối lượng đội ngũ",
      salaryCol: "Lương / Chu kỳ",
      progressCol: "Tiến độ",
      statusCol: "Trạng thái",
      achieved: "Đã đạt",
      nextTarget: "Mục tiêu tiếp theo",
      locked: "Đã khóa",
      salaryHistoryTitle: "Lịch sử lương",
      records: "{count} bản ghi",
      loadingHistory: "Đang tải lịch sử...",
      noSalaryHistory: "Chưa có lịch sử lương. Đạt hạng để bắt đầu kiếm!",
      typeCol: "Loại",
      dateCol: "Ngày",
      amountCol: "Số lượng",
      txCol: "Giao dịch",
      salaryCredited: "Lương đã ghi nhận",
      harvestedLabel: "Đã thu hoạch"
    },
    teamDividend: {
      title: "Cổ tức đội ngũ",
      subtitle: "Kiếm từ 15 cấp lợi nhuận gộp lãi đội ngũ dựa trên số người giới thiệu trực tiếp của bạn. Người dùng không hoạt động trong chuỗi sẽ bị bỏ qua — chỉ người tham gia stake hoạt động mới tính là cấp.",
      connectWalletTitle: "Kết nối ví",
      connectWalletDesc: "Xem thu nhập cổ tức đội ngũ của bạn",
      unlockedLevels: "Cấp đã mở khóa",
      directReferrals: "Người giới thiệu trực tiếp",
      moreForNext: "Thêm {count} cho cấp tiếp theo",
      maxLevelsUnlocked: "Đã mở khóa tối đa cấp",
      directBusiness: "Khối lượng trực tiếp",
      referralStakes: "Stake giới thiệu",
      teamVolume: "Khối lượng đội ngũ",
      totalDownlineVolume: "Tổng khối lượng tuyến dưới",
      teamDividend: "Cổ tức đội ngũ",
      harvest: "Thu hoạch",
      activeLabel: "hoạt động",
      levelBreakdownTitle: "Phân tích cấp — Chi tiết đầy đủ",
      levelBreakdownDesc: "Mỗi cấp kiếm được tỷ lệ phần trăm lợi nhuận gộp lãi được tạo bởi người dùng hoạt động ở độ sâu nén đó. Người dùng không hoạt động bị bỏ qua — không tính là cấp. L1: 10%, L2-L10: 5% mỗi cấp, L11-L15: 2% mỗi cấp. Mở khóa cấp bằng cách thêm người giới thiệu trực tiếp: 1-5 trực tiếp = 1-5 cấp, sau đó mỗi trực tiếp thêm = 2 cấp nữa (tối đa 15 tại 10 trực tiếp).",
      levelCol: "Cấp",
      rateCol: "Tỷ lệ",
      membersCol: "Thành viên",
      businessCol: "Khối lượng",
      earnedCol: "Đã kiếm",
      statusCol: "Trạng thái",
      statusActive: "Hoạt động",
      statusNext: "Tiếp theo",
      statusLocked: "Đã khóa",
      total: "Tổng",
      levelLabel: "Cấp {level}",
      directsNeeded: "{count} trực tiếp",
      levelActivationTracker: "Theo dõi kích hoạt cấp",
      levelActivationDesc: "Bạn có {directs} người giới thiệu trực tiếp, mở khóa {unlocked} / 15 cấp cổ tức đội ngũ.",
      ppl: "người",
      legs: "{count} nhánh",
      legVolumeBreakdown: "Phân tích khối lượng theo nhánh",
      legVolumeDesc: "Mỗi người giới thiệu trực tiếp tạo thành một \"nhánh\". Tổng khối lượng hạ nguồn của họ đóng góp vào khối lượng đội ngũ và điều kiện hạng của bạn.",
      refCol: "Người giới thiệu",
      selfStakeCol: "Stake cá nhân",
      legVolumeCol: "Khối lượng nhánh",
      shareCol: "Phần chia",
      howItWorks: "Cổ tức đội ngũ hoạt động thế nào",
      how1: "Khi bất kỳ người dùng nào trong đội ngũ gộp lãi stake, lợi nhuận được tạo ra (0,15% mỗi khoảng thời gian).",
      how2: "Bạn kiếm được tỷ lệ phần trăm của lợi nhuận đó theo cấp: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Yêu cầu stake hoạt động và không gian giới hạn FIFO. Thu nhập giới hạn ở 3X tổng stake của bạn."
    },
    cms: {
      subtitle: "Mua đăng ký CMS và kiếm phần thưởng KAIRO",
      connectWalletTitle: "Thành viên cốt lõi",
      notAvailable: "CMS không khả dụng",
      notAvailableDesc: "Hợp đồng đăng ký thành viên cốt lõi chưa được triển khai.",
      yourSubscriptions: "Đăng ký của bạn",
      remainingSlots: "Slot còn lại",
      subscriptionStatus: "Trạng thái đăng ký",
      active: "Hoạt động",
      ended: "Kết thúc",
      purchaseSubscription: "Mua đăng ký",
      subscriptionEnded: "Kỳ đăng ký đã kết thúc",
      numberOfSubscriptions: "Số đăng ký",
      enterAmount: "Nhập số lượng...",
      subscriptionDetails: "Chi tiết đăng ký",
      pricePerSub: "Giá mỗi đăng ký:",
      loyaltyRewardPerSub: "Phần thưởng trung thành mỗi đăng ký:",
      totalCost: "Tổng chi phí:",
      youllEarn: "Bạn sẽ kiếm:",
      approveUsdt: "Phê duyệt USDT",
      subscribeBtn: "Đăng ký ({cost} USDT)",
      completeRegistrationFirst: "Vui lòng hoàn tất đăng ký trước",
      claimRewards: "Nhận phần thưởng",
      alreadyClaimed: "Bạn đã nhận phần thưởng",
      loyaltyRewards: "Phần thưởng trung thành",
      leadershipRewards: "Phần thưởng lãnh đạo",
      totalClaimable: "Tổng có thể nhận",
      claimRules: "Quy tắc nhận thưởng",
      claimRule1: "Nhận một lần (dùng hoặc mất)",
      claimRule2: "Yêu cầu stake hoạt động trong StakingManager",
      claimRule3: "Giới hạn bởi giá trị stake hoạt động (phần dư bị xóa)",
      claimRule4: "90% được mint cho bạn, 10% giảm phát (không mint)",
      excessWarning: "Cảnh báo: {amount} KAIRO sẽ bị xóa vĩnh viễn (vượt giới hạn stake)",
      maxClaimable: "Tối đa có thể nhận (dựa trên stake):",
      claimRewardsBtn: "Nhận phần thưởng",
      leadershipRewardsTitle: "Phần thưởng lãnh đạo (5 cấp)",
      levelCol: "Cấp",
      requiredDirectsCol: "Trực tiếp yêu cầu",
      rewardPerSubCol: "Phần thưởng/Đăng ký",
      subscriptionsCol: "Đăng ký",
      earnedCol: "Đã kiếm (KAIRO)",
      levelLabel: "Cấp {level}",
      howCmsWorks: "CMS hoạt động thế nào",
      subscriptionBenefits: "Quyền lợi đăng ký",
      benefit1: "10 USDT mỗi đăng ký (tối đa 10.000 tổng)",
      benefit2: "Kiếm 5 KAIRO phần thưởng trung thành mỗi đăng ký",
      benefit3: "Kiếm phần thưởng lãnh đạo từ 5 cấp giới thiệu",
      benefit4: "Nhận một lần với stake hoạt động (dùng hoặc mất)",
      referralRewards: "Phần thưởng giới thiệu",
      level1Desc: "1 KAIRO mỗi đăng ký (0 trực tiếp yêu cầu)",
      level2Desc: "0,5 KAIRO mỗi đăng ký (2 trực tiếp yêu cầu)",
      level3Desc: "0,5 KAIRO mỗi đăng ký (3 trực tiếp yêu cầu)",
      level4Desc: "0,25 KAIRO mỗi đăng ký (4 trực tiếp yêu cầu)",
      level5Desc: "0,25 KAIRO mỗi đăng ký (5 trực tiếp yêu cầu)",
      level1: "Cấp 1:",
      level2: "Cấp 2:",
      level3: "Cấp 3:",
      level4: "Cấp 4:",
      level5: "Cấp 5:"
    },
    analytics: {
      title: "Phân tích giao thức",
      subtitle: "Thống kê hệ sinh thái KAIRO thời gian thực",
      kairoPrice: "Giá KAIRO",
      marketCap: "Vốn hóa thị trường",
      poolLiquidityUsdt: "Thanh khoản Pool (USDT)",
      totalBurned: "Tổng đã đốt",
      tokenSupply: "Nguồn cung Token",
      deflationaryNote: "Cơ chế giảm phát thông qua đốt",
      circulating: "Lưu thông",
      burned: "Đã đốt",
      effectiveSupply: "Nguồn cung hiệu quả",
      socialLock: "Social Lock",
      burnRate: "Tỷ lệ đốt",
      liquidityPool: "Pool thanh khoản",
      dexPoolComposition: "Thành phần pool DEX",
      kairoInPool: "KAIRO trong Pool",
      usdtInPool: "USDT trong Pool",
      pricePerSupply: "Giá (USDT / Tổng nguồn cung)"
    },
    portfolio: {
      totalPortfolioValue: "Tổng giá trị danh mục",
      activeStakes: "Stake hoạt động",
      totalStaked: "Tổng đã stake",
      totalEarned: "Tổng đã kiếm",
      remainingCapping: "Giới hạn còn lại",
      kairoPrice: "Giá KAIRO",
      poolLiquidity: "Thanh khoản Pool",
      totalCirculation: "Tổng lưu thông",
      harvestableAffiliate: "Có thể thu hoạch (Tiếp thị)",
      activeDirects: "Trực tiếp hoạt động"
    },
    activeStakesTable: {
      title: "Stake hoạt động",
      loading: "Đang tải stake...",
      empty: "Không có stake hoạt động. Bắt đầu staking để kiếm phần thưởng!",
      tierCount: "{count} hạng",
      stakeCount: "{count} stake",
      stakedAmount: "Số lượng đã stake",
      capProgress: "Tiến độ giới hạn 3X",
      harvestable: "Có thể thu hoạch",
      harvested: "Đã thu hoạch",
      totalEarned: "Tổng đã kiếm",
      pendingCompoundProfit: "Lợi nhuận gộp lãi đang chờ",
      autoCompound: "Tự động gộp lãi",
      autoCompoundBtn: "Tự động gộp lãi ({count})",
      accruing: "Đang tích lũy",
      harvest: "Thu hoạch ${amount}",
      minHarvestStake: "Tối thiểu $10/stake",
      minHarvestAmount: "Tối thiểu $10",
      intervals: "khoảng thời gian"
    },
    income: {
      title: "Tóm tắt thu nhập",
      typesCount: "{count} loại",
      direct: "Hoa hồng trực tiếp",
      team: "Cổ tức đội ngũ",
      rank: "Lương hạng",
      harvest: "Thu hoạch",
      pendingHarvest: "Thu hoạch đang chờ",
      affiliateHarvested: "Tiếp thị đã thu hoạch",
      directLabel: "Trực tiếp",
      teamLabel: "Đội ngũ",
      rankLabel: "Hạng",
      stakingEarnings: "Thu nhập staking",
      harvestedLabel: "Đã thu hoạch",
      harvestableLabel: "Có thể thu hoạch"
    },
    faucet: {
      testnetFaucet: "Vòi Testnet · USDT giả",
      mintDesc: "Tạo USDT thử nghiệm cho phát triển. Số dư hiện tại:",
      mint10000: "Tạo 10.000 USDT",
      mint: "Tạo",
      customPlaceholder: "tùy chỉnh",
      mintingPending: "Đang tạo USDT thử nghiệm…",
      mintingDesc: "Đang gửi {amount} USDT đến ví của bạn",
      mintedSuccess: "Đã tạo {amount} USDT thử nghiệm",
      mintFailed: "Tạo thất bại",
      invalidAmount: "Số lượng không hợp lệ"
    },
    common: {
      connectWalletTitle: "Kết nối ví của bạn",
      connectWalletDesc: "Kết nối ví để xem danh mục, quản lý stake và theo dõi thu nhập."
    }
  },

  ko: {
    staking: {
      connectWalletTitle: "스테이킹을 위해 지갑 연결",
      closingInterval: "마감 간격",
      newStake: "새 스테이크",
      amount: "금액 (USDT)",
      amountPlaceholder: "금액 입력...",
      balanceHelper: "잔액: {balance} USDT | 최소: 10 USDT | 최대 한도 없음",
      autoCompoundEvery: "매 {interval}마다 자동 복리",
      approveAndStake: "승인 & 스테이크 ${amount}",
      stakeBtn: "스테이크 ${amount}",
      yourStakes: "내 스테이크",
      active: "활성",
      noActiveStakesDesc: "활성 스테이크가 없습니다. 첫 스테이크를 만들어 수익을 시작하세요!",
      stakeCount: "{count} 스테이크",
      totalStaked: "총 스테이크",
      tierHeader: "3X 상한",
      pendingCompoundProfit: "대기 중 복리 수익",
      autoCompoundBtn: "자동 복리 ({count})",
      accruing: "누적 중",
      harvestBtn: "수확 ${amount}",
      minHarvestStake: "최소 $10/스테이크",
      minHarvestAmount: "최소 $10",
      total: "합계",
      tierCol: "등급",
      stakedCol: "스테이크",
      earnedCol: "획득",
      harvestedCol: "수확됨",
      capCol: "3X 상한",
      startedCol: "시작",
      statusCol: "상태",
      actionCol: "작업",
      statusActive: "활성",
      statusCapped: "상한 도달",
      statusClosed: "종료",
      unstake: "언스테이크",
      unstakeConfirm: "스테이크 #{index} 언스테이크?\n\n${original} USDT를 스테이크했습니다.\n~${preview} KAIRO를 받습니다\n(원금의 80%, 미수취 대기 수익 차감).\n\n이 작업은 되돌릴 수 없습니다. 계속하시겠습니까?",
      calcTitle: "복리 계산기",
      calcSubtitle: "시간에 따른 잠재적 수익 누적 예측",
      calcStakeAmount: "스테이크 금액 (USDT)",
      calcEnterAmount: "스테이크 금액 입력...",
      calcDuration: "기간: {count}개월",
      calcProjectedProfit: "예상 수익",
      calcTier: "등급",
      calcFrequency: "빈도",
      calcCompounds: "복리 횟수",
      calcNote: "복리당 0.15% · 등급 및 빈도는 금액에서 자동 감지",
      levelUnlockTitle: "팀 배당 레벨 잠금 해제",
      levelUnlockDesc: "직접 추천인을 추가하여 더 많은 팀 배당 레벨을 잠금 해제하세요. 현재 직접 추천인 {count}명과 {unlocked} / 15 레벨이 잠금 해제되었습니다.",
      directs: "직접",
      intervals: "간격"
    },
    p2p: {
      subtitle: "원자적 피어투피어 KAIRO 거래",
      connectWalletTitle: "거래를 위해 지갑 연결",
      connectWalletDesc: "피어투피어 KAIRO 거래 접근",
      dexPrice: "DEX 가격",
      vol: "거래량",
      noActiveBuyOrders: "활성 매수 주문 없음",
      noActiveSellOrders: "활성 매도 주문 없음",
      fill: "체결",
      enterAmount: "금액 입력...",
      usdtAmount: "USDT 금액",
      kairoAmount: "KAIRO 금액",
      max: "최대: {amount}",
      balanceLabel: "잔액: {amount} {token}",
      dexReferencePrice: "DEX 참조 가격",
      tradingFee: "거래 수수료",
      estimated: "예상 {token}",
      approveAndCreateBuy: "승인 & 매수 주문 생성",
      createBuyOrder: "매수 주문 생성",
      approveAndCreateSell: "승인 & 매도 주문 생성",
      createSellOrder: "매도 주문 생성",
      noActiveOrders: "활성 주문이 없습니다.",
      noActiveOrdersDesc: "시작하려면 매수 또는 매도 주문을 생성하세요.",
      myBuyOrders: "내 매수 주문",
      mySellOrders: "내 매도 주문",
      cancel: "취소",
      remaining: "${amount} 남음",
      filledOfTotal: "${total} 중 ${filled} 체결",
      kairoRemaining: "{amount} KAIRO 남음"
    },
    swap: {
      title: "스왑",
      subtitle: "{fee}% 수수료 및 디플레이션 소각으로 단방향 스왑",
      connectWalletTitle: "스왑을 위해 지갑 연결",
      connectWalletDesc: "디플레이션 소각으로 KAIRO를 USDT로 단방향 스왑",
      poolUsdt: "풀 USDT",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "스왑에 디플레이션 소각 포함",
      youPay: "지불",
      youReceive: "수령 (예상)",
      rate: "비율",
      fee: "수수료 ({percent}%)",
      minOutput: "최소 출력 ({slippage}% 슬리피지)",
      slippage: "슬리피지:",
      priceImpact: "가격 영향",
      approveAndSwap: "승인 & 스왑",
      swapBtn: "KAIRO → USDT 스왑",
      max: "최대: {amount}"
    },
    referralNetwork: {
      title: "추천 네트워크",
      rank: "랭크",
      directReferrals: "직접 추천인",
      directActive: "{count} 활성",
      directBusiness: "직접 볼륨",
      referralStakes: "추천 스테이크",
      teamBusiness: "팀 볼륨",
      totalDownlineVolume: "총 다운라인 볼륨",
      shareLink: "링크를 공유하여 새 회원을 초대하고 다단계 커미션을 받으세요.",
      earnDirect: "각 추천 스테이크에서 5% 직접 커미션 + 15단계 팀 배당을 받으세요."
    },
    rankDividend: {
      title: "랭크 배당",
      subtitle: "팀 볼륨을 통해 랭크를 달성하고 정기 급여 보상을 받으세요",
      connectWalletTitle: "지갑 연결",
      rankChangeDetected: "랭크 변경 감지: {from} → {to}",
      rankChangeDesc: "확인하면 급여 타이머가 재설정됩니다. 아래를 클릭하여 랭크를 업데이트하세요.",
      updateRank: "랭크 업데이트",
      currentRank: "현재 랭크",
      rankLevel: "레벨 {level} / 10",
      rankSalary: "랭크 급여",
      perPeriod: "기간당",
      harvestable: "수확 가능",
      crystallized: "결정화됨",
      harvested: "수확됨",
      totalClaimed: "총 청구됨",
      rankProgress: "랭크 진행",
      earningPerPeriod: "${amount} / 기간 획득",
      pending: "대기 중: ${amount} · 결정화하려면 동기화 클릭",
      syncRankChange: "랭크 변경 동기화",
      syncRankSalary: "랭크 급여 동기화 (+${amount})",
      nothingToSync: "동기화할 항목 없음",
      harvestBtn: "수확 ${amount}",
      nothingToHarvest: "수확할 항목 없음",
      teamVolumeTitle: "팀 볼륨",
      totalTeamVolume: "총 팀 볼륨",
      next: "다음: {rank}",
      targetMet: "목표 달성!",
      needMoreVolume: "${amount} 더 자격 볼륨 필요",
      progressAchieved: "{percent}% 달성",
      directReferrals: "직접 추천인",
      activeDirects: "활성 직접",
      unlockedLevels: "잠금 해제된 레벨",
      harvestIncomeTitle: "수확 수익",
      direct: "직접",
      team: "팀",
      rank: "랭크",
      harvest: "수확",
      fiftyPctCapRule: "레그당 50% 상한 규칙",
      fiftyPctDesc: "각 랭크 목표에 대해 해당 랭크의 임계값 최대 50%까지 단일 레그에서 인정 가능합니다. 개인 볼륨은 랭크 자격에 산정되지 않습니다. 단일 레그가 막대한 볼륨을 가져도 랭크 목표의 50%만 인정됩니다.",
      totalTeamVolumeLabel: "총 팀 볼륨",
      largestLeg: "최대 레그",
      numberOfLegs: "레그 수",
      qualifyingVolume: "자격 볼륨",
      legVolumeBreakdown: "레그별 볼륨 분석",
      leg: "레그 {index}",
      maxCredited: "(최대 ${amount})",
      rankTargetsTitle: "랭크 목표 및 급여",
      rankCol: "랭크",
      teamVolumeTargetCol: "팀 볼륨 목표",
      salaryCol: "급여 / 기간",
      progressCol: "진행",
      statusCol: "상태",
      achieved: "달성",
      nextTarget: "다음 목표",
      locked: "잠김",
      salaryHistoryTitle: "급여 이력",
      records: "{count} 레코드",
      loadingHistory: "이력 로딩 중...",
      noSalaryHistory: "급여 이력이 없습니다. 랭크를 달성하여 수익을 시작하세요!",
      typeCol: "유형",
      dateCol: "날짜",
      amountCol: "금액",
      txCol: "Tx",
      salaryCredited: "급여 인정됨",
      harvestedLabel: "수확됨"
    },
    teamDividend: {
      title: "팀 배당",
      subtitle: "직접 추천인 수에 따라 15단계의 팀 복리 수익에서 받으세요. 체인의 비활성 사용자는 건너뜁니다 — 활성 스테이크 참여자만 레벨로 산정됩니다.",
      connectWalletTitle: "지갑 연결",
      connectWalletDesc: "팀 배당 수익 보기",
      unlockedLevels: "잠금 해제된 레벨",
      directReferrals: "직접 추천인",
      moreForNext: "다음 레벨까지 {count} 더",
      maxLevelsUnlocked: "최대 레벨 잠금 해제",
      directBusiness: "직접 볼륨",
      referralStakes: "추천 스테이크",
      teamVolume: "팀 볼륨",
      totalDownlineVolume: "총 다운라인 볼륨",
      teamDividend: "팀 배당",
      harvest: "수확",
      activeLabel: "활성",
      levelBreakdownTitle: "레벨 분석 — 전체 세부정보",
      levelBreakdownDesc: "각 레벨은 해당 압축 깊이의 활성 사용자가 생성한 복리 수익의 퍼센트를 받습니다. 비활성 사용자는 건너뜁니다 — 레벨로 산정되지 않습니다. L1: 10%, L2-L10: 각 5%, L11-L15: 각 2%. 직접 추천인 추가로 레벨 잠금 해제: 1-5 직접 = 1-5 레벨, 이후 추가 직접 = 2 레벨 더 (10 직접시 최대 15).",
      levelCol: "레벨",
      rateCol: "비율",
      membersCol: "회원",
      businessCol: "볼륨",
      earnedCol: "획득",
      statusCol: "상태",
      statusActive: "활성",
      statusNext: "다음",
      statusLocked: "잠김",
      total: "합계",
      levelLabel: "레벨 {level}",
      directsNeeded: "{count} 직접",
      levelActivationTracker: "레벨 활성화 추적기",
      levelActivationDesc: "직접 추천인 {directs}명, 팀 배당 레벨 {unlocked} / 15 잠금 해제.",
      ppl: "명",
      legs: "{count} 레그",
      legVolumeBreakdown: "레그별 볼륨 분석",
      legVolumeDesc: "각 직접 추천인은 \"레그\"를 형성합니다. 그들의 총 하류 볼륨은 팀 볼륨과 랭크 자격에 기여합니다.",
      refCol: "추천인",
      selfStakeCol: "본인 스테이크",
      legVolumeCol: "레그 볼륨",
      shareCol: "지분",
      howItWorks: "팀 배당 작동 방식",
      how1: "팀의 사용자가 스테이크를 복리화할 때 수익이 발생합니다 (간격당 0.15%).",
      how2: "레벨에 따라 해당 수익의 퍼센트를 받습니다: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "활성 스테이크와 FIFO 상한 공간이 필요합니다. 수익은 총 스테이크의 3X로 제한됩니다."
    },
    cms: {
      subtitle: "CMS 구독 구매 및 KAIRO 보상 획득",
      connectWalletTitle: "코어 멤버십",
      notAvailable: "CMS 사용 불가",
      notAvailableDesc: "코어 멤버십 구독 계약이 아직 배포되지 않았습니다.",
      yourSubscriptions: "내 구독",
      remainingSlots: "남은 슬롯",
      subscriptionStatus: "구독 상태",
      active: "활성",
      ended: "종료",
      purchaseSubscription: "구독 구매",
      subscriptionEnded: "구독 기간이 종료되었습니다",
      numberOfSubscriptions: "구독 수",
      enterAmount: "금액 입력...",
      subscriptionDetails: "구독 세부정보",
      pricePerSub: "구독당 가격:",
      loyaltyRewardPerSub: "구독당 충성도 보상:",
      totalCost: "총 비용:",
      youllEarn: "획득 예정:",
      approveUsdt: "USDT 승인",
      subscribeBtn: "구독 ({cost} USDT)",
      completeRegistrationFirst: "먼저 등록을 완료하세요",
      claimRewards: "보상 청구",
      alreadyClaimed: "보상을 이미 청구했습니다",
      loyaltyRewards: "충성도 보상",
      leadershipRewards: "리더십 보상",
      totalClaimable: "총 청구 가능",
      claimRules: "청구 규칙",
      claimRule1: "1회 청구 (사용하거나 잃음)",
      claimRule2: "StakingManager에 활성 스테이크 필요",
      claimRule3: "활성 스테이크 가치로 제한 (초과분 삭제)",
      claimRule4: "90% 귀하에게 민트, 10% 디플레이션 (민트 안 함)",
      excessWarning: "경고: {amount} KAIRO가 영구 삭제됩니다 (스테이크 상한 초과)",
      maxClaimable: "최대 청구 가능 (스테이크 기준):",
      claimRewardsBtn: "보상 청구",
      leadershipRewardsTitle: "리더십 보상 (5 레벨)",
      levelCol: "레벨",
      requiredDirectsCol: "필요 직접",
      rewardPerSubCol: "구독당 보상",
      subscriptionsCol: "구독",
      earnedCol: "획득 (KAIRO)",
      levelLabel: "레벨 {level}",
      howCmsWorks: "CMS 작동 방식",
      subscriptionBenefits: "구독 혜택",
      benefit1: "구독당 10 USDT (총 최대 10,000)",
      benefit2: "구독당 5 KAIRO 충성도 보상 획득",
      benefit3: "5 추천 레벨에서 리더십 보상 획득",
      benefit4: "활성 스테이크로 1회 청구 (사용하거나 잃음)",
      referralRewards: "추천 보상",
      level1Desc: "구독당 1 KAIRO (직접 0명 필요)",
      level2Desc: "구독당 0.5 KAIRO (직접 2명 필요)",
      level3Desc: "구독당 0.5 KAIRO (직접 3명 필요)",
      level4Desc: "구독당 0.25 KAIRO (직접 4명 필요)",
      level5Desc: "구독당 0.25 KAIRO (직접 5명 필요)",
      level1: "레벨 1:",
      level2: "레벨 2:",
      level3: "레벨 3:",
      level4: "레벨 4:",
      level5: "레벨 5:"
    },
    analytics: {
      title: "프로토콜 분석",
      subtitle: "실시간 KAIRO 생태계 통계",
      kairoPrice: "KAIRO 가격",
      marketCap: "시가총액",
      poolLiquidityUsdt: "풀 유동성 (USDT)",
      totalBurned: "총 소각",
      tokenSupply: "토큰 공급",
      deflationaryNote: "소각을 통한 디플레이션 메커니즘",
      circulating: "유통 중",
      burned: "소각됨",
      effectiveSupply: "유효 공급",
      socialLock: "소셜 락",
      burnRate: "소각률",
      liquidityPool: "유동성 풀",
      dexPoolComposition: "DEX 풀 구성",
      kairoInPool: "풀 내 KAIRO",
      usdtInPool: "풀 내 USDT",
      pricePerSupply: "가격 (USDT / 총 공급)"
    },
    portfolio: {
      totalPortfolioValue: "총 포트폴리오 가치",
      activeStakes: "활성 스테이크",
      totalStaked: "총 스테이크",
      totalEarned: "총 획득",
      remainingCapping: "남은 상한",
      kairoPrice: "KAIRO 가격",
      poolLiquidity: "풀 유동성",
      totalCirculation: "총 유통",
      harvestableAffiliate: "수확 가능 (제휴)",
      activeDirects: "활성 직접"
    },
    activeStakesTable: {
      title: "활성 스테이크",
      loading: "스테이크 로딩 중...",
      empty: "활성 스테이크 없음. 보상 받으려면 스테이킹 시작!",
      tierCount: "{count} 등급",
      stakeCount: "{count} 스테이크",
      stakedAmount: "스테이크 금액",
      capProgress: "3X 상한 진행",
      harvestable: "수확 가능",
      harvested: "수확됨",
      totalEarned: "총 획득",
      pendingCompoundProfit: "대기 중 복리 수익",
      autoCompound: "자동 복리",
      autoCompoundBtn: "자동 복리 ({count})",
      accruing: "누적 중",
      harvest: "수확 ${amount}",
      minHarvestStake: "최소 $10/스테이크",
      minHarvestAmount: "최소 $10",
      intervals: "간격"
    },
    income: {
      title: "수익 요약",
      typesCount: "{count} 종류",
      direct: "직접 커미션",
      team: "팀 배당",
      rank: "랭크 급여",
      harvest: "수확",
      pendingHarvest: "대기 수확",
      affiliateHarvested: "제휴 수확됨",
      directLabel: "직접",
      teamLabel: "팀",
      rankLabel: "랭크",
      stakingEarnings: "스테이킹 수익",
      harvestedLabel: "수확됨",
      harvestableLabel: "수확 가능"
    },
    faucet: {
      testnetFaucet: "테스트넷 파셋 · 모의 USDT",
      mintDesc: "개발용 테스트 USDT 발행. 현재 잔액:",
      mint10000: "10,000 USDT 발행",
      mint: "발행",
      customPlaceholder: "사용자 정의",
      mintingPending: "테스트 USDT 발행 중…",
      mintingDesc: "지갑으로 {amount} USDT 전송 중",
      mintedSuccess: "{amount} 테스트 USDT 발행 완료",
      mintFailed: "발행 실패",
      invalidAmount: "잘못된 금액"
    },
    common: {
      connectWalletTitle: "지갑 연결",
      connectWalletDesc: "포트폴리오를 보고 스테이크를 관리하며 수익을 추적하려면 지갑을 연결하세요."
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
