import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const messagesDir = path.join(__dirname, '..', 'src', 'i18n', 'messages');

function deepMerge(target, source) {
  for (const key in source) {
    if (typeof source[key] === 'object' && source[key] !== null && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

const translations = {
  de: {
    staking: {
      connectWalletTitle: "Verbinde deine Wallet zum Staking",
      closingInterval: "Abschlussintervall",
      newStake: "Neuer Stake",
      amount: "Betrag (USDT)",
      amountPlaceholder: "Betrag eingeben...",
      balanceHelper: "Guthaben: {balance} USDT | Min: 10 USDT | Kein Max Limit",
      autoCompoundEvery: "Auto-Compound alle {interval}",
      approveAndStake: "Genehmigen & Staken ${amount}",
      stakeBtn: "Staken ${amount}",
      yourStakes: "Deine Stakes",
      active: "aktiv",
      noActiveStakesDesc: "Noch keine aktiven Stakes. Erstelle deinen ersten Stake, um zu verdienen!",
      stakeCount: "{count} Stake{count, plural, =1 {} other {s}}",
      totalStaked: "Gesamt gestakt",
      tierHeader: "3X Limit",
      pendingCompoundProfit: "Ausstehender Compound-Gewinn",
      autoCompoundBtn: "Auto-Compound ({count})",
      accruing: "Auflaufend",
      harvestBtn: "Ernten ${amount}",
      minHarvestStake: "Min $10/Stake",
      minHarvestAmount: "Min $10",
      total: "Gesamt",
      tierCol: "Stufe",
      stakedCol: "Gestakt",
      earnedCol: "Verdient",
      harvestedCol: "Geerntet",
      capCol: "3X Limit",
      startedCol: "Gestartet",
      statusCol: "Status",
      actionCol: "Aktion",
      statusActive: "Aktiv",
      statusCapped: "Begrenzt",
      statusClosed: "Geschlossen",
      unstake: "Entstaken",
      unstakeConfirm: "Stake #{index} entfernen?\n\nDu hast ${original} USDT gestakt.\nDu erhältst ~${preview} in KAIRO\n(80% des Kapitals, abzüglich ausstehender geernteter Einnahmen).\n\nDiese Aktion ist unwiderruflich. Fortfahren?",
      calcTitle: "Compound-Rechner",
      calcSubtitle: "Projiziere potenzielle Gewinntwicklung über die Zeit",
      calcStakeAmount: "Stake-Betrag (USDT)",
      calcEnterAmount: "Stake-Betrag eingeben...",
      calcDuration: "Dauer: {count} {count, plural, =1 {Monat} other {Monate}}",
      calcProjectedProfit: "Projizierter Gewinn",
      calcTier: "Stufe",
      calcFrequency: "Frequenz",
      calcCompounds: "Compounds",
      calcNote: "0,15% pro Compound · Stufe & Frequenz automatisch aus Betrag ermittelt",
      levelUnlockTitle: "Team-Dividenden-Level-Freischaltung",
      levelUnlockDesc: "Schalte mehr Team-Dividenden-Level frei, indem du direkte Referrals hinzufügst. Du hast aktuell {count} direkte Referrals und {unlocked} / 15 Level freigeschaltet.",
      directs: "direkte",
      intervals: "Intervalle"
    },
    p2p: {
      subtitle: "Atomarer Peer-to-Peer KAIRO-Handel",
      connectWalletTitle: "Verbinde deine Wallet zum Handeln",
      connectWalletDesc: "Zugang zu Peer-to-Peer KAIRO-Handel",
      dexPrice: "DEX-Preis",
      vol: "Vol",
      noActiveBuyOrders: "Keine aktiven Kaufaufträge",
      noActiveSellOrders: "Keine aktiven Verkaufsaufträge",
      fill: "Erfüllen",
      enterAmount: "Betrag eingeben...",
      usdtAmount: "USDT-Betrag",
      kairoAmount: "KAIRO-Betrag",
      max: "MAX: {amount}",
      balanceLabel: "Guthaben: {amount} {token}",
      dexReferencePrice: "DEX-Referenzpreis",
      tradingFee: "Handelsgebühr",
      estimated: "Geschätzt {token}",
      approveAndCreateBuy: "Genehmigen & Kaufauftrag erstellen",
      createBuyOrder: "Kaufauftrag erstellen",
      approveAndCreateSell: "Genehmigen & Verkaufsauftrag erstellen",
      createSellOrder: "Verkaufsauftrag erstellen",
      noActiveOrders: "Du hast keine aktiven Aufträge.",
      noActiveOrdersDesc: "Erstelle einen Kauf- oder Verkaufsauftrag, um zu beginnen.",
      myBuyOrders: "Meine Kaufaufträge",
      mySellOrders: "Meine Verkaufsaufträge",
      cancel: "Abbrechen",
      remaining: "${amount} verbleibend",
      filledOfTotal: "${filled} erfüllt von ${total} gesamt",
      kairoRemaining: "{amount} KAIRO verbleibend"
    },
    swap: {
      title: "Swap",
      subtitle: "Einweg-Swap mit {fee}% Gebühr und deflationärem Burn",
      connectWalletTitle: "Verbinde deine Wallet zum Swappen",
      connectWalletDesc: "Einweg-KAIRO-zu-USDT-Swap mit deflationärem Burn",
      poolUsdt: "Pool-USDT",
      kairoToUsdt: "KAIRO → USDT",
      swapBurnNote: "Swap beinhaltet deflationären Burn",
      youPay: "Du zahlst",
      youReceive: "Du erhältst (geschätzt)",
      rate: "Kurs",
      fee: "Gebühr ({percent}%)",
      minOutput: "Min. Ausgabe ({slippage}% Slippage)",
      slippage: "Slippage:",
      priceImpact: "Preisauswirkung",
      approveAndSwap: "Genehmigen & Swappen",
      swapBtn: "Swap KAIRO → USDT",
      max: "MAX: {amount}"
    },
    referralNetwork: {
      title: "Referral-Netzwerk",
      rank: "Rang",
      directReferrals: "Direkte Referrals",
      directActive: "{count} aktiv",
      directBusiness: "Direktes Volumen",
      referralStakes: "Referral-Stakes",
      teamBusiness: "Team-Volumen",
      totalDownlineVolume: "gesamtes Downline-Volumen",
      shareLink: "Teile deinen Link, um neue Mitglieder einzuladen und Multi-Level-Provisionen zu verdienen.",
      earnDirect: "Verdiene 5% direkte Provision + 15-Level-Team-Dividenden bei jedem Referral-Stake."
    },
    rankDividend: {
      title: "Rang-Dividende",
      subtitle: "Erreiche Ränge durch Team-Volumen und verdiene regelmäßige Gehaltsbelohnungen",
      connectWalletTitle: "Verbinde deine Wallet",
      rankChangeDetected: "Rangänderung erkannt: {from} → {to}",
      rankChangeDesc: "Dein Gehalts-Timer wird beim Bestätigen zurückgesetzt. Klicke unten, um deinen Rang zu aktualisieren.",
      updateRank: "Rang aktualisieren",
      currentRank: "Aktueller Rang",
      rankLevel: "Level {level} / 10",
      rankSalary: "Rang-Gehalt",
      perPeriod: "pro Periode",
      harvestable: "Erntbar",
      crystallized: "kristallisiert",
      harvested: "Geerntet",
      totalClaimed: "gesamt beansprucht",
      rankProgress: "Rang-Fortschritt",
      earningPerPeriod: "Verdiene ${amount} / Periode",
      pending: "Ausstehend: ${amount} · klicke Sync zum Kristallisieren",
      syncRankChange: "Rangänderung synchronisieren",
      syncRankSalary: "Rang-Gehalt synchronisieren (+${amount})",
      nothingToSync: "Nichts zu synchronisieren",
      harvestBtn: "Ernten ${amount}",
      nothingToHarvest: "Nichts zu ernten",
      teamVolumeTitle: "Team-Volumen",
      totalTeamVolume: "Gesamt-Team-Volumen",
      next: "Weiter: {rank}",
      targetMet: "Ziel erreicht!",
      needMoreVolume: "Brauchst ${amount} mehr qualifizierendes Volumen",
      progressAchieved: "{percent}% erreicht",
      directReferrals: "Direkte Referrals",
      activeDirects: "Aktive Directs",
      unlockedLevels: "Freigeschaltete Level",
      harvestIncomeTitle: "Ernte-Einnahmen",
      direct: "Direkt",
      team: "Team",
      rank: "Rang",
      harvest: "Ernte",
      fiftyPctCapRule: "50% Pro-Bein-Cap-Regel",
      fiftyPctDesc: "Für jedes Rang-Ziel kann maximal 50% der Schwelle dieses spezifischen Rangs aus einem einzigen Bein gutgeschrieben werden. Dein persönliches Volumen zählt nicht zur Rang-Qualifizierung. Selbst wenn ein einzelnes Bein massives Volumen hat, werden nur 50% des Rang-Ziels gutgeschrieben.",
      totalTeamVolumeLabel: "Gesamt-Team-Volumen",
      largestLeg: "Größtes Bein",
      numberOfLegs: "Anzahl Beine",
      qualifyingVolume: "Qualifizierendes Volumen",
      legVolumeBreakdown: "Bein-Volumen-Aufschlüsselung",
      leg: "Bein {index}",
      maxCredited: "(max ${amount})",
      rankTargetsTitle: "Rang-Ziele & Gehälter",
      rankCol: "Rang",
      teamVolumeTargetCol: "Team-Volumen-Ziel",
      salaryCol: "Gehalt / Periode",
      progressCol: "Fortschritt",
      statusCol: "Status",
      achieved: "Erreicht",
      nextTarget: "Nächstes Ziel",
      locked: "Gesperrt",
      salaryHistoryTitle: "Gehaltsverlauf",
      records: "{count} Einträge",
      loadingHistory: "Verlauf wird geladen...",
      noSalaryHistory: "Noch kein Gehaltsverlauf. Erreiche einen Rang, um zu verdienen!",
      typeCol: "Typ",
      dateCol: "Datum",
      amountCol: "Betrag",
      txCol: "Tx",
      salaryCredited: "Gehalt gutgeschrieben",
      harvestedLabel: "Geerntet"
    },
    teamDividend: {
      title: "Team-Dividende",
      subtitle: "Verdiene aus 15 Leveln von Team-Compound-Gewinnen basierend auf deiner Anzahl direkter Referrals. Inaktive Nutzer in der Kette werden übersprungen — nur aktive Stake-Teilnehmer zählen als Level.",
      connectWalletTitle: "Verbinde deine Wallet",
      connectWalletDesc: "Sieh dir deine Team-Dividenden-Einnahmen an",
      unlockedLevels: "Freigeschaltete Level",
      directReferrals: "Direkte Referrals",
      moreForNext: "{count} mehr für nächstes Level",
      maxLevelsUnlocked: "Max Level freigeschaltet",
      directBusiness: "Direktes Volumen",
      referralStakes: "Referral-Stakes",
      teamVolume: "Team-Volumen",
      totalDownlineVolume: "Gesamtes Downline-Volumen",
      teamDividend: "Team-Dividende",
      harvest: "Ernten",
      activeLabel: "aktiv",
      levelBreakdownTitle: "Level-Aufschlüsselung — Volle Details",
      levelBreakdownDesc: "Jedes Level verdient einen Prozentsatz der Compound-Gewinne, die von aktiven Nutzern auf dieser komprimierten Tiefe generiert werden. Inaktive Nutzer werden übersprungen — sie zählen nicht als Level. L1: 10%, L2-L10: 5% jeweils, L11-L15: 2% jeweils. Schalte Level frei durch Hinzufügen direkter Referrals: 1-5 Directs = 1-5 Level, dann jeder zusätzliche Direct = 2 weitere Level (max 15 bei 10 Directs).",
      levelCol: "Level",
      rateCol: "Rate",
      membersCol: "Mitglieder",
      businessCol: "Volumen",
      earnedCol: "Verdient",
      statusCol: "Status",
      statusActive: "Aktiv",
      statusNext: "Weiter",
      statusLocked: "Gesperrt",
      total: "Gesamt",
      levelLabel: "Level {level}",
      directsNeeded: "{count} Direct{count, plural, =1 {} other {s}}",
      levelActivationTracker: "Level-Aktivierungs-Tracker",
      levelActivationDesc: "Du hast {directs} direkte Referrals, was {unlocked} / 15 Team-Dividenden-Level freischaltet.",
      ppl: "Pers.",
      legs: "{count} Beine",
      legVolumeBreakdown: "Bein-Volumen-Aufschlüsselung",
      legVolumeDesc: "Jeder direkte Referral bildet ein \"Bein\". Sein gesamtes nachgelagertes Volumen trägt zu deinem Team-Volumen und Rang-Qualifizierung bei.",
      refCol: "Referral",
      selfStakeCol: "Eigener Stake",
      legVolumeCol: "Bein-Volumen",
      shareCol: "Anteil",
      howItWorks: "Wie Team-Dividenden funktionieren",
      how1: "Wenn ein Nutzer in deinem Team seinen Stake compounded, wird Gewinn generiert (0,15% pro Intervall).",
      how2: "Du verdienst einen Prozentsatz dieses Gewinns basierend auf dem Level: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "Erfordert aktiven Stake und FIFO-Cap-Speicherplatz. Einnahmen sind auf 3X deines Gesamt-Stakes begrenzt."
    },
    cms: {
      subtitle: "Kaufe CMS-Abonnements und verdiene KAIRO-Belohnungen",
      connectWalletTitle: "Kern-Mitgliedschaft",
      notAvailable: "CMS nicht verfügbar",
      notAvailableDesc: "Der Kern-Mitgliedschafts-Abonnementvertrag ist noch nicht bereitgestellt.",
      yourSubscriptions: "Deine Abonnements",
      remainingSlots: "Verbleibende Slots",
      subscriptionStatus: "Abonnement-Status",
      active: "Aktiv",
      ended: "Beendet",
      purchaseSubscription: "Abonnement kaufen",
      subscriptionEnded: "Der Abonnementzeitraum ist beendet",
      numberOfSubscriptions: "Anzahl Abonnements",
      enterAmount: "Betrag eingeben...",
      subscriptionDetails: "Abonnement-Details",
      pricePerSub: "Preis pro Abonnement:",
      loyaltyRewardPerSub: "Treue-Belohnung pro Abonnement:",
      totalCost: "Gesamtkosten:",
      youllEarn: "Du verdienst:",
      approveUsdt: "USDT genehmigen",
      subscribeBtn: "Abonnieren ({cost} USDT)",
      completeRegistrationFirst: "Bitte schließe zuerst die Registrierung ab",
      claimRewards: "Belohnungen beanspruchen",
      alreadyClaimed: "Du hast deine Belohnungen bereits beansprucht",
      loyaltyRewards: "Treue-Belohnungen",
      leadershipRewards: "Führungs-Belohnungen",
      totalClaimable: "Gesamt beanspruchbar",
      claimRules: "Beanspruchungs-Regeln",
      claimRule1: "Einmalige Beanspruchung nur (nutzen oder verlieren)",
      claimRule2: "Erfordert aktiven Stake im StakingManager",
      claimRule3: "Begrenzt durch aktiven Stake-Wert (Überschuss wird gelöscht)",
      claimRule4: "90% dir gemintet, 10% deflationär (nicht gemintet)",
      excessWarning: "Warnung: {amount} KAIRO werden dauerhaft gelöscht (überschreitet Stake-Cap)",
      maxClaimable: "Max beanspruchbar (basierend auf Stake):",
      claimRewardsBtn: "Belohnungen beanspruchen",
      leadershipRewardsTitle: "Führungs-Belohnungen (5 Level)",
      levelCol: "Level",
      requiredDirectsCol: "Benötigte Directs",
      rewardPerSubCol: "Belohnung/Abonnement",
      subscriptionsCol: "Abonnements",
      earnedCol: "Verdient (KAIRO)",
      levelLabel: "Level {level}",
      howCmsWorks: "Wie CMS funktioniert",
      subscriptionBenefits: "Abonnement-Vorteile",
      benefit1: "10 USDT pro Abonnement (max 10.000 gesamt)",
      benefit2: "Verdiene 5 KAIRO Treue-Belohnung pro Abonnement",
      benefit3: "Verdiene Führungs-Belohnungen aus 5 Referral-Leveln",
      benefit4: "Einmal beanspruchen mit aktivem Stake (nutzen oder verlieren)",
      referralRewards: "Referral-Belohnungen",
      level1Desc: "1 KAIRO pro Abonnement (0 Directs erforderlich)",
      level2Desc: "0,5 KAIRO pro Abonnement (2 Directs erforderlich)",
      level3Desc: "0,5 KAIRO pro Abonnement (3 Directs erforderlich)",
      level4Desc: "0,25 KAIRO pro Abonnement (4 Directs erforderlich)",
      level5Desc: "0,25 KAIRO pro Abonnement (5 Directs erforderlich)",
      level1: "Level 1:",
      level2: "Level 2:",
      level3: "Level 3:",
      level4: "Level 4:",
      level5: "Level 5:"
    },
    analytics: {
      title: "Protokoll-Analytik",
      subtitle: "Echtzeit-KAIRO-Ökosystem-Statistiken",
      kairoPrice: "KAIRO-Preis",
      marketCap: "Marktkapitalisierung",
      poolLiquidityUsdt: "Pool-Liquidität (USDT)",
      totalBurned: "Gesamt verbrannt",
      tokenSupply: "Token-Angebot",
      deflationaryNote: "Deflationäre Mechanismen durch Burn",
      circulating: "Im Umlauf",
      burned: "Verbrannt",
      effectiveSupply: "Effektives Angebot",
      socialLock: "Social Lock",
      burnRate: "Burn-Rate",
      liquidityPool: "Liquiditäts-Pool",
      dexPoolComposition: "DEX-Pool-Zusammensetzung",
      kairoInPool: "KAIRO im Pool",
      usdtInPool: "USDT im Pool",
      pricePerSupply: "Preis (USDT / Gesamt-Angebot)"
    },
    portfolio: {
      totalPortfolioValue: "Gesamter Portfoliowert",
      activeStakes: "Aktive Stakes",
      totalStaked: "Gesamt gestakt",
      totalEarned: "Gesamt verdient",
      remainingCapping: "Verbleibendes Limit",
      kairoPrice: "KAIRO-Preis",
      poolLiquidity: "Pool-Liquidität",
      totalCirculation: "Gesamtumlauf",
      harvestableAffiliate: "Erntbar (Affiliate)",
      activeDirects: "Aktive Directs"
    },
    activeStakesTable: {
      title: "Aktive Stakes",
      loading: "Stakes werden geladen...",
      empty: "Keine aktiven Stakes. Starte Staking, um Belohnungen zu verdienen!",
      tierCount: "{count} Stufe(n)",
      stakeCount: "{count} Stake{count, plural, =1 {} other {s}}",
      stakedAmount: "Gestakter Betrag",
      capProgress: "3X-Cap-Fortschritt",
      harvestable: "Erntbar",
      harvested: "Geerntet",
      totalEarned: "Gesamt verdient",
      pendingCompoundProfit: "Ausstehender Compound-Gewinn",
      autoCompound: "Auto-Compound",
      autoCompoundBtn: "Auto-Compound ({count})",
      accruing: "Auflaufend",
      harvest: "Ernten ${amount}",
      minHarvestStake: "Min $10/Stake",
      minHarvestAmount: "Min $10",
      intervals: "Intervalle"
    },
    income: {
      title: "Einnahmen-Übersicht",
      typesCount: "{count} Typen",
      direct: "Direkte Provision",
      team: "Team-Dividenden",
      rank: "Rang-Gehalt",
      harvest: "Ernte",
      pendingHarvest: "Ausstehende Ernte",
      affiliateHarvested: "Affiliate geerntet",
      directLabel: "Direkt",
      teamLabel: "Team",
      rankLabel: "Rang",
      stakingEarnings: "Staking-Einnahmen",
      harvestedLabel: "Geerntet",
      harvestableLabel: "Erntbar"
    },
    faucet: {
      testnetFaucet: "Testnet-Faucet · Mock-USDT",
      mintDesc: "Minte Test-USDT für Entwicklung. Aktuelles Guthaben:",
      mint10000: "10.000 USDT minten",
      mint: "Minten",
      customPlaceholder: "benutzerdefiniert",
      mintingPending: "Test-USDT wird gemintet…",
      mintingDesc: "Sende {amount} USDT an deine Wallet",
      mintedSuccess: "{amount} Test-USDT gemintet",
      mintFailed: "Minten fehlgeschlagen",
      invalidAmount: "Ungültiger Betrag"
    },
    common: {
      connectWalletTitle: "Verbinde deine Wallet",
      connectWalletDesc: "Verbinde deine Wallet, um dein Portfolio zu sehen, Stakes zu verwalten und Einnahmen zu verfolgen."
    }
  },

  ar: {
    staking: {
      connectWalletTitle: "اتصل بمحفظتك للستيكينج",
      closingInterval: "فترة الإغلاق",
      newStake: "ستيك جديد",
      amount: "المبلغ (USDT)",
      amountPlaceholder: "أدخل المبلغ...",
      balanceHelper: "الرصيد: {balance} USDT | الحد الأدنى: 10 USDT | لا حد أقصى",
      autoCompoundEvery: "تأليف تلقائي كل {interval}",
      approveAndStake: "موافقة وستيك ${amount}",
      stakeBtn: "ستيك ${amount}",
      yourStakes: "ستيكاتك",
      active: "نشط",
      noActiveStakesDesc: "لا توجد ستيكات نشطة بعد. أنشئ أول ستيك لتبدأ بالكسب!",
      stakeCount: "{count} ستيك",
      totalStaked: "إجمالي الستيك",
      tierHeader: "سقف 3X",
      pendingCompoundProfit: "ربح التأليف المعلق",
      autoCompoundBtn: "تأليف تلقائي ({count})",
      accruing: "تتراكم",
      harvestBtn: "حصاد ${amount}",
      minHarvestStake: "الحد الأدنى $10/ستيك",
      minHarvestAmount: "الحد الأدنى $10",
      total: "الإجمالي",
      tierCol: "الفئة",
      stakedCol: "الستيك",
      earnedCol: "المكسب",
      harvestedCol: "المحصود",
      capCol: "سقف 3X",
      startedCol: "البداية",
      statusCol: "الحالة",
      actionCol: "إجراء",
      statusActive: "نشط",
      statusCapped: "مكتمل",
      statusClosed: "مغلق",
      unstake: "إلغاء الستيك",
      unstakeConfirm: "إلغاء ستيك #{index}؟\n\nستكّت ${original} USDT.\nستتلقى ~${preview} KAIRO\n(80% من الأصل، ناقص أي دخل محصود معلّق).\n\nهذا الإجراء لا يمكن التراجع عنه. هل تريد المتابعة؟",
      calcTitle: "حاسبة التأليف",
      calcSubtitle: "توقع تراكم الأرباح المحتمل بمرور الوقت",
      calcStakeAmount: "مبلغ الستيك (USDT)",
      calcEnterAmount: "أدخل مبلغ الستيك...",
      calcDuration: "المدة: {count} شهر",
      calcProjectedProfit: "الربح المتوقع",
      calcTier: "الفئة",
      calcFrequency: "التكرار",
      calcCompounds: "التأليفات",
      calcNote: "0.15% لكل تأليف · الفئة والتكرار يُكتشفان تلقائياً من المبلغ",
      levelUnlockTitle: "فتح مستوى أرباح الفريق",
      levelUnlockDesc: "افتح المزيد من مستويات أرباح الفريق بإضافة إحالات مباشرة. لديك حالياً {count} إحالات مباشرة و {unlocked} / 15 مستوى مفتوح.",
      directs: "مباشرين",
      intervals: "فترات"
    },
    p2p: {
      subtitle: "تداول KAIRO من نظير لنظير ذري",
      connectWalletTitle: "اتصل بمحفظتك للتداول",
      connectWalletDesc: "الوصول إلى تداول KAIRO من نظير لنظير",
      dexPrice: "سعر DEX",
      vol: "حجم",
      noActiveBuyOrders: "لا توجد أوامر شراء نشطة",
      noActiveSellOrders: "لا توجد أوامر بيع نشطة",
      fill: "تنفيذ",
      enterAmount: "أدخل المبلغ...",
      usdtAmount: "مبلغ USDT",
      kairoAmount: "مبلغ KAIRO",
      max: "الحد الأقصى: {amount}",
      balanceLabel: "الرصيد: {amount} {token}",
      dexReferencePrice: "سعر مرجعي DEX",
      tradingFee: "رسوم التداول",
      estimated: "{token} المقدر",
      approveAndCreateBuy: "موافقة وإنشاء أمر شراء",
      createBuyOrder: "إنشاء أمر شراء",
      approveAndCreateSell: "موافقة وإنشاء أمر بيع",
      createSellOrder: "إنشاء أمر بيع",
      noActiveOrders: "ليس لديك أوامر نشطة.",
      noActiveOrdersDesc: "أنشئ أمر شراء أو بيع للبدء.",
      myBuyOrders: "أوامر الشراء الخاصة بي",
      mySellOrders: "أوامر البيع الخاصة بي",
      cancel: "إلغاء",
      remaining: "${amount} متبقي",
      filledOfTotal: "${filled} منفذ من ${total} الإجمالي",
      kairoRemaining: "{amount} KAIRO متبقي"
    },
    swap: {
      title: "مبادلة",
      subtitle: "مبادلة باتجاه واحد برسم {fee}% وحرق انكماشي",
      connectWalletTitle: "اتصل بمحفظتك للمبادلة",
      connectWalletDesc: "مبادلة KAIRO إلى USDT باتجاه واحد مع حرق انكماشي",
      poolUsdt: "USDT في البركة",
      kairoToUsdt: "KAIRO ← USDT",
      swapBurnNote: "تشمل المبادلة حرقاً انكماشياً",
      youPay: "تدفع",
      youReceive: "تستلم (تقديري)",
      rate: "السعر",
      fee: "الرسم ({percent}%)",
      minOutput: "الحد الأدنى للإخراج ({slippage}% انزلاق)",
      slippage: "الانزلاق:",
      priceImpact: "تأثير السعر",
      approveAndSwap: "موافقة ومبادلة",
      swapBtn: "مبادلة KAIRO ← USDT",
      max: "الحد الأقصى: {amount}"
    },
    referralNetwork: {
      title: "شبكة الإحالة",
      rank: "الرتبة",
      directReferrals: "الإحالات المباشرة",
      directActive: "{count} نشط",
      directBusiness: "الحجم المباشر",
      referralStakes: "ستيكات الإحالة",
      teamBusiness: "حجم الفريق",
      totalDownlineVolume: "إجمالي حجم الخط السفلي",
      shareLink: "شارك رابطك لدعوة أعضاء جدد وكسب عمولات متعددة المستويات.",
      earnDirect: "اكسب 5% عمولة مباشرة + أرباح فريق من 15 مستوى لكل ستيك إحالة."
    },
    rankDividend: {
      title: "أرباح الرتبة",
      subtitle: "حقق الرتب من خلال حجم الفريق واكسب مكافآت راتب دورية",
      connectWalletTitle: "اتصل بمحفظتك",
      rankChangeDetected: "تم اكتشاف تغيير الرتبة: {from} → {to}",
      rankChangeDesc: "سيتم إعادة ضبط مؤقت راتبك عند التأكيد. انقر أدناه لتحديث رتبتك.",
      updateRank: "تحديث الرتبة",
      currentRank: "الرتبة الحالية",
      rankLevel: "المستوى {level} / 10",
      rankSalary: "راتب الرتبة",
      perPeriod: "لكل فترة",
      harvestable: "قابل للحصاد",
      crystallized: "مبلور",
      harvested: "محصود",
      totalClaimed: "إجمالي المطالب به",
      rankProgress: "تقدم الرتبة",
      earningPerPeriod: "تكسسب ${amount} / فترة",
      pending: "معلّق: ${amount} · انقر مزامنة للتبلور",
      syncRankChange: "مزامنة تغيير الرتبة",
      syncRankSalary: "مزامنة راتب الرتبة (+${amount})",
      nothingToSync: "لا شيء للمزامنة",
      harvestBtn: "حصاد ${amount}",
      nothingToHarvest: "لا شيء للحصاد",
      teamVolumeTitle: "حجم الفريق",
      totalTeamVolume: "إجمالي حجم الفريق",
      next: "التالي: {rank}",
      targetMet: "تم تحقيق الهدف!",
      needMoreVolume: "تحتاج ${amount} حجم مؤهل إضافي",
      progressAchieved: "{percent}% محقق",
      directReferrals: "الإحالات المباشرة",
      activeDirects: "المباشرون النشطون",
      unlockedLevels: "المستويات المفتوحة",
      harvestIncomeTitle: "دخل الحصاد",
      direct: "مباشر",
      team: "فريق",
      rank: "رتبة",
      harvest: "حصاد",
      fiftyPctCapRule: "قاعدة سقف 50% لكل فرع",
      fiftyPctDesc: "لكل هدف رتبة، يمكن احتساب 50% كحد أقصى من عتبة تلك الرتبة المحددة من أي فرع واحد. حجمك الشخصي لا يحتسب ضمن تأهيل الرتبة. حتى لو كان لفرع واحد حجم ضخم، سيُحتسب فقط 50% من هدف الرتبة منه.",
      totalTeamVolumeLabel: "إجمالي حجم الفريق",
      largestLeg: "أكبر فرع",
      numberOfLegs: "عدد الفروع",
      qualifyingVolume: "الحجم المؤهل",
      legVolumeBreakdown: "تفصيل حجم الفروع",
      leg: "الفرع {index}",
      maxCredited: "(الحد الأقصى ${amount})",
      rankTargetsTitle: "أهداف ورواتب الرتب",
      rankCol: "الرتبة",
      teamVolumeTargetCol: "هدف حجم الفريق",
      salaryCol: "الراتب / الفترة",
      progressCol: "التقدم",
      statusCol: "الحالة",
      achieved: "محقق",
      nextTarget: "الهدف التالي",
      locked: "مقفل",
      salaryHistoryTitle: "سجل الرواتب",
      records: "{count} سجل",
      loadingHistory: "تحميل السجل...",
      noSalaryHistory: "لا يوجد سجل رواتب بعد. حقق رتبة لتبدأ الكسب!",
      typeCol: "النوع",
      dateCol: "التاريخ",
      amountCol: "المبلغ",
      txCol: "معاملة",
      salaryCredited: "راتب مُضاف",
      harvestedLabel: "محصود"
    },
    teamDividend: {
      title: "أرباح الفريق",
      subtitle: "اكسب من 15 مستوى من أرباح تأليف الفريق بناءً على عدد إحالاتك المباشرة. يتم تخطي المستخدمين غير النشطين في السلسلة — فقط المساهمين النشطين يُحتسبون كمستويات.",
      connectWalletTitle: "اتصل بمحفظتك",
      connectWalletDesc: "اعرض أرباح فريقك",
      unlockedLevels: "المستويات المفتوحة",
      directReferrals: "الإحالات المباشرة",
      moreForNext: "{count} إضافية للمستوى التالي",
      maxLevelsUnlocked: "تم فتح جميع المستويات",
      directBusiness: "الحجم المباشر",
      referralStakes: "ستيكات الإحالة",
      teamVolume: "حجم الفريق",
      totalDownlineVolume: "إجمالي حجم الخط السفلي",
      teamDividend: "أرباح الفريق",
      harvest: "حصاد",
      activeLabel: "نشط",
      levelBreakdownTitle: "تفصيل المستوى — التفاصيل الكاملة",
      levelBreakdownDesc: "يكتسب كل مستوى نسبة مئوية من أرباح التأليف التي يولدها المستخدمون النشطون عند ذلك العمق المضغوط. يتم تخطي المستخدمين غير النشطين — لا يُحتسبون كمستوى. L1: 10%, L2-L10: 5% لكل واحد, L11-L15: 2% لكل واحد. افتح المستويات بإضافة إحالات مباشرة: 1-5 مباشرين = 1-5 مستويات, ثم كل إضافة مباشرة = 2 مستويات إضافية (الحد الأقصى 15 عند 10 مباشرين).",
      levelCol: "المستوى",
      rateCol: "النسبة",
      membersCol: "الأعضاء",
      businessCol: "الحجم",
      earnedCol: "المكتسب",
      statusCol: "الحالة",
      statusActive: "نشط",
      statusNext: "التالي",
      statusLocked: "مقفل",
      total: "الإجمالي",
      levelLabel: "المستوى {level}",
      directsNeeded: "{count} مباشر",
      levelActivationTracker: "متتبع تفعيل المستويات",
      levelActivationDesc: "لديك {directs} إحالات مباشرة، تفتح {unlocked} / 15 مستوى أرباح فريق.",
      ppl: "شخص",
      legs: "{count} فروع",
      legVolumeBreakdown: "تفصيل حجم الفروع",
      legVolumeDesc: "كل إحالة مباشرة تشكل \"فرعاً\". حجمها الإجمالي المصب يساهم في حجم فريقك وتأهيل رتبتك.",
      refCol: "الإحالة",
      selfStakeCol: "الستيك الذاتي",
      legVolumeCol: "حجم الفرع",
      shareCol: "الحصة",
      howItWorks: "كيف تعمل أرباح الفريق",
      how1: "عندما يؤلف أي مستخدم في فريقك ستيكه، يُولد ربح (0.15% لكل فترة).",
      how2: "تكتسب نسبة من ذلك الربح بناءً على المستوى: L1=10%, L2-L10=5%, L11-L15=2%.",
      how3: "يتطلب ستيك نشط ومساحة في سقف FIFO. الأرباح محدودة بـ 3X من إجمالي ستيكك."
    },
    cms: {
      subtitle: "اشترك في CMS واكسب مكافآت KAIRO",
      connectWalletTitle: "عضوية أساسية",
      notAvailable: "CMS غير متاح",
      notAvailableDesc: "عقد اشتراك العضوية الأساسية لم يُنشر بعد.",
      yourSubscriptions: "اشتراكاتك",
      remainingSlots: "المواضع المتبقية",
      subscriptionStatus: "حالة الاشتراك",
      active: "نشط",
      ended: "منتهي",
      purchaseSubscription: "شراء اشتراك",
      subscriptionEnded: "انتهت فترة الاشتراك",
      numberOfSubscriptions: "عدد الاشتراكات",
      enterAmount: "أدخل المبلغ...",
      subscriptionDetails: "تفاصيل الاشتراك",
      pricePerSub: "السعر لكل اشتراك:",
      loyaltyRewardPerSub: "مكافأة الولاء لكل اشتراك:",
      totalCost: "التكلفة الإجمالية:",
      youllEarn: "ستكتسب:",
      approveUsdt: "موافقة USDT",
      subscribeBtn: "اشترك ({cost} USDT)",
      completeRegistrationFirst: "يرجى إكمال التسجيل أولاً",
      claimRewards: "استلام المكافآت",
      alreadyClaimed: "لقد استلمت مكافآتك بالفعل",
      loyaltyRewards: "مكافآت الولاء",
      leadershipRewards: "مكافآت القيادة",
      totalClaimable: "إجمالي قابل للاستلام",
      claimRules: "قواعد الاستلام",
      claimRule1: "استلام لمرة واحدة فقط (استخدمها أو افقدها)",
      claimRule2: "يتطلب ستيك نشط في StakingManager",
      claimRule3: "محدود بقيمة الستيك النشط (الفائض يُحذف)",
      claimRule4: "90% يُسك لك، 10% انكماشي (لا يُسك)",
      excessWarning: "تحذير: {amount} KAIRO سيتم حذفها نهائياً (تتجاوز سقف الستيك)",
      maxClaimable: "الحد الأقصى للاستلام (بناءً على الستيك):",
      claimRewardsBtn: "استلام المكافآت",
      leadershipRewardsTitle: "مكافآت القيادة (5 مستويات)",
      levelCol: "المستوى",
      requiredDirectsCol: "المباشرون المطلوبون",
      rewardPerSubCol: "المكافأة/اشتراك",
      subscriptionsCol: "الاشتراكات",
      earnedCol: "المكتسب (KAIRO)",
      levelLabel: "المستوى {level}",
      howCmsWorks: "كيف يعمل CMS",
      subscriptionBenefits: "فوائد الاشتراك",
      benefit1: "10 USDT لكل اشتراك (الحد الأقصى 10,000 إجمالياً)",
      benefit2: "اكسب 5 KAIRO مكافأة ولاء لكل اشتراك",
      benefit3: "اكسب مكافآت قيادة من 5 مستويات إحالة",
      benefit4: "استلم مرة واحدة مع ستيك نشط (استخدمها أو افقدها)",
      referralRewards: "مكافآت الإحالة",
      level1Desc: "1 KAIRO لكل اشتراك (0 مباشرين مطلوبين)",
      level2Desc: "0.5 KAIRO لكل اشتراك (2 مباشرين مطلوبين)",
      level3Desc: "0.5 KAIRO لكل اشتراك (3 مباشرين مطلوبين)",
      level4Desc: "0.25 KAIRO لكل اشتراك (4 مباشرين مطلوبين)",
      level5Desc: "0.25 KAIRO لكل اشتراك (5 مباشرين مطلوبين)",
      level1: "المستوى 1:",
      level2: "المستوى 2:",
      level3: "المستوى 3:",
      level4: "المستوى 4:",
      level5: "المستوى 5:"
    },
    analytics: {
      title: "تحليلات البروتوكول",
      subtitle: "إحصائيات نظام KAIRO في الوقت الفعلي",
      kairoPrice: "سعر KAIRO",
      marketCap: "القيمة السوقية",
      poolLiquidityUsdt: "سيولة البركة (USDT)",
      totalBurned: "إجمالي المحروق",
      tokenSupply: "عرض الرموز",
      deflationaryNote: "آليات انكماشية عبر الحرق",
      circulating: "متداول",
      burned: "محروق",
      effectiveSupply: "العرض الفعلي",
      socialLock: "قفل اجتماعي",
      burnRate: "معدل الحرق",
      liquidityPool: "بركة السيولة",
      dexPoolComposition: "تكوين بركة DEX",
      kairoInPool: "KAIRO في البركة",
      usdtInPool: "USDT في البركة",
      pricePerSupply: "السعر (USDT / إجمالي العرض)"
    },
    portfolio: {
      totalPortfolioValue: "إجمالي قيمة المحفظة",
      activeStakes: "الستيكات النشطة",
      totalStaked: "إجمالي الستيك",
      totalEarned: "إجمالي المكسب",
      remainingCapping: "السقف المتبقي",
      kairoPrice: "سعر KAIRO",
      poolLiquidity: "سيولة البركة",
      totalCirculation: "إجمالي التداول",
      harvestableAffiliate: "قابل للحصاد (تسويق)",
      activeDirects: "مباشرون نشطون"
    },
    activeStakesTable: {
      title: "الستيكات النشطة",
      loading: "تحميل الستيكات...",
      empty: "لا توجد ستيكات نشطة. ابدأ الستيكينج لكسب المكافآت!",
      tierCount: "{count} فئة",
      stakeCount: "{count} ستيك",
      stakedAmount: "المبلغ المُستثمر",
      capProgress: "تقدم سقف 3X",
      harvestable: "قابل للحصاد",
      harvested: "محصود",
      totalEarned: "إجمالي المكسب",
      pendingCompoundProfit: "ربح التأليف المعلق",
      autoCompound: "تأليف تلقائي",
      autoCompoundBtn: "تأليف تلقائي ({count})",
      accruing: "تتراكم",
      harvest: "حصاد ${amount}",
      minHarvestStake: "الحد الأدنى $10/ستيك",
      minHarvestAmount: "الحد الأدنى $10",
      intervals: "فترات"
    },
    income: {
      title: "ملخص الدخل",
      typesCount: "{count} أنواع",
      direct: "عمولة مباشرة",
      team: "أرباح الفريق",
      rank: "راتب الرتبة",
      harvest: "حصاد",
      pendingHarvest: "حصاد معلق",
      affiliateHarvested: "تسويق محصود",
      directLabel: "مباشر",
      teamLabel: "فريق",
      rankLabel: "رتبة",
      stakingEarnings: "أرباح الستيكينج",
      harvestedLabel: "محصود",
      harvestableLabel: "قابل للحصاد"
    },
    faucet: {
      testnetFaucet: "حنفية Testnet · USDT تجريبي",
      mintDesc: "أنشئ USDT تجريبي للتطوير. الرصيد الحالي:",
      mint10000: "إنشاء 10,000 USDT",
      mint: "إنشاء",
      customPlaceholder: "مخصص",
      mintingPending: "جاري إنشاء USDT تجريبي…",
      mintingDesc: "إرسال {amount} USDT إلى محفظتك",
      mintedSuccess: "تم إنشاء {amount} USDT تجريبي",
      mintFailed: "فشل الإنشاء",
      invalidAmount: "مبلغ غير صالح"
    },
    common: {
      connectWalletTitle: "اتصل بمحفظتك",
      connectWalletDesc: "اتصل بمحفظتك لعرض محفظتك وإدارة ستيكاتك ومتابعة أرباحك."
    }
  }
};

for (const [locale, tr] of Object.entries(translations)) {
  const filePath = path.join(messagesDir, `${locale}.json`);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  deepMerge(content, tr);
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
  console.log(`${locale}: updated`);
}
console.log('Done!');
